### ISSUE TITLE
Vocab terms "to an audience"

### ISSUE THREAD

**Issue by riannella** [w3c/poe#101]
There are 4 vocab actions that end in "...to an audience":
- present
- display
- play
- textToSpeech

Typically, the right to "publicly perform" is an additional right (compared to me only allowed to play my music in private at home.)

I would like to recommend "...to an audience" be removed and if you need to express "the audience" then you can use the "recipient" constraint.

@nitmws I recall these were added from the legal review in 2015 ?

**Comment by nitmws** [comment]
If "to an audience" is removed the actions present, display, play and textToSpeech should include a note requiring to add a recipient party to define a private or open audience.

**Comment by riannella** [comment]
I think the definition of Present is an issue. It was originally defined in ODRL 2.0 more like a synonym for play, and display - but now has a very broad definition: "...perform or exhibit an Asset"

For "Present" to be a true parent to Play/Display/Print it's definition will need to reflect that.

 I would suggest something like: "...to render the Asset in visual or static form."

(The other changes have been made.)

**Comment by nitmws** [comment]
As I recall the Action vocabulary discussion for ODRL 2.1 the intention of Present was to define at a generic level: this action is targeting an audience beyond the assignees = the assignee is the party presenting the asset to a wider/public/b2c audience. All the other sub-terms of "use" are actions in the context of the assignee only. And the "real" actions of presenting the asset are the sub-terms of Present.
Therefore it is no surprise that taking away the "to a (public) audience" leaves a term with small semantics.

The suggested suffix above is unclear and limiting: is playing a MP3 file covered by "visual or static form", and what exactly is rending an asset in static form?
And this raises a basic issue (again): the current ODRL specs do not explicitly define that an Asset MUST be digital. (... can ODRL be used to grant the display of an artwork from a museum?)

Note on the use of the Recipient constraint. The current language may surprise a reader: a _constraint_ should be used to _widen_ the group of people using the asset - that's a contradiction at first sight and hard to understand. The most bullet proof variant is to claim for Present and all its sub-terms that the Recipient (the Assignee or more people) must be defined by a constraint.

**Comment by riannella** [comment]
Sorry @nitmws, the intention of "Present" was to be a parent to play/display/print - so you would have one action that covered 3 "common" actions in the expression.

If you look at: https://www.w3.org/community/odrl/vocab/2.0/
You can see "present" as a synonym for Play and Display

**Comment by riannella** [comment]
I would recommend we deprecate Present.

**Comment by riannella** [comment]
..as it touches on, but does not complete the economic rights:
Reproduction Right
Distribution Right
Public Performance Right
Fixation Right
Communication Right
Transformation Right

**Comment by riannella** [comment]
Alternatively, we can define Present as an action for  play/display a (multimedia) asset.
ie, the Parent to play and display (only)

Having said that....
play is only for audio assets, and display *seems* defined only for static visual asset.
what about a movie?

I think "play" should be update to "audio/video" asset

**Comment by vroddon** [comment]
...or MediaResource as in the Ontology for Media Resources.
https://www.w3.org/TR/mediaont-10/#ont-ttl

**Comment by riannella** [comment]
A "multimedia" asset ?

**Comment by vroddon** [comment]
good!

**Comment by riannella** [comment]
@nitmws Any comments/feedback?

**Comment by riannella** [comment]
Proposal:

1 - update "play" definition  to "The Assigner permits/prohibits the Assignees to perform a multimedia Asset"

2 - deprecate "present"

comments?

**Comment by riannella** [comment]
Alternative for 2)

- Leave "Present" as the action to perform/exhibit the asset, but remove it as the parent of play/display/print

**Comment by riannella** [comment]
Done (as per above)

commit: a4697a3
