### ISSUE TITLE
Definition of policy

### ISSUE THREAD

**Issue by vroddon** [w3c/poe#102]
@sereAbi I suggest we replace this definition

> Policy
>     A set of rules defining what is allowed, disallowed or obligatory over a resource.

with this one:

> Policy
>     A set of rules defining what is allowed, disallowed or obligatory over **_an Asset_**.

**Comment by riannella** [comment]
"over a resource" should be "an Asset" in all the terms in section "1.4 Terminology"
(Resource and Content are not formally part of the IM).
We should also up the ontology to match

**Comment by vroddon** [comment]
I have changed the definitions in the ontology according to this. 

The current definition of Action does not make me happy: 

> Action: A set of operations...

I believe should read

> Action
> **An operation** that can be allowed by Permissions, disallowed by Prohibitions, or made obligatory by Duties.
> 

In any case, these are the definitions as I have left in the ontology.

> 
> Policy A set of rules defining what is allowed, disallowed or obligatory over an Asset.
> Rule A set of actions defining the precise Permissions, Prohibitions and Obligations over an Asset.
> Action A set of operations that can be allowed by Permissions, disallowed by Prohibitions, or made obligatory by Duties.
> Permission A set of actions that are allowed to be performed over an Asset.
> Prohibition A set of actions that are forbidden to be performed over an Asset.
> Duty A set of actions that are obliged to be performed over an Asset.
> Asset The subject of a Policy that permissions and prohibitions are applied to.
> Party Any form of identifiable entity that is the object of a Policy, e.g., a person, a group of people, an organisation, or an agent.
> Constraint The limits and restrictions to the Permissions, the Prohibitions and the Duties expressed in the Policy.

**Comment by riannella** [comment]
Sounds OK

**Comment by vroddon** [comment]
Done! I leave the issue open as a reminder to Serena/Renato to change the definition in the Information Model text...

**Comment by simonstey** [comment]
> Duty A set of actions that are obliged to be performed over an Asset.

is that true though?

1. A duty may not have a target asset (in contrast to perms/prohibs)
2. A duty can only be defined for perms, thus isn't affected by the expansion mechanism defined in [3.1.1 Policy Structures](http://w3c.github.io/poe/model/#structure) 
3. It's missing the whole "*A Permission entity MAY include a Duty entity that indicates a requirement that MUST be satisfied in order to undertake the Permission.*" part.

**Comment by riannella** [comment]
That was not correct. It has been updated in the terminology section:
 http://w3c.github.io/poe/model/#terminology

**Comment by vroddon** [comment]
I have updated again the ontology to reflect two changes in the terminology:
- Capital letter for "Rules" in the definition of :Policy
- A longer definition for :Party
As I am not aware of further issues, we may want to close this issue.

**Comment by riannella** [comment]
@vroddon I removed " .. e.g., a person, a group of people, an organisation, or an agent." from the Definition as it is coved in the skos:note
(and definitions should not include examples ;-)

**Comment by riannella** [comment]
My update:

Duty - A set of Actions that are obliged to be performed for Permissions.
Asset - The subject of a Policy that Rules are applied to.
Constraint -The limits and restrictions to Actions in Rules
