### ISSUE TITLE
Add "stream" to Vocab

### ISSUE THREAD

**Issue by riannella** [w3c/poe#103]
"Streaming" is a common action for media now.
I recommend we add this.
Should it also be a narrower term of Present?

**Comment by simonstey** [comment]
> http://streamreasoning.github.io/RSP-QL/RSP_Requirements_Design_Document/

unfortunately for data in general too, cf. http://streamreasoning.github.io/RSP-QL/RSP_Requirements_Design_Document/

**Comment by riannella** [comment]
Leave definition broad.
Not a narrower version of Present

**Comment by riannella** [comment]
Stream added. Please review.
