### ISSUE TITLE
This specification doesn't appear to have any 'Privacy' or 'Security' considerations sections.

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#109]
Respec now raises following warning: 

> This specification doesn't appear to have any 'Privacy' or 'Security' considerations sections. Please consider adding one, see https://w3ctag.github.io/security-questionnaire/

How do we address this?

**Comment by riannella** [comment]
Looks like "w3c" changed Respec for "ED" documents.
We can raise an issue.
But the UCR will become a "WG-NOTE" when we release the dated version

**Comment by iherman** [comment]
> On 20 Feb 2017, at 08:26, simon <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> Respec now raises following warning:
> 
> This specification doesn't appear to have any 'Privacy' or 'Security' considerations sections. Please consider adding one, see https://w3ctag.github.io/security-questionnaire/ <https://w3ctag.github.io/security-questionnaire/>
> How do we address this?
> 
This is indeed a new feature of Respec (it is only a warning, though).

We did talk about looking at the horizontal issues and surveys. Then we can see. But the section on privacy or security can be as simple a saying that this spec does not raise any of those issues; it is a sign that the group has considered the problem i the first place.

All that being said: we we plan to publish is a draft. It is perfectly o.k. if the relevant section says: "T.B.D."

**Comment by riannella** [comment]
I think this is occurring in the UCR NOTE, so in reality, should not need such a section.

**Comment by riannella** [comment]
@simonstey feedback from respec team:

as a quick fix, you can set:
  lint: false,
in your ReSpec config. That should turn off that warning.

**Comment by simonstey** [comment]
ah cool thx
