### ISSUE TITLE
Ordering of the contents of the Vocab section

### ISSUE THREAD

**Issue by riannella** [w3c/poe#11]
Here is a proposed ordering of the Vocab section:
1 - Model Concepts
2 - Policy Types
3 - Actions for Permissions/Prohibitions
4 - Actions for Duties
5 - Constraints
6 - Constraint Operators
7 - Party Roles
8 - Party Scopes
9 - Asset Relations
10 - Deprecated Concepts

How to do this from the owl ontology?
For classes we can group them into SKOS collections.
For properties?
For individuals?

**Comment by riannella** [comment]
And we need an updated figure to visually show the groupings as well.

**Comment by nevali** [comment]
We can create some local top-level objects in the RDF that the other things form part of (via dct:isPartOf and similar), and I can tweak our version of phpspecgen to only pay attention to those objects but not to express them themselves. This does mean minting some new dummy identifiers, but they can be done carefully so as not to conflict with ones we're likely to create in the future (e.g., use fragments rather then slash-URIs from the base). I'll annotate the groups with a comment that they exist for organisation purposes only and are not themselves terms which form part of the expression.

In the template, we'll probably end up with something like these…

``` php
<?php

/* express the contents of http://www.w3.org/ns/odrl/2/#modelConcepts */
writeGroup('#modelConcepts');

/* express the contents of http://www.w3.org/ns/odrl/2/#policyTypes */
writeGroup('#policyTypes');

/* etc */

?>
```

Each one gets written as a section, with an optional HTML file in `vocab/parts/` to provide an intro/description.

How does that sound?

**Comment by riannella** [comment]
Can we use SKOS as the expression of the groups?
If we created a SKOS Collection for each of the 10 groups (see above), then the script can work as you indicated, but the ontology will keep it semantic-ness?

**Comment by riannella** [comment]
@nevali As a test, I have added some SKOS Collection examples (see lines 67-100 of .ttl) as test for grouping. Do you think that could work?

**Comment by riannella** [comment]
@nevali I have added all the terms now to all the SKOS Collections.
I assume that in the template for (example):
  writeGroup('#policyTypes');
It will then create a new section (with H2 of the skos:prefLabel), then add any html text from /parts/policyTypes.html
Then each skos:member will be iterated and output as it is now (new section and the two tables).
(hopefully the order is preserved ;-)

Also, we may do this later, it would be nice to make the Deprecated Terms look different from the rest.  Perhaps we can use a different shaded colour background (for now)? And later, present it as one summarised table (one row per term).
