### ISSUE TITLE
@uid vs @id

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#111]
some examples use `@uid` some `@id`.. shouldn't all examples use `@id`?

**Comment by vroddon** [comment]
I understand @id within JSON-LD but... what is @uid? I just checked there is no meaning for that in the spec...

**Comment by simonstey** [comment]
`uid` is a legacy attribute of ODRL, see e.g., ->

> uid: the unique identification of the Policy entity (REQUIRED)

**Comment by riannella** [comment]
I thought I had swapped them all over (to @id) - will do now...
The uid (from the model) is mapped to @id for JSON-LD

**Comment by riannella** [comment]
Done

**Comment by simonstey** [comment]
why do we substitute @id with uid?

**Comment by riannella** [comment]
That ended up no being correct, as the JSON-LD context does the mapping from the IM's uid to an id

**Comment by aisaac** [comment]
I too am really curious why there is such mapping in the JSON-LD context, instead of just re-using JSON-LD's basic @id. The latter would be really much, much simpler to understand for these who are even vaguely familiar with JSON-LD.

**Comment by riannella** [comment]
At this teleconf: https://www.w3.org/2017/04/24-poe-minutes
it was discussed (by @iherman ) to use the names of that the IM uses (eg uid over @id)

**Comment by aisaac** [comment]
Yes I guess my question is more for IM than Vocab. Why would IM be committed to uid?

**Comment by riannella** [comment]
@vroddon You are right. uid is missing :-)
Now added

fc5b514c6911424e9e092c9b1927dcf2dc88087e
