### ISSUE TITLE
Definition of odrl:delayPeriod

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#115]
The description of Example 27 in Section 3.8.1 Constraint Relations [1] states:

> The Policy below shows a Permission to distribute photos in which the first constraint (the event "football/game/2017" has passed) is statisfied, then the second constraint (wait for 60 minutes) is processed, and is then satisfied. **(Note: The operator value of andSequence is not the same as and as for the latter, both operand Constraints must be satisfied, but could be processed at the same time.)** 

Which is wrong considering the definition of `odrl:delayPeriod` which itself imposes some sort of temporal dependency, hence doesn't rely on `odrl:andSequence` for doing so[2]: 

> The Action may be executed after the end of this period. **The starting time of the period is triggered by the satisfaction of another temporal constraint in a Constraint Relation.**

(ignoring imprecise wording for now) 

[1] http://w3c.github.io/poe/model/#constraint-relations
[2] https://w3c.github.io/poe/vocab/#term-delayPeriod

**Comment by nitmws** [comment]
I agree the wording of Example 27-related things need clarification:

* Re Action Delay Period in http://w3c.github.io/poe/vocab/#term-delayPeriod
Its definition could be modified to: The Action may be exercised after the end of this period. The point in time triggering this period MAY be defined by another temporal constraint with an odrl:andSequence relationship expressed by a Constrations Relation.

* Re constraint http://example.com/policy:88/C1: I think this constraint is wrong in this context as its satisfaction does not set a point in time. The odrl:event LeftOperand is defined as "An identified event used for exercising the Action." And even its Note does not help as by a strict interpretation the constraint C1 could be already satisfied in the first second of the event (operator is `>=`) and not at its closing time. As discussed in the context of developing the `andSequence` operator a LeftOperand like Event Closing Time is required for this purpose. 

* Re Note of Example 27: could be modified to "The operator `andSequence` requires that first the constraint in the leftOperand is satisfied - the event has closed - and this triggers the Action Delay Period after which the action of the permission may be excercised.

**Comment by riannella** [comment]
1) Perhaps delayPeriod should be less specific about *how* the point in time to trigger the delay is from an odrl:andSequence, but that there must be a point-in-time expressed somehwhere/how?
(as we should allow the definitions of these concepts stand-alone - another ISO11179 principle)

2) If the operator is odrl:gt, then that would work?

3) ok

**Comment by nitmws** [comment]
* re 1/"stand-alone": we have a POE use case and we have segmented its ODRL implementation into related particles. Therefore it makes sense to include such relationships into a specification as it helps a user to quickly find out what particles are of big help. To align to ISO11179 we could avoid pointing at odrl:andSequence in the Definition of the Action Delay Period but we should add a hint about odrl:andSequence as Note. The ODRL Vocab document uses already Notes for pointing at formats of a LeftOperand.

**Comment by riannella** [comment]
Yes, Notes are good.

**Comment by riannella** [comment]
Updated
