### ISSUE TITLE
JSON example - fix repeated properties

### ISSUE THREAD

**Issue by riannella** [w3c/poe#116]
Need to fix the JSON examples where we have repeated the same property

**Comment by Kizilaslan** [comment]
Sahinbeybelediye27@hotmail.com

**Comment by riannella** [comment]
fixed example 4 and 5

**Comment by iherman** [comment]
Just to to miss it: same issue with examples 26 and 27

**Comment by riannella** [comment]
Fixed examples 13, 14, 22, 26, 27
