### ISSUE TITLE
Vocab Time examples

### ISSUE THREAD

**Issue by riannella** [w3c/poe#118]
Give better examples for the 5 time-based constraint actions (to make it clearer how they are used and their differences)

dateTime
delayPeriod
elapsedTime
meteredTime
timeInterval

**Comment by nitmws** [comment]
I'll reflect use cases I'm aware of as news/media guy:

* dateTime: 
option 1: the Action of the Rule may be exercised before (operator lt/lteq) or after (operatior gt/gteq) the date defined by the rightOperand. My use case: an article may be shown only until 13 April 2017 = for 1 month from now.
option 2: the Action of the Rule may be exercised inside a period of time = between the start date/time and end date/time of the period.
The open issues I see there are: a) is the only relevant operator eq only? (What would lt or gt mean?) and b) when does the period start and implicitly end??? Does this has to be defined elsewhere - and if: where exactly?
_My comment: in fact a period could also be expressed by two dateTime constraints setting the start dateTime (with operator gteq) and the end date/time (with operator lteq). Why not exclude the use of dateTime for a period and add a note about this use?_
* delayPeriod: the Action of the Rule may be exercised only after a period of time = after the end date/time of the period. The definition/a note of delayPeriod tells how to set the start date/time of the period.
The open issue I see: what operators may/should be used? (Would be worth a Note)
* elapsedTime: the Action of the Rule may be exercised inside a period of time, the start date/time of this  set by the date/time of executing the Action for a first time. In fact this can only be measured by a party knowing the date/time of the first time execution.
The open issue I see: what operators may/should be used? (Would be worth a Note)
* meteredTime: the time of actively exercising the Action of the Rule must align with a period of time. My example: a photo may be used until 31 Dec 2017, this is set by dateTime. And a second constraint defines when the photo is shown (in an electronic environment) it must not be shown longer than for 30 seconds, then it has to disappear for ?? seconds/minutes ... 
This LeftOperand is currently not well defined.
The open issue I see: what operators may/should be used? (Would be worth a Note)
* timeInterval: sets the period between the recurring executions of the Action of the Rule. My example: a video may be displayed, but a timeInterval of PT1H defines only 1 hour after the end of displaying it it may be shown again.

My considerations:
* dateTime could be simplified and clarified by removing its use for a period of time.
* it would be worth to review all LeftOperands expressing a period of time:
  * how to define when the period starts. This could be a persistent dateTime (in a second constraint?) or a dynamic dateTime, both or only the latter related by andSequence, or an explicitly relative one like for elapsedTime
  * define what the operators can express: lt = before the period, gt = after the period, we may need two additional ones: "insidePeriod" = at any time inside a period, "outsidePeriod" = at any time outside the period.
 
General note: the specs of period-like LeftOperands claim the period has to be expressed as represented in xmlschema11-2 (linked without any deep linking). Unfortunately XML Schema 1.1 doesn't specify anything about periods, it only knows about duration. Linking to duration may mix up semantics and format requirements.

**Comment by riannella** [comment]
I also like the idea of dateTime just being explicit datetimes only - no Periods (durations), as in P2H, as then we have the "when does it start" issue (otherwise it is the same as elapsedTime).

Also, elapsedTime, meteredTime, and timeInterval are all time periods (xsd:duration), and all "start" the moment you first exercise the action.

**Comment by riannella** [comment]
Comments from wide review:
  https://lists.w3.org/Archives/Public/public-poe-comments/2017Mar/0012.html
Confirm our need to clarify scope of dateTime to explicit datetime values only

**Comment by riannella** [comment]
Proposal: remove "period" from datetime definition

And add some narrative examples to the other time-based terms.

@nitmws Comments?

**Comment by riannella** [comment]
Removed period support from dateTime and updated time-based terms with examples

Commit a196056e6daede396d6b1332ab1c6f2855e47af0
