### ISSUE TITLE
1.4 Terminology

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#119]
I've some remarks regarding the definitions given in Section [1.4 Terminology](http://w3c.github.io/poe/model/#terminology):

> Policy: A set of Rules defining what is allowed, disallowed or obligatory over an Asset.

That's afaik only partially true, as duties do not operate on the same level as permissions/prohibitions and as such do not define _"what is obligatory over an Asset"_, but define obligations for performing their respective permission(s) they are attached to.

> Rule: **A set of Actions** defining the precise Permissions, Prohibitions and obligations over an Asset.

A rule is _"a set of actions"_? How can _"a set of actions"_ define _"the precise Permissions, Prohibitions and obligations over an Asset"_? Isn't Rule an abstract concept anyway? 
Why lowercase _"obligations"_ ?

> Permission/Prohibition/Duty: **A set of Actions** that are ...

as mentioned above

> Duty: A set of Actions that are obliged **to be performed for Permissions.**

What permissions? all? 
Why? What does _"performed for Permissions"_ mean/imply (in general and for respective permissions)?

> Asset: **The subject of a Policy** that Rules are applied to.

So there's only 1 asset / policy?

> Constraint: The limits and restrictions to Actions in Rules.

What's the difference between limits and restrictions? 

simon

**Comment by riannella** [comment]
Here is my proposal (everything is defined in the singular):

Policy - A Rule expressing what Action is allowed and/or disallowed over an Asset.
Rule - A Permission, Prohibition or Duty that expresses an Action that may, must not, and must be performed (respectively),
Action - An operation that is applicable to an Asset
Permission - An Action that may be performed over an Asset.
Prohibition - An Action that must not be performed over an Asset.
Duty - An Action that must be performed as a requirement for the applicable Permission to become valid.
Asset - An identifiable resource that is the subject of the Rule.
Party - An identifiable entity who may undertake a Role in the Policy.
Constraint - The context, such as limitations, restrictions, or interpretations, that must be applied to an Action.

**Comment by vroddon** [comment]
@riannella 
Implemented, save for the first one: Policy is not " A Rule expressing...." for it can comprise many rules.
Current definition is:
_"A set of Rules defining what is allowed, disallowed or obligatory over an Asset."_
Proposed definition was:
_"A Rule expressing what Action is allowed and/or disallowed over an Asset."_
My proposal:
_"A Rule expressing what Actions are allowed and/or disallowed over one or more Assets."_

**Comment by riannella** [comment]
True, but for consistency I defined everything in the singular, as your definition is also true, but not when there is one action. That is, the atomic (non-reducible) definitions.

**Comment by riannella** [comment]
Updated the Model

**Comment by simonstey** [comment]
the model document isn't loading properly for me..
I think you've messed up some html tags while updating it ;)

**Comment by riannella** [comment]
try now...

**Comment by simonstey** [comment]
> Policy: A Rule expressing what Action is allowed and/or disallowed over an Asset.

only 1 rule/action/asset?

> Rule: A Permission, Prohibition or Duty that expresses an Action that may, must not, **and** must be performed (respectively)

s/and/or

> Action: An operation that is applicable to an Asset

not sure if _applicable to_ fits here.. (I'm not a native though)

**Comment by vroddon** [comment]
For the first: see a few commens above. My proposal was: "A Rule expressing what Actions are allowed and/or disallowed over one or more Assets."

For the second: I don't see it wrong, but I am not native either.

**Comment by riannella** [comment]
1) "A" is used as in the indefinite article - it can refer to any Rule. 
But it is the *information model* that is normative in terms of cardinality of the defined terms.

2) fixed

3) What about "an operation that may be applied to an asset" ?

**Comment by riannella** [comment]
@simonstey @vroddon Any comments/Feedback?

**Comment by vroddon** [comment]
@riannella Comments:

1) The definition for agreement is formulated in an unclear manner, it should be in singular form and I find it too strong (talking about contracts and licenses).  

> Agreement: a) Policy expressions that are formal contracts (licenses) stipulating all the terms of usage and all the parties involved.

Also Assertion is plural, whereas Offer singular. 

2) Article. Some definitions have it, some not. 

> Offer: Policy expression that proposes terms of usage from an Asset owner.

vs

> Asset:  An identifiable resource that is the subject of a Rule.

3) Some of the elements are defined by their use. 

> Undefined Term: Is used to indicate how to support Actions that are not part of any vocabulary or profile in the policy expression system.

We might define them instead as:

> Undefined Term: Class of Actions that are not part of any vocabulary or profile in the policy expression system.

**Comment by riannella** [comment]
Proposal: some consistency in the policy types: 

 Agreement: A Policy that grants the assignee a Rule over an Asset from an assigner.
 Offer: A Policy that proposes a Rule over an Asset from an assigner.
  Request: A Policy that proposes a Rule over an Asset from an assignee.
 Assertion: A Policy that asserts a Rule over an Asset from parties.
 Privacy: A Policy that expresses a Rule over an Asset containing personal information.
 Set: A Policy that expresses a Rule over an Asset.
 Ticket:  A Policy that grants the holder a Rule over an Asset from an assigner.

**Comment by riannella** [comment]
RE: Undefined Term

Is it the "class of actions" or the class of "ways to process" undefined actions?

**Comment by vroddon** [comment]
@riannella I have updated the Turtle file to include the latest version of the definitions.

Agree that "class of actions" is not correct, because other classes are not defined as "class of...".  
Revision: cf13891d2bbad9bc49d3a54b1b2e44761c4d3cde

**Comment by simonstey** [comment]
reopen because of #74

**Comment by riannella** [comment]
This is now being tracked in #74
