### ISSUE TITLE
3.3.2 (Party) Scope

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#120]
[3.3.2 Scope](http://w3c.github.io/poe/model/#party-scope) states: 

> group: indicates that the Party entity represents a group. The group consisting of many individual members. The linked Permission, Duty or Prohibition is applicable for each member of that group. For example, a Permission to play a movie 5 times is valid for each Party member **or the Duty to pay 3 EUR has to be fulfilled by each Party member.**

[3.4 Permission](http://w3c.github.io/poe/model/#permission) states: 

> The Permission entity MAY refer to one or more duty/ies. **The Duty expresses an obligation that MUST be fulfilled before the Permission being granted.**

If a permission with a duty is defined for an assignee with scope `group`, **all** members of that group have to fulfill the duty in order for the permission to be granted?

**Comment by riannella** [comment]
Correct.

**Comment by riannella** [comment]
@simonstey Added "to be closed"...unless there is some change proposal?
