### ISSUE TITLE
On Duties and their Permissions

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#122]
Throughout the entire spec the relationship between permissions and their duties is defined as follows: 

> A Permission entity MAY refer to a Duty entity that indicates **a requirement that MUST be satisfied for Permissions to become valid**. 

> Duty: An Action that **must be performed as a requirement for the applicable Permission to become valid**.

> A Duty indicates that the Policy expresses an Action that MUST be performed **(as a requirement to be granted a Permission**). 

> The Permission entity MAY refer to one or more duty/ies. **The Duty expresses an obligation that MUST be fulfilled in order for the Permission to be valid.**

There are some duty actions, however, which are basically useless given that definition. e.g. an [odrl:uninstall](https://w3c.github.io/poe/vocab/#term-uninstall) duty would require to uninstall/delete an asset before the permission to use respective asset could actually be granted.

[4.18.11 Uninstall](https://w3c.github.io/poe/vocab/#term-uninstall)
> **Definition:** 	The Assigner requires that the Assignees unload and delete the computer program Asset from a storage device and disable its readiness for operation.
>
> **Note:** 	The Asset is no longer accessible to the Assignees.

and no:

> Even though a Duty entity is mandatory, the ODRL model does not specify any conditions on WHEN the Duty Action MUST be performed.  Such business rules MAY be expressed through additional Constraints. For example, a Policy may state that you can play a music file for a payment of $5.00. This does not indicate when the $5.00 should be paid, as different business rules may apply such as montly invoicing.

that paragraph doesn't do the trick (imo)..

**Comment by riannella** [comment]
Yes that is true. If you have a duty to uninstall Asset X in order to play Asset X, then you have pretty bad policy ;-)

Another way to look at this is that the duty could be to uninstall some other asset (using a different target) that competes/conflicts with the permission target asset. 

Should uninstall be deprecated? Others?

**Comment by riannella** [comment]
update the duties to include "the requirement is **agreed** to satisfied/fulfilled"

**Comment by riannella** [comment]
Updated duty narrative to include “agreed” as part of the semantics.
@simonstey please check you are ok with the changes

**Comment by simonstey** [comment]
> A Permission entity MAY refer to a Duty entity that indicates an agreed requirement that MUST be satisfied for Permissions to become valid.

->

A Permission MAY refer to one or more Duties which indicate obligations that MUST be fulfilled in order for the Permission to be valid.

also: (imo) you can only **fulfill** a duty, but not **satisfy** it. 


fwiw: I found a [paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.666.1141&rep=rep1&type=pdf) discussing the differences between "pre-obligations" and "post-obligations".

**Comment by riannella** [comment]
Change commited
