### ISSUE TITLE
Synchronize (addition to vocab)

### ISSUE THREAD

**Issue by riannella** [w3c/poe#123]
Original Feedback: https://lists.w3.org/Archives/Public/public-poe-comments/2017Apr/0000.html

===========
FROM: Luca Andrea Ludovico <ludovico@di.unimi.it>, Paolo Perlasca <perlasca@di.unimi.it>, Adriano Baratè <barate@di.unimi.it>, "Prof. Goffredo Haus" <haus@di.unimi.it> 

in response to your request for comments, I am forwarding to you some proposals of ODRL definitions coming from the IEEE 1599 staff, together with some remarks.
We hope that this can improve the documentation produced by the POE working group.
 
Greeting from Milan.
 
Luca
 
 
 
Vocabulary
 
Synchronize
Definition: The assigner Permits/Prohibits the Assignees to perform a synchronized experience using the asset (as a part of the experience) to an audience.
Label: Synchronize
Identifier: http://www.w3.org/ns/odrl/2/synchronize
Class: Action
 
 
Ontology
 
Synchronize
The assigner Permits/Prohibits the Assignees to perform a synchronized experience using the asset (as a part of the experience) to an audience.
URI: http://www.w3.org/ns/odrl/2/synchronize
Label: Synchronize
Status: ?stable?
Broader terms: use
Class: Action
Concept scheme: actions
 
 
POE Use Cases and Requirements
 
2.24 POE.UC.24: Synchronization in a multilayer music description environment
 
Laboratorio di Informatica Musicale (LIM), Department of Computer Science, Universitá degli Studi di Milano
 
IEEE 1599 is an international XML-based standard that aims to comprehensively describe music content by supporting the representation of heterogeneous music aspects within a single XML document.
Moreover, IEEE 1599 lets spatio-temporal relationships emerge among such materials, thanks to the identification of music events inside a common data structure known as the spine: in this way, events can be described in different layers (e.g., a chord's graphical
aspect and its audio performance), as well as multiple times within a single layer (e.g., different music performances of the same events).
Consequently, the IEEE 1599 multilayer environment presents two complementary synchronization modes: inter-layer and intra-layer synchronization. Coupling these two categories of synchronization makes it possible to design and implement frameworks
that allow new kinds of interaction with media contents and novel music-experience models, as shown in the Music Box area of the EMIPIU web framework (see the URL above). Recognizing music events and their synchronization can be seen as an
additional intellectual achievement that on one side does not affect the already existing IP rights on media contents, but on the other side requires adequate protection. Consequently, it is desirable to consider a new permission which allows the producer to synchronize different media contents with respect to the other possibly existing permissions, restrictions and duties associated with media contents.
Related Requirements: POE.R.DM.08, POE.R.DM.12, POE.R.V.12
 
3.1.8 POE.R.DM.08: Add a category property to Asset
A new property of the class Asset should define the category of the Asset.
 
POE.UC.01,POE.UC.17,POE.UC.24
 
3.1.12 POE.R.DM.12: Grouping party entities
Being able to assign multiple individuals of type Party to a Group for which permissions/prohibitions/duties can be specified.
 
POE.UC.05,POE.UC.24
 
3.2.8 POE.R.V.12: New Asset Category Vocabulary
Create a new vocabulary with a basic set of terms for the requested new category property of the Asset class.
 
POE.UC.01,POE.UC.17,POE.UC.24

**Comment by vroddon** [comment]
Two ideas:
1) When editing the MPEG-21 Media Value Chain Ontology, several parties participating in the standard's edition claimed that Synchronization was an action of utter importance for them to have.
2) The definition we are given is not sound, as we are using the defined term within the definition. 

MVCO's definition was: "Concurrent performance/display of two distinct Works or Adaptation Instances each for a different sense e.g. text and audio or video and song. Synchronization implies the simultaneous rendition of two IP Entities requiring the additional Permission of the Creator."

**Comment by riannella** [comment]
Yes, it is big thing now in the music industry - when you license your music for a movie or TV show.
I think we can come up with a slightly better definition as @vroddon suggests.

**Comment by riannella** [comment]
**Proposal: add new vocab term:

synchronize: The assigner Permits/Prohibits the Assignee to use the Asset in timed relations with media (audio/visual) elements of another Asset.**

**Comment by riannella** [comment]
Completed

**Comment by riannella** [comment]
(whoops) Added to vocab now
