### ISSUE TITLE
what is the authoritative 'formal' definition?

### ISSUE THREAD

**Issue by iherman** [w3c/poe#124]
This may just be an editorial point, but we should be careful...

The model document says, in 1.2.

> The ODRL Information Model is formally specified using UML notation

At the same time, section 4 of the vocab document says

> The ODRL Vocabulary formally defines the semantics for the concepts and terms from the ODRL Information Model [odrl-model] and the vocabulary terms that can be used for common use cases for ODRL Policy expressions. 

Do we really mean that the formal semantics is governed by the [UML semantics document](http://www.omg.org/spec/UML/2.5/PDF)? What is then the relationship between the UML Semantics and the RDF semantics underlying the serialization of the vocabulary? These two are not the same (there has been [some collection of document](https://www.w3.org/wiki/UML_and_RDF) on the relationship, which was not really maintained).

As I said, it may only be an editorial issues. The vocabulary is formally defined in RDF, ie, by default, the RDF Semantics applies. UML is used for illustrative purposes, and we should keep away from referring to "formally specified using UML".

(Yes, I am knit-picking...)

**Comment by Kizilaslan** [comment]
27020

**Comment by riannella** [comment]
I think that the line "The ODRL Information Model is formally specified using UML notation" should be removed as the **whole** (normative) document defines the IM (not just Figure 1).

And the term "...formally..." should be removed from the Vocab document.

**Comment by iherman** [comment]
> On 19 Apr 2017, at 14:26, Renato Iannella <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> I think that the line "The ODRL Information Model is formally specified using UML notation" should be removed as the whole (normative) document defines the IM (not just Figure 1).
> 
In any case. As I have just commented elsewhere (#128), I wonder about the value of the UML diagram in the first place.

> And the term "...formally..." should be removed from the Vocab document.
>

**Comment by riannella** [comment]
Ok...some comments on #128

**Comment by simonstey** [comment]
also related: #104 :

> renato: Hmmm...I think you maybe viewing the ODRL Information Model as a direct OWL Ontology model?
**It is independent from any serialisations (and, or course, based on UML).**
The intention is that the IM is mapped to various serialisations (thats what ODRL22.ttl does for OWL/RDF and ODRL22.xsd for XML Schema etc)

**Comment by riannella** [comment]
I think we can remove the UML dependence, and express the IM as _close-as-possible_ to RDF/OWL but not dependently.

**Comment by riannella** [comment]
This is now the same as #128 (so will close this)

**Comment by simonstey** [comment]
> I think we can remove the UML dependence, **and express the IM as close-as-possible to RDF/OWL but not dependently.**

has this happened already?

because the current IM draft still contains references to _relation properties_, _function roles_/_types of function properties_, and other concepts that are only relevant for a potential ODRL XML encoding, but not (or only indirectly) for JSON(-LD) or RDF ones.    

take for example: 

> **A Party MUST have a function** indicating the role undertaken by the Party.

here's a valid JSON-LD encoding of a policy in which `billie` doesn't have "a function that indicates his role":
```json
{
   "@context": "http://www.w3.org/ns/odrl.jsonld",
   "@type": "Offer",
   "uid": "http://example.com/policy:9001",
   "permission": [{
       "target": "http://example.com/music:4545",
       "assigner": "http://example.com/billie",
       "action": "distribute"
   }]
}
```

here's the same policy in XML, in which party `billie` has a function that indicates his role:
```xml
<o:Policy xmlns:o="http://www.w3.org/ns/odrl/2/" uid="http://example.com/policy:9001"
                type="http://www.w3.org/ns/odrl/2/Offer">
    <o:permission>
        <o:asset uid="http://example.com/music:4545" 
                 relation="http://www.w3.org/ns/odrl/2/target"/>
        <o:action name="http://www.w3.org/ns/odrl/2/distribute"/>
        <o:party uid="http://example.com/billie"
             function="http://www.w3.org/ns/odrl/2/assigner"/>
    </o:permission> 
</o:Policy>
```

so unless we replace all JSON-LD examples with XML ones, or update the ODRL ontology along the lines of:

```json
{
   "@context": "http://www.w3.org/ns/odrl.jsonld",
   "@type": "Offer",
   "uid": "http://example.com/policy:9001",
   "permission": [{
       "target": "http://example.com/music:4545",
       "party": [{
           "function": "assigner",
           "uid": "http://example.com/billie"
       }] ,
       "action": "distribute"
   }]
}
```

I see no reason for having legacy XML concepts in the IM.

**Comment by riannella** [comment]
Example 1 does exactly as the model says...Billie has the functional role of "assigner"

Thats what this says:

     "assigner": "http://example.com/billie",

XML simply has a different syntactical way of expressing that...

**Comment by riannella** [comment]
I've added more explanation to section 3.0 on the abstract properties and the need for them to be subtyped. Also added a new figure.
(and @philarcher1 feedback email asked for more clarification)

commit 57115fe8cabcc94e029d86d4b161092b8277df6c
