### ISSUE TITLE
Wrong examples (4 & 5) in the model document

### ISSUE THREAD

**Issue by iherman** [w3c/poe#126]
Example 4 is buggy. It contains the `"target"` key twice, which is a syntax error in JSON. Example 5 is also erroneous for the same reasons. 

Example 5 can be settled by using one `"permission"` key and two elements in the corresponding array (this is the intention!). Example 4, if kept, should make it clear that this would be the _intention_ but is not doable in the JSON syntax. Or something like that.

**Comment by riannella** [comment]
Thanks @iherman - this is the same issue as #116 (and will be fixed now...)
