### ISSUE TITLE
What does Policy merge means (model document)

### ISSUE THREAD

**Issue by iherman** [w3c/poe#130]
It is referred to in 3.1.3. Does it mean like a merge of RDF Graphs? Is it restricted to inheritance or are there other ways of combining policies? (Only inheritance is mentioned in the document.) In any case, it makes sense in 3.1.3 to refer to the policy inheritance, which is probably the most common example. (Maybe even reorder the sections?)

**Comment by riannella** [comment]
Merge can also mean you have a number of policies which could refer to the same Asset and Parties (over time) and you want to ascertain the current set of Rules that are available to you.

Should we add that as narrative? 

Yes, we can reorder the sections.

**Comment by iherman** [comment]
Formally, I presume there may be other possible conflicts, although I did not analysed them. For example, what happens if I merge two Policies on two, totally different assets? I would expect that to be meaningless.

In other words, it is not _only_ to add some narrative, but also to use the narrative to _define_ the merge and specify the cases when the merge is meaningless.

**Comment by simonstey** [comment]
also:

> The conflict attribute is used to establish strategies to resolve conflicts that arise from the merging of Policies or conflicts between Permissions and Prohibitions in the same Policy. 

Isn't that the same? If you merge policies (as in RDF graph merging) you throw all their rules in a new policy, thus any conflicts arising from such a merge are "_conflicts between Permissions and Prohibitions in the same Policy_".

>Conflicts may arise when merging Policies about the same Asset and the resultant Actions are inconsistent.

- what? only the same asset? So if Alice has the permission to use an asset, but Bob is prohibited to use the very same asset, there's a conflict?
- what are resultant actions?
- how do I know if merging policies is inconsistent?

**Comment by riannella** [comment]
Hence why I proposed #138 

Its a difficult space to get into **normatively** given  how complex some policies may become...and perhaps we can make it part of the Formal Semantics NOTE instead?

**Comment by riannella** [comment]
Added inheritance as example/link in Conflict section and reordered both sections.

commit 11d7d64aea230a98a069a509b018e692aa910e7d
