### ISSUE TITLE
What is an ODRL Processor? (Model document)

### ISSUE THREAD

**Issue by iherman** [w3c/poe#131]
The terms comes out of the blue in 3.1.3. It sounds very formal, but not defined...

**Comment by riannella** [comment]
We needed something to refer the "processing rules" to...

Perhaps we can change "ODRL Processor" to something like "...the processing of ODRL expressions..."

?

**Comment by iherman** [comment]
Yeah, that sounds better, but it is still a bit vague. I would prefer to define the term ODRL processor more formally, probably an abstract processor that, given a set of policies and a set of questions (what are they?) gives some meaningful answers. If defined somewhere at the beginning, the term may be used all across the document and may make some of the explanation a bit cleaner. As a bonus, it may be bound to the Semantics document that Victor & Simon may want to publish.

**Comment by riannella** [comment]
Ok, I added a def to the terminology list

**Comment by iherman** [comment]
+1 for me, but we may want to wait the discussion on the semantics before we close the issue. I guess the definition of the Processor is very much at the heart of the semantics document, and they should be in sync.

**Comment by riannella** [comment]
Reopen (and discuss) this in the Formal Semantics NOTE.
