### ISSUE TITLE
(Editorial) use 'code' for URL-s in the text

### ISSUE THREAD

**Issue by iherman** [w3c/poe#132]
Using `<code>` for URL-s in the document may be a good idea, would make things more readable imho.

**Comment by riannella** [comment]
Done. I have added <code> to all hrefs to external URLs.

Need to do Vocab document

**Comment by iherman** [comment]
Hm. I am looking at the document dated 21 April, and I still see:

> The first Policy http://example.com/policy:0001

in the prose right before Example 9 (and there are others). Do you still need to commit?

**Comment by riannella** [comment]
Ok, understand now ;-) 

I've updated the example style to "json" and it all works now

**Comment by iherman** [comment]
The examples are indeed looking fine, but that is #137 ! (Did you comment in a wrong issue?)

The original issue still stands. Eg, in section 3.1.5, it currently says:

> Example Use Case: Consider the parent Policy http://example.com/policy:3333 that has been expressed primarly for inheritance purposes:

and it should say

> Example Use Case: Consider the parent Policy &lt;code>http://example.com/policy:3333 &lt;/code> that has been expressed primarly for inheritance purposes:

(Disregard the fact that the github markdown turns a URI string into a link, that is not the point.)

**Comment by riannella** [comment]
Ok, fixed them all now ;-)
