### ISSUE TITLE
Asset references (Model document)

### ISSUE THREAD

**Issue by iherman** [w3c/poe#134]
Section 3.2 refers to four different ways for identifying assets.

1. URI (possibly with fragments). Apart from the separate issue on IRI-s (#133) that is clear.
2. POWDER. I have several problems with this.
    1. What is exactly the value of the `asset` property in that case? Is it a reference to a full POWDER structure (that would then assign a bunch of attributes to a set of URI-s) or a `<iriset>` with proper `xml:id`?
    1. Alas!, POWDER may be rescinded due to no implementations whatsoever. I wonder whether we should refer to it (sorry Phil!)
3. URI wildcards. Where is that defined? What is it?
4. URI templates. (Maybe that is enough and not refer to URI wildcards?)

Beyond the exact meaning there is also a matter of whether these are normative features or not. If POWDER is rescinded then it is a problem. Actually, rfc6570 is a _proposed_ standard, so a normative reference is probably not a good idea. At the moment, both POWDER and rfc6570 are part of the informative references but… they are referred to in a normative text! Not good...

Furthermore, if these are normative, then there should be at least two implementations. We won't get it, mainly for POWDER.

I think the way we should define this is:

- by default, the asset is a URI or an IRI.
- add an informative note saying that implementations may also accept URI templates as a value to denote several assets, referring to the informative URI template rfc6570
- maybe mention POWDER's `<iriset>` as an alternative, but I would probably prefer not to mention it at all.

**Comment by riannella** [comment]
I am ok with the proposed changes.

@philarcher1 ok if we remove Powder?

**Comment by riannella** [comment]
I have removed all references to POWDER.
