### ISSUE TITLE
Editorial: the formatting of the examples is not consistent (model)

### ISSUE THREAD

**Issue by iherman** [w3c/poe#137]
In many cases `@context` is not intended (it should) and/or the content of `@context` is not intended (it should...). In other cases it is; it should be consistent in the document.

**Comment by riannella** [comment]
Sorry, we are not JSON-LD people ;-) so am not sure what we did wrong here...can you be more specific? thanks...

**Comment by iherman** [comment]
It is, mainly, inconsistent. B.t.w., there is nothing JSON-LD specific, it is simply JSON.

In Example 1:

```json
{
"@context": {
    "odrl": "http://www.w3.org/ns/odrl/2/"
    },
    "@type": "odrl:Set",
    ...
}
```

In Example 3:

```json
{
    "@context": {
    "odrl": "http://www.w3.org/ns/odrl/2/"
    },
    "@type": "odrl:Agreement",
    "@id": "http://example.com/policy:8888",
    ...
}
```

In Example 18:

```json
{
    "@context": [{ "odrl": "http://www.w3.org/ns/odrl/2/",
                   "vCard": "http://www.w3.org/2006/vcard/ns#" }],
    "@type": "odrl:Agreement",
    "@id": "http://example.com/policy:8888",
    "permission": [{
        "target": "http://example.com/music/1999.mp3",
        "assigner":
    ...
}
```

I would simply prefer a standard JSON style. Ie,

```json
{
    "@context": {
        "odrl": "http://www.w3.org/ns/odrl/2/"
    },
    "@type": "odrl:Agreement",
    "@id": "http://example.com/policy:8888",
    ...
}

```

and

```json
{
    "@context": {
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "vCard": "http://www.w3.org/2006/vcard/ns#"
    },
    "@type": "odrl:Agreement",
    "@id": "http://example.com/policy:8888",
    "permission": [{
        "target": "http://example.com/music/1999.mp3",
        "assigner":
   ...
```

(Note, b.t.w., that the current JSON-LD for Example 18 is probably wrong, the context is a single object in all our examples.)

I guess the safe thing is to use a JSON beautifier on all the examples to ensure a unified style.

**Comment by simonstey** [comment]
After skimming through JSON-LD's [5.1 The Context](https://www.w3.org/TR/json-ld/#the-context) section I'm wondering whether we are actually using `"@context"` correctly. (I'm not a JSON-LD expert though)

According to [5.1 The Context](https://www.w3.org/TR/json-ld/#the-context) Example 5: 
```json
{
  "@context":
  {
    "name": "http://schema.org/name",
    "image": {
      "@id": "http://schema.org/image",
      "@type": "@id"
    },
    "homepage": {
      "@id": "http://schema.org/url",
      "@type": "@id"
    }
  },
  "name": "Manu Sporny",
  "homepage": "http://manu.sporny.org/",
  "image": "http://manu.sporny.org/images/manu.png"
}
``` 
A policy like:
```json
{
"@context": {
    "odrl": "http://www.w3.org/ns/odrl/2/"
    },
    "@type": "odrl:Offer",
    "@id": "http://example.com/policy:1012",
    "permission": [{
            "target": "http://example.com/music:1012",
            "action": "odrl:play"
     }]
}
```
should actually look like:
```json
{
 "@context": {
    "odrl": "http://www.w3.org/ns/odrl/2/",
    "permission": "http://www.w3.org/ns/odrl/2/permission",
    "target": "http://www.w3.org/ns/odrl/2/target",
    "action": "http://www.w3.org/ns/odrl/2/action",
    "play": "http://www.w3.org/ns/odrl/2/play"
},
 "@type": "odrl:Offer",
 "@id": "http://example.com/policy:1012",
 "permission": [{
    "target": "http://example.com/music:1012",
    "action": "play"
 }]
}
```
right?

**Comment by iherman** [comment]
You are right. I believe we already said that.

Actually, the better approach is to have a profile file somewhere (containing all those) and make a reference to it from `@context`

**Comment by simonstey** [comment]
> You are right. I believe we already said that.

ah ok

> Actually, the better approach is to have a profile file somewhere (containing all those) and make a reference to it from `@context`

+1

**Comment by riannella** [comment]
Ok, I fixed the consistency of the "context" in all the examples.

We already have a context profile (linked in the Vocab spec):
  https://github.com/w3c/poe/blob/gh-pages/vocab/ODRL22.jsonld

And in section 1.2, we say to see the Vocab spec for normative serialisations.
