### ISSUE TITLE
Policy Conflict - Deprecate?

### ISSUE THREAD

**Issue by riannella** [w3c/poe#138]
Should we deprecate the Policy conflict strategy section:
  https://w3c.github.io/poe/model/#conflict

It only covers a small part of all the potential conflicts between policies.

**Comment by simonstey** [comment]
> It only covers a small part of all the potential conflicts between policies.

what other potential conflicts do you think of?

**Comment by riannella** [comment]
For example, one rule stated that Assignee Fred had been granted an "exclusive" distribution Permission, and the other rule said the same for Assignee Mary.

So, conflicts at the action "semantics" level

You could also have constraint conflicts.
One rule says "print this less than 5 times" and the other "print more that 10 times"

**Comment by riannella** [comment]
Little support for this, so closing the issue
