### ISSUE TITLE
Processing of dc:isReplacedBy

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/poe#141]
In the Information Model, the section on [Policy Provenance](https://w3c.github.io/poe/model/#provenace) says

> If a Policy contains the dc:isReplacedBy property, then the identified Policy *must* be retrieved and processed.

Since this is a normative document, I think it should be explicit, that the replaced policy *must* be ignored (even if it's implicit). Suggested text:

> If a Policy contains the dc:isReplacedBy property, then a processor *must* consider the first Policy invalid and *must* retrieve and process the identified Policy.

**Comment by riannella** [comment]
Updated with commit 5d4f9221b955281c572afe8f4b485a8d4b06c713

**Comment by larsgsvensson** [comment]
OK, thanks @rianella

**Comment by larsgsvensson** [comment]
OK, thanks @riannella

**Comment by riannella** [comment]
@larsgsvensson Can you please confirm you are ok with the resolution of this issue (and close it) or please add any further feedback/comments.

**Comment by larsgsvensson** [comment]
Fine with me.
