### ISSUE TITLE
Example used for "scope"

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/poe#142]
In the Information Model, the [definition of "scope"](https://w3c.github.io/poe/model/#asset-scope) says that 

> **scope** attribute URI values **should** be defined in the ODRL vocabulary and ODRL Profiles.

The example (Example 17) uses a value for **scope** that is not in the ODRL vocabulary (but might be in an ODRL profile). It would be helpful for the reader if there was some explaining text making it explicit that it is assumed that http://example.com/imt/jpeg is defined in a profile (e. g. http://example.com/profiles/1 and add that profile to the example.

Further, the example use case states that

> http://example.com/imt/jpeg ... provides additional context on what characteristics the Asset **must** hold.

Again, it would be helpful to the reader (and give a hint at Best Practices) if you say that http://example.com/imt/jpeg **should** dereference to a scope description.

Proposed Text

> Example Use Case: The Policy defines a target Asset http://example.com/media-catalogue that has a scope of http://example.com/imt/jpeg. That scope specifies further context on what characteristics the Asses **must** hold. The scope is defined in the profile http://example.com/profiles/1. It is considered good practice that the scope and profile URIs are not mere identifiers but dereference to human- and machine-readable documentation. For further information on profiles, see (link to profiles goes here).

I'm not quite sure on where to add the "profile" element so I'll leave that to you.

**Comment by riannella** [comment]
Updated in commit 87cfc9856bbe3cb200f07cb7745e74e0556a6717

**Comment by riannella** [comment]
@larsgsvensson Can you please confirm you are ok with the resolution of this issue (and close it) or please add any further feedback/comments.

**Comment by larsgsvensson** [comment]
Fine with me.
