### ISSUE TITLE
Use of "agent" in the definition of "Party"

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/poe#143]
The ODRL Information Model says that a

> Party can be any form of identifiable entity who undertakes a role in the Policy, such as a person, group of people, organisation, or agent. An agent is a person or thing that takes an active Role or produces a specified effect. 

I find the use of agent vs Party confusing. In most contexts (e. g. FOAF) entities that perform things are named "agents". I guess that "Party" is used for historical reasons but then it would be better to say that odrl:Party is roughly equivalent to [foaf:Agent](http://xmlns.com/foaf/0.1/Agent) (defined as "eg. person, group, software or physical artifact").

**Comment by riannella** [comment]
In the ODRL Ontology we have for Party
owl:unionOf ( schema:Person schema:Organization foaf:Person foaf:Organization vcard:Individual vcard:Organization )

We found the semantics of foaf:agent to be too broad.

**Comment by larsgsvensson** [comment]
Does that mean that software agents are explicitly not instances of `odrl:Party`?

My point is that the IM talks about things that take active roles or produce specified effects. What kind of things could that be if software is excluded?

**Comment by vroddon** [comment]
Shall we have a short discussion in the next call?

**Comment by simonstey** [comment]
> In the **ODRL Ontology** we have for Party
owl:unionOf ( schema:Person schema:Organization foaf:Person foaf:Organization vcard:Individual vcard:Organization )

How is this enforced for https://w3c.github.io/poe/vocab/#xml ?

> We found the semantics of foaf:agent to be too broad.

why? too broad for what?

**Comment by riannella** [comment]
There was some discussion back here: https://lists.w3.org/Archives/Public/public-odrl/2014Sep/0011.html

I think the "physical artefact" part of foaf:Agent was too broad (a statue in a park ;-).

But I am not too worried if that is a real assignee !

**Comment by riannella** [comment]
Proposal: add foaf:Agent and vCard:Agent to odrl:Party union

**Comment by riannella** [comment]
Completed.

commit 9af11bd5a25fc7bd83bc3ff7622beb7406f060e2

**Comment by larsgsvensson** [comment]
Fine with me.

Thanks,

Lars
