### ISSUE TITLE
Cardinality of Permission in Policy

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/poe#144]
The Information Model [states that](https://w3c.github.io/poe/model/#permission)

> An ODRL policy expression MAY contain at least one Permission.

Exactly what is the cardinalty here? A **may** means that it's optional, so the above definition would allow me to construct a Policy with no Permission and only Prohibitions and Duties (which wouldn't make much sense since the Assignee cannot really do anything). So I assume that you mean that the Policy **must** contain at least one Permission.

**Comment by riannella** [comment]
We now have removed such statements from the IM.
See this commit e055b79b52922eb52942a7622cebe25df3c091f1

We leave such rules to the definition of Policy Types now (or Profiles).

**Comment by riannella** [comment]
@larsgsvensson Can you please confirm you are ok with the resolution of this issue (and close it) or please add any further feedback/comments.

**Comment by larsgsvensson** [comment]
I read through the section on Rules and its subclasses now it's very much clearer. Thank you!
