### ISSUE TITLE
Action names to be used

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/poe#145]
The Information Model says about [Action](https://w3c.github.io/poe/model/#action)s:

> The ODRL vocabulary [vocab-odrl] defines a standard set of common Action names that MAY be used.

Does that mean that anyone can define Actions in a profile? If so I propose to add the following text:

> Communities can define further Actions that **should** be documented in a Profile (vgl. {reference to profile creation goes here}).

**Comment by riannella** [comment]
This was updated in this commit e055b79b52922eb52942a7622cebe25df3c091f1

**Comment by riannella** [comment]
@larsgsvensson Can you please confirm you are ok with the resolution of this issue (and close it) or please add any further feedback/comments.

**Comment by larsgsvensson** [comment]
Assuming that the change was in line 794
```
<p>The ODRL vocabulary [[!vocab-odrl]] defines a standard set of common Actions that MAY be used and ODRL Profiles MAY also define Actions.</p>
```
that commit resolves my issue.

**Comment by riannella** [comment]
Yes
