### ISSUE TITLE
Usage permissions for Ticket

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/poe#146]
The Definition of [Ticket](https://w3c.github.io/poe/vocab/#term-Ticket) says

> Policy expression that stipulates the terms of usage and is redeemable by any Party who currently holds the Ticket in their possession.

And the note adds

> A Offer Policy Type MUST contain a target Asset and at least one of a Permission or Prohibition rule. The Offer MAY contain the Party with Assigner role and a Party with Assignee role. A Ticket (or Voucher) may be anonymous or personalised, where the holder of that Ticket may remain unknown or has to be identified. The holder, or if known, the Assignee, is being granted the terms of the Ticket from the Assigner (in known).

I think the first two sentences (referring to Offer) should be removed. Further I find the reference to the Assignee confusing. The definition says that a Ticket is redeemable by anyone who holds the ticket. Does that hold even if the Ticket is assigned to someone else (i. e. the Holder is different from the Assignee)?

**Comment by riannella** [comment]
(That seems to be a copy/paste error ;-)
I have updated the definition of Ticket in this commit c1126c6146d95d8120005c48d8045967b27aa5ab

**Comment by larsgsvensson** [comment]
OK, thanks @riannella

**Comment by riannella** [comment]
@larsgsvensson Can you please confirm you are ok with the resolution of this issue (and close it) or please add any further feedback/comments.

**Comment by larsgsvensson** [comment]
Yes, fine with me. I'm closing.
