### ISSUE TITLE
Text for note on Target

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/poe#147]
The note for [Target](https://w3c.github.io/poe/vocab/#term-target) is very terse:

> Or not performed by Prohibitions.

I think the following text would improve readability

> In the case of Prohibitions, the Target specifies the Asset upon which the Action **must not** be performed.

**Comment by riannella** [comment]
This has been superseded in this commit e055b79b52922eb52942a7622cebe25df3c091f1

**Comment by simonstey** [comment]
> This has been superseded in this commit e055b79

no, this commit doesn't update the vocab

**Comment by riannella** [comment]
Update vocab now 51dddf982cda8b6c158e9c29cbdd8b9508c12da3

**Comment by riannella** [comment]
@larsgsvensson Can you please confirm you are ok with the resolution of this issue (and close it) or please add any further feedback/comments.

**Comment by larsgsvensson** [comment]
Fine with me
