### ISSUE TITLE
Actions for Prohibitions and Duties

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/poe#148]
The note on [has Action](https://w3c.github.io/poe/vocab/#term-action) says

> A permission must include exactly one action.

What are the cardinality constraints on Prohibitions and Duties?

**Comment by riannella** [comment]
Updated in this commit e055b79b52922eb52942a7622cebe25df3c091f1

**Comment by simonstey** [comment]
> Updated in this commit e055b79

it's in the vocab

**Comment by riannella** [comment]
Whoops..missed that.

Commit 07c34e7c2a1b3a73134e3cf64984b165553e4bc4

**Comment by riannella** [comment]
@larsgsvensson Can you please confirm you are ok with the resolution of this issue (and close it) or please add any further feedback/comments.

**Comment by larsgsvensson** [comment]
Fine with me.
