### ISSUE TITLE
Should vs must in some odrl:LeftOperand

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/poe#150]
The usage notes on some LeftOperands are very inconsistent regarding the use of **must** vs **should**

In [count](https://w3c.github.io/poe/vocab/#term-count) the note says

> Should be a positive integer

When would it be OK to use a negative integer?

In [dateTime](https://w3c.github.io/poe/vocab/#term-dateTime) the note says

> Right operand should be a xsd:date or a xsd:dateTime, Value must conform to [iso8601] as represented in [xmlschema11-2]. The use of Timezone information is strongly recommended.

In what cases would it be OK not to use an xsd:date or an xsd:dateTime? And can I use any datatype as long as the representation conforms to xsd?

In [delayPeriod](https://w3c.github.io/poe/vocab/#term-delayPeriod) the note says

> Value must conform to [iso8601] as represented in [xmlschema11-2] as a xsd:duration. This maybe used with the odrl:andSequence operator. 

Why is the use of xsd mandatory here but only recommended in dateTime? (And the text should read "This may be used ..."; a common typo throughout the document)

In [meteredTime](https://w3c.github.io/poe/vocab/#term-meteredTime) the note starts with 

> The value must conform to ...

whereas in [payAmount](https://w3c.github.io/poe/vocab/#term-payAmount) the note starts with

> The datatype of the right operand...

It would increase readability if all instances where values **must** conform to certain datatypes were phrased the same way.

**Comment by nitmws** [comment]
Quick note: as editor of leftOperands I have copied and pasted notes from the ODRL specifications of corresponding/equivalent leftOperands (constraints called there). 

Questions 1: were the must, should, could etc applied to the note in the RFC 2119 (https://www.ietf.org/rfc/rfc2119.txt) context?

Question 2: what level of agreement is required to modify the notes: by the Editors of the draft document of by the WG?

**Comment by riannella** [comment]
A1: Should be the same ;-)
A2: Editors

**Comment by riannella** [comment]
A1: MUST be the same ;-))))

**Comment by riannella** [comment]
1) count - removed the note.
2) dateTime - xsd is now a MUST (same for all date/time constraints)
3) fixed wording

commit: a82f28226581d96c497254726411f9c4ab30b322

**Comment by larsgsvensson** [comment]
Yes, that commit resolves my issues.

Thanks,

Lars

**Comment by riannella** [comment]
Thanks
