### ISSUE TITLE
XML encoding: qcodes and qnames

### ISSUE THREAD

**Issue by riannella** [w3c/poe#151]
Do we still need to support Qcodes and Qnames in the XML Encoding section:
  https://w3c.github.io/poe/vocab/#xml

And/or do we need to make these universal across all serialisations?

Or does the new support for IRIs work ok as is?

**Comment by stuartmyles** [comment]
In my view, it would be fine for us to drop support for QNames and QCodes from ODRL XML (and not spread them to other encodings). Within IPTC our experience has been that full IRIs (or URIs) are easier to deal with in the general case - the space savings of using QCodes entail additional processing to map from QCodes to full IRIs.

**Comment by riannella** [comment]
Thanks. Will remove them from the XML encoding spec/schema

**Comment by riannella** [comment]
Change made.

Commit 04388d9d5012f0619732cbe076552e9907e1d2b8
