### ISSUE TITLE
JSON-LD Encoding

### ISSUE THREAD

**Issue by riannella** [w3c/poe#153]
Is the current text in the JSON-LD Encoding section:
https://w3c.github.io/poe/vocab/#json
enough for implementors to normatively follow?

**Comment by iherman** [comment]
I believe that is enough, in terms of definition. However, I guess for the readability a text explaining that we do not define a generic JSON encoding but we rely on JSON-LD's capability to encode the RDF vocabulary, etc, etc, would be welcome. The JSON encoding is, in this sense, different from the XML encoding that does not seem to rely on RDF/XML.

**Comment by nitmws** [comment]
As I like precise statements I suggest this change in the JSON-LD Encoding section - inserted words in bold:
Implementations producing ODRL expressions **in JSON** should include ...

**Comment by riannella** [comment]
@nitmws would that be "...in JSON-LD..." ?

**Comment by nitmws** [comment]
@riannella the first step is: the production must produce JSON syntax (and not XML or something else), only then adding @context makes sense. A more expanded statement could be: "Implementations producing ODRL expressions **in JSON for the use with JSON-LD** should include a @context property value ..."

**Comment by simonstey** [comment]
>  the first step is: the production must produce JSON syntax (and not XML or something else), only then adding @context makes sense. A more expanded statement could be: "Implementations producing ODRL expressions in JSON for the use with JSON-LD should include a @context property value

we moved from JSON to JSON-LD as discussed in #46

**Comment by riannella** [comment]
As said in #46:
"The JSON representation should be the JSON-LD simply with the @context removed."

Is that ok @nitmws @stuartmyles  ?

**Comment by simonstey** [comment]
> "The JSON representation should be the JSON-LD simply with the @context removed."

why?  

as @gkellog said:

> ... JSON-LD is JSON ...

**Comment by riannella** [comment]
BTW, I also was quoting @gkellogg
