### ISSUE TITLE
Systematic labeling of normative vs. informative

### ISSUE THREAD

**Issue by iherman** [w3c/poe#155]
At the moment there is no separation between normative and informative sections. Remember that, in a W3C Rec, any section that is not explicitly labeled is considered to be normative. I think we will have to make a thorough overview on this. E.g.

1. We have to make explicit that examples are _not_ normative (e.g. in the conformance section)
2. I am not sure whether the XML serialization is normative or not. If it is, we will have to have test cases and implementations. (This is also related to issue #151)
3. I am not sure whether all terms defined in the vocab documents are normative or not. I seem to remember that we had some discussions on this in the past, and many (most?) terms in the vocab document are actually informative.

There are probably more sections like that. Also, the choice whether a reference is normative or not depends on this. E.g., if we decide that the JSON-LD serialization is normative (I am not sure) then the corresponding json-ld reference must be normative (it is informative right now).

**Comment by riannella** [comment]
1) Do you mean the examples in the Encoding section of the Vocab document?
We state this: https://w3c.github.io/poe/vocab/#conformance

2) I assume we need test cass for all serialisations  @philarcher1 

3) Yes, we have discussed this a lot. The proposal is that we ask implementors (again) which terms they use and document that (like we did the first time [1]). From that we can split the Vocab into normative/non-normative.

Another option is to split the Vocab into **Core** (normative) and **Common** (non-normative) and only have the IM terms in the Core.
So the spec says the IM is the core and the rest is all recommended terms.

[1] https://www.w3.org/2016/poe/wiki/File:ODRLImplementationSurvey-2016-Dec-07.pdf

**Comment by iherman** [comment]
>1) Do you mean the examples in the Encoding section of the Vocab document?
>We state this: https://w3c.github.io/poe/vocab/#conformance
>

Ah, yes, indeed, I missed that. This takes care of the examples.

>2) I assume we need test cases for all serialisations  @philarcher1
>
>3) Yes, we have discussed this a lot. The proposal is that we ask implementors (again) which terms they use and document that (like we did the first time [1]). From that we can split the Vocab into normative/non-normative.
>
>Another option is to split the Vocab into **Core** (normative) and **Common** (non-normative) and only have the IM terms in the Core.
>So the spec says the IM is the core and the rest is all recommended terms.

I would day *this decision is urgent*. The CR (which, afaik, is planned after the F2F meeting) **must** contain something about this. Either we decide on what is and what is not normative or, at the minimum, we label all features that _may_ become informative as "at risk" in the document. If we do not do that, and we "downgrade" some features as informative later, that means we will be required to re-publish a CR at some point which may be a source of delays.

To take a specific example (I may be a bit pushy here) I could imagine _not_ to consider the RDF serializations in the documents as normative. The ODRL recommendation is the model and the vocabulary; the vocabulary is defined in RDF. *That* is is the new thing we bring to the table. The fact that the RDF content can be serialized in JSON-LD, Turtle, or anything else is not a feature this recommendation adds as something new, it is just the usage of existing Recommendations.

(The testing of the vocabulary will use some form of a serialization, but that is different. We should not test the serialization _itself_.

The XML serialization is something different: that is not an RDF one. The question is whether it would be widely used (I am not sure), ie, whether putting it out as a Recommendation adds a value over "just" publishing it either as a separate Note or as an informative appendix in the spec.

**Comment by riannella** [comment]
Proposal for CR:

1. ODRL Info  Model

Mark these sections as non-normative:
3.1.1 Policy Composition
3.1.2 Policy Provenance
3.1.3 Policy Conflict Strategy
3.1.4 Undefined Actions
3.1.5 Policy Inheritance
(and move them to the end of  section "3. ODRL Information Model"

2. ODRL Vocab & Expression

Split  the current Vocabulary section into two:
"4. Core Vocabulary" (normative)
"5. CommonVocabulary" (non-normative)

Only terms in the normative IM are in the Core Vocabulary, everything else is in Common.

The section on "Vocabulary Encodings" (including rdf/turtle, xml, json-ld) are marked as non-normative

**Comment by riannella** [comment]
See #182

**Comment by riannella** [comment]
This will be tracked via #182
