### ISSUE TITLE
General feedback on POE Use Cases

### ISSUE THREAD

**Issue by riannella** [w3c/poe#156]
@aisaac 

1. General feedback on POE Use Cases (https://www.w3.org/TR/2017/WD-poe-ucr-20170223/)

Are the requirements identified in this document (https://www.w3.org/TR/2017/WD-poe-ucr-20170223/#Requirements) referred in other POE documents? It would be great to see which requirements have been implemented or not, and by which specific item of the Information Model or Vocabulary. Unless all have been met? It's not very clear. Some requirements have been stricken out, indicating de-prioritization. But it could still be that some of the ones you judge important are only partially met.

Also not all requirements for use cases have been captured. To start with, the RightsStatements.org case could be used to motivate more requirements. In addition to the current focus, rightsstatements.org can articulate other use cases paired with existing requirements, namely:
* POE.R.V.15 - for our statements NoC-CR and NoC-OKLR
* Perhaps new entries under POE.R.E (Encoding) following our use of `relatedURL` parameter for statements that need a link to a human-readable legal piece
* Documenting cases of rights status expiry, which is perhaps relevant to POE.R.DM.06
Would you accept new/revised use cases?

As an other example, I'm not sure POE says anything about propagation of deletions (POE.UC.23). The use case POE.UC.23 had just one general requirement about having complex constraints…

**Comment by simonstey** [comment]
quick comment:

> It would be great to see which requirements have been implemented or not, and by which specific item of the Information Model or Vocabulary.

We did something similar for SHACL (cf. http://w3c.github.io/data-shapes/data-shapes-ucr/#requirements)

**Comment by simonstey** [comment]
Proposal: Re-open submission of new/revised use cases

**Comment by riannella** [comment]
WG agreed (8 May) to allow update of these UC/reqs (only)

**Comment by aisaac** [comment]
Regarding revision of mentioned cases and requirements, this sounds good. Have you got a precise timing in place?

Also, about the other comment in this issue: will there be something to show which requirements are met? It's unclear from the subsequent thread. Maybe it should be treated as a new issue?

**Comment by simonstey** [comment]
- [x] added additional requirements to UC-27 (see https://github.com/w3c/poe/commit/f9b43803441646fcdecc0f5aecd404f82bb64680)
- [ ] _"It would be great to see which requirements have been implemented or not, and by which specific item of the Information Model or Vocabulary. "_
