### ISSUE TITLE
Europeana/DPLA use case

### ISSUE THREAD

**Issue by riannella** [w3c/poe#157]
@aisaac 

2. Europeana/DPLA use case (https://www.w3.org/TR/2017/WD-poe-ucr-20170223/#POE.UC.27)

First, thanks for including us, it is really good to have connections between our initiatives. And we'll try to remain compatible with POE specifications. Especially in our modeling work (http://rightsstatements.org/files/170106requirements_for_the_technical_infrastructure_for_standardized_international_rights_statements_v1.2.pdf, p17) we have tried to reuse odrl:inheritFrom.

Our first comment here is about representation issues for our case. In the material we had written on the the ODRL community Wiki
https://www.w3.org/community/odrl/wiki/Europeana/DPLA_In_Copyright_-_Educational_Use_Only
we had proposed to represent our right statement the following way:

```turtle
  <http://rightsstatements.org/rs/ic-edu> a dcterms:RightsStatement , odrl:Policy ;
    skos:prefLabel "In Copyright - Educational Use Only"@en ;
    odrl:permission [
               odrl:action odrl:use ;
               odrl:constraint [
                     odrl:operator odrl:eq ;
                     odrl:purpose <http://rightsstatements.org/purpose/education> # This would be preferably from an existing namespace, not ours.
                   ]
        ] .
```

Note especially the use of odrl:purpose as a property, following the spec in the previous ODRL ontology: https://www.w3.org/ns/odrl/2/ODRL21#term-purpose
But this has now changed, it seems, with odrl:purpose being an instance, and the whole stuff about constraint operands being quite different (http://w3c.github.io/poe/model/#constraint)
As I understand the new POE vocabulary the example should now be

```turtle
  <http://rightstatements.org/rs/ic-edu> a dcterms:RightsStatement , odrl:Policy ;
    skos:prefLabel "In Copyright - Educational Use Only"@en ;
    odrl:permission [
       odrl:action odrl:use ;
       odrl:constraint [
             odrl:leftOperand odrl:purpose ;
             odrl:operator odrl:eq ;
             odrl:purpose <http://rightstatements.org/purpose/education>
        ]
    ].
```

Can you confirm this? And would you accept new/revised use cases?

Note that this is not implemented on our side yet. The current representations of statements (https://github.com/rightsstatements/data-model/blob/master/rights-statements.ttl) are simpler. But it will become important in the future.

Also, I guess in the requirements related to our case, a ‘vocabulary of purpose’ could have been noted (like the ‘education’ one used above). Or at least a mechanism to extend existing purposes/actions (there is a comment on the other feedback mail sent at the same time as this one). We've not created the purpose http://rightstatements.org/purpose/education that is used in the example, yet. And we would prefer not to have to maintain such general concepts ourselves...

Finally, a couple of editorial comments: it would be better to name is a RightsStatements.org use case; mentioning Europeana and DPLA in the body is fine :-) Also you should remove Riccardo Albertoni - Riccardo worked with me only on data quality - and add Mark Matienzo instead.

edit (simon): fixed formatting

**Comment by riannella** [comment]
WG agreed (8 May) to allow update of these UC/reqs (only)

**Comment by aisaac** [comment]
Sounds good. Have you got a precise timing in mind?

**Comment by simonstey** [comment]
- [x] s/Riccardo Albertoni/Mark Matienzo/
- [x] added code example
- [x] renamed UC
- [x] + _"Hence, a mechanism allowing for extending existing or adding new purposes/actions should be provided."_

see -> https://github.com/w3c/poe/commit/8bc9cee0eab856e40b2dab02881860cb4084faae
