### ISSUE TITLE
Possible extensions of the (SKOS) concept schemes defined in POE

### ISSUE THREAD

**Issue by riannella** [w3c/poe#160]
@aisaac 

1.  I'd like to make a suggestion regarding possible extensions of the (SKOS) concept schemes defined in POE, such as the Actions one.
The POE model foresees that there can be new actions, which from the perspective of POE are not supported, and thus captured as ‘undefined’. This is apparently being debated, as reflected in https://github.com/w3c/poe/issues/105. But can’t a simpler, more flexible approach be taken, which would avoid the awkwardness of this ‘undefined’? I’m thinking of the Web Annotation mechanism to represent annotation motivations: https://www.w3.org/TR/annotation-vocab/#extending-motivations .
The rule there is that WA introduces a set of basic Motivations (like POE introduced a set of basic Actions) and WA recommends to extend this set by defining new Motivations as specializations of existing ones, using skos:broader.
The actions already present in POE seem to cover a wide ground already, it seems that such approach of “extension-by-specialization” would be possible.

**Comment by riannella** [comment]
See #139 (as we may remove this feature).

I think these types of suggestions should be in the Profile section.

**Comment by aisaac** [comment]
Looking at #139: I think it makes sense removing the 'undefined action' as it was at
https://www.w3.org/TR/2017/WD-odrl-model-20170223/#undefined
And it could be that treating this as part of Profiles is the right thing to do.

However I would still consider POE has to offer something. Is it possible that #139 is closed noting that there should be something? From the perspective of #160 this should be about the extension mechanism.

**Comment by riannella** [comment]
F2F: Update model to support hierarchies (relationship) expressible between Actions

RESOLUTION: That we introduce the terms odrl:narrowerThan and odrl:alsoRequires to the Information Model. These are applicable to Assets, Parties and Actions

requires = other actions that it requires (eg share must include distribute)

both are transitive

REMOVE all SKOS !!!!

http://www.w3.org/2017/05/19-poe-minutes.html

@simonstey @sabrina to propose definitions and examples

**Comment by aisaac** [comment]
This sounds rather weird a decision, sorry to say it. Why re-defining a whole hierarchy apparatus? If you want to represent 'hierarchies' it means that you have a rather 'conceptual' approach of actions anyway. 

But maybe I need to see your requirements. It's not clear from the minutes, why these would be different from what SKOS means to tackle. 

My problem is not only the matter of re-using SKOS for the sake of re-using SKOS. Hierarchical extension is a good thing to allow for profiles (again, as Web Annotation does for their instances of oa:Motivation). If profile designers are expected to use a mechanism with very specific semantics, and one that would disallow the re-use of any existing vocabulary of actions they might have elsewhere, then they might be discouraged. Actually as the owner of a vocabulary that is now said to create their own Action (#154), I am now discouraged. So this is an obstacle to building extensions that could be better interoperable. 

Btw odrl:alsoRequires may have some good motivation, but the name surprises me. Why 'also'? Is there some kind of 'primaryRequires' relationship anywhere?

**Comment by riannella** [comment]
Resolutions 29/may17:

1. rename narrowerThan to partOf for Asset and Party and remove AssetIndividual and PartyIndividual
2. rename alsoRequires to implies for Action

Waiting on more info for alsoRequires for Party/Asset

**Comment by riannella** [comment]
Added narrowerThan, implies, partOf properties to model and updated vocab.
updated the vocab to use narrowerThan

commit: ba08816cd3f0eeb38e083e802d070c75c40316a6

**Comment by riannella** [comment]
See discussion starting in this thread:
  https://lists.w3.org/Archives/Public/public-poe-wg/2017Jun/0002.html

**Comment by aisaac** [comment]
After discussion on #164 . I need to have a more general look at all SKOS-related matters in POE, taking into this ticket but also the questions raised in #164  (if still relevant).
@riannella what would be the deadline for it? This week I can't work much on it...

**Comment by riannella** [comment]
@aisaac middle of next week would be good.

**Comment by riannella** [comment]
Implemented the changes as per:
  https://lists.w3.org/Archives/Public/public-poe-wg/2017Jun/0013.html

commit: 2ba294e90de7f26a1425e0852ec751435e41ccce

**Comment by riannella** [comment]
WG agreed to withdraw the "alsoRequires for Asset/Party" proposal

**Comment by aisaac** [comment]
@riannella does the last comment reflect the last position of the group wrt SKOS-related features? If yes then I can embark on reviewing these SKOS-related features. If not then I'd rather wait a bit, because I don't have much time...

**Comment by riannella** [comment]
Yes, please also look at some comments in #188
