### ISSUE TITLE
Permission cardinality

### ISSUE THREAD

**Issue by riannella** [w3c/poe#17]
Section 2 says that "an ODRL Policy must contain at least one Permission" but the UML model shows 0..*

**Comment by simonstey** [comment]
why must an ODRL policy contain at least one permission?

**Comment by riannella** [comment]
Model (narrative) needs to be updated to show at least one Perm or Prohib needs to be in a Policy?

**Comment by nitmws** [comment]
My recollection of dicussing the overall use case of ODRL is: its key feature is to grant any kind of action which can be applied to an asset and this is expressed by a Permission. A more generic permission can be constrained by a specific prohibition. Therefore at least 1 permission should be in a policy and zero to many prohibitions.

**Comment by riannella** [comment]
I do recall such discussions. But thinking about some policy types (eg Set) where we allow _anything_ then perhaps the model entities should be optional, and we define constraints more tightly at the Policy Type level (and of course, they can be applied even more tightly at the Profile level).

**Comment by vroddon** [comment]
I believe that no use case imposes a requirement in any direction here. Being free to choose, I would also leave the policy level unconstrained.

**Comment by riannella** [comment]
Will update the text to remove this constraint (and the UML model has been updated) and add text to say that the Policy Type may express additional constraints on the model.

**Comment by riannella** [comment]
Updated the XML Encoding section to remove the mandatory Permission (the XML Schema is correct)

**Comment by riannella** [comment]
Done
