### ISSUE TITLE
ODRL Profiles & RFC2119

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#172]
the entire [section on ODRL Profiles](http://w3c.github.io/poe/model/#profile) is flagged as being non-normative, but uses RFC2119 keywords, e.g.:

> This property is OPTIONAL, but if the property appears, then any consuming system MUST understand the identified ODRL Profile and all the constraints in the ODRL Profile MUST apply to the Policy expression. If a consuming system does not understand the ODRL Profile, then it MAY continue processing the Policy expression, but it SHOULD NOT assume it has interpreted the Policy expression correctly. 

what's the semantics of a non-normative RFC2119 MUST?
 
(cf. http://ln.hixie.ch/?start=1140242962&count=1);

> It is very easy to confuse statements of fact with normative conformance criteria, because they are often phrased similarly, are styled the same, and usually appear right along with conformance criteria. In specifications that use RFC2119 terminology, the key to distinguishing statements of fact from conformance criteria is to check to see if the spec uses any of the RFC2119 key words. If it doesn't, it isn't a normative conformance statement, and is either a definition or a statement of fact. It's a definition if it defines a specific term (either explicitly, as in the quote above, or implicitly, using the construct "a term is definition"). Otherwise, it's just an statement of fact.

**Comment by simonstey** [comment]
this should also be updated/removed: 

> It is also recommended to share the ODRL Profile with the **W3C ODRL Community Group** for feedback and comments. In addition, the **W3C ODRL Community Group** may host the ODRL Profile documents on their website.

**Comment by philarcher** [comment]
I agree that RFC2119 keywords are inappropriate in a non-normative section. But the POE WG should take note that the <a href="https://www.w3.org/2017/dxwg/">Dataset Exchange WG</a> (DXWG) kicks off next week and is <a href="https://www.w3.org/2017/dxwg/charter#deliverables">chartered</a> to, among other things, define what is meant by an application profile and explain one or more methods for publishing and sharing them. Therefore, one option for POE would be to reduce the section on ODRL profiles to generic text, pointing readers to the new WG for future guidance. This does not preclude giving the RightsML example of course.

**Comment by riannella** [comment]
RE: what's the semantics of a non-normative RFC2119 MUST?

It means "IF you implement X, then you MUST do it this way"

Other recent specs use RFC2119 terms in non-normative sections:
https://www.w3.org/TR/2017/PR-activitystreams-vocabulary-20170413/#places
https://www.w3.org/TR/annotation-model/#additional-media-types-selector-combination
https://www.w3.org/TR/activitystreams-core/#activitystreams-1.0

@simonstey What should be updated in that paragraph?

**Comment by simonstey** [comment]
> It means "IF you implement X, then you MUST do it this way"

Which is not what [4.2 Requirements](http://w3c.github.io/poe/model/#profile-requirements) says though:

> The profile property in a Policy is used to indicate the identifier (IRI) of the ODRL Profile for which the Policy expression conforms to. **This property is OPTIONAL, but if the property appears, then _any_ consuming system _MUST_ understand the identified ODRL Profile and _all_ the constraints in the ODRL Profile _MUST_ apply to the Policy expression.**

_"any consuming system"_ != _"any consuming system that supports/implements given profile"_
Actually, it's even contradicting itself as it continues on with stating that:

>  **If a consuming system _does not understand_ the ODRL Profile, then _it MAY continue processing_ the Policy expression,** but it SHOULD NOT assume it has interpreted the Policy expression correctly. 

Since it's required that **any** consuming system **MUST** understand the identified Profile, any system that doesn't, doesn't conform to the spec. 

see https://www.ietf.org/rfc/rfc2119.txt:

>1.) **MUST**   This word, or the terms "REQUIRED" or "SHALL", mean that the
   definition is **an absolute requirement of the specification**.
>
>3.) **SHOULD**   This word, or the adjective "RECOMMENDED", mean that **there
   may exist valid reasons in particular circumstances to ignore a
   particular item,** but the full implications must be understood and
   carefully weighed before choosing a different course.
>
>5.) **MAY**   This word, or the adjective "OPTIONAL", mean that **an item is
   truly optional.**  [..] An implementation which does not include a particular option **MUST be
   prepared to interoperate** with another implementation which does
   include the option, **though perhaps with reduced functionality**. In the
   same vein an implementation which does include a particular option
   **MUST be prepared to interoperate** with another implementation which
   does not include the option **(except, of course, for the feature the
   option provides.)**

renato:
> Other recent specs use RFC2119 terms in non-normative sections:

Unfortunately, yes.. But they make it very clear to whom those requirements apply to and/or don't use MUST:

https://www.w3.org/TR/2017/PR-activitystreams-vocabulary-20170413/#places:

> While **publishers are not required to use these specific properties** and MAY make use of other mechanisms for describing locations, consuming **implementations that support the Place object MUST support the use of these properties.** 

- publishers are not required to use these specific properties
- only implementations that support the Place object MUST support the use
---------------------
https://www.w3.org/TR/annotation-model/#additional-media-types-selector-combination:

> The table below contains some other, possible combinations of media types and selector types, **which MAY be implemented but are not mandated by this specification**.

- MAY be implemented but not mandated by the spec
---------------------
https://www.w3.org/TR/activitystreams-core/#activitystreams-1.0:

> The terms displayName, verb, title and objectType should be treated as reserved terms that **SHOULD NOT be used** within Activity Streams 2.0 documents. When encountered in an Activity Streams 2.0 document, **they SHOULD be processed** in accordance to the guidelines listed in ..

- SHOULD NOT be used 
- if encountered they SHOULD be processed according to the guidelines 
---------------------
> @simonstey What should be updated in that paragraph?

1. don't require **any** implementation to be able to understand/process profiles 
2. s/MUST/SHOULD/
3. (move the whole section on ODRL Profiles into their own WG Note :) )

**Comment by riannella** [comment]
Perhaps we should remove the concept of Profiles completely?
And leave it up to implementors/communities (like other specs...)

I note that RighstML (an example cited) does not actually use the "profile" property @nitmws @stuartmyles

**Comment by simonstey** [comment]
+1

**Comment by iherman** [comment]
@riannella I presume we had this concept because there is a need for it; completely forgetting about it may be a step too far. Maybe the best approach is what @simonstey proposed, ie, move it into a separate note. Once it is a note it is also safer to make references to a nascent WG that @philarcher1 proposed.

**Comment by simonstey** [comment]
> Maybe the best approach is what @simonstey proposed, ie, move it into a separate note. Once it is a note it is also safer to make references to a nascent WG that @philarcher1 proposed.

in which case we have to address #173

**Comment by philarcher** [comment]
The concept of a profile for ODRL is exactly in line with what the DXWG is going to tackle so if POE is happy to leave it at that, it can be done with confidence. The KO meeting for DXWG is on Thursday during the POE F2F (I'll need to slip out of the room for that hour). The POE WG has time within it remaining charter to assess whether or not DXWG will deliver the required level of support and, if it doesn't, POE can create a separate Note.

**Comment by vroddon** [comment]
REL Profiles have been there for the last 15 years, but history alone should not be the only reason to maintain a feature.  

The advantage of having profiles is that the specification of each adopter can eventually have an official sanction. If profiles are now not mentioned, homogeneous practice will be lost. But I believe this is entirely up to the interest of current adopters. What do they think?

**Comment by riannella** [comment]
See #173

**Comment by riannella** [comment]
This issue will be tracked via #173
