### ISSUE TITLE
An Action is associated to the Asset with the action property in a Rule. 

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#175]
http://w3c.github.io/poe/model/#action:
> An Action is associated to the Asset with the `action` property in a Rule. 

what? how?

**Comment by riannella** [comment]
Agree...we keep referring to Actions for Assets, when they should be for Rules (and the Rule describes the action semantics)

**Comment by riannella** [comment]
Updated.
Commit f58a025183c9ac2db7965d836f01ed4164d3964f
