### ISSUE TITLE
invalid examples

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#176]
**Example 9:**
```json
{
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Offer",
    "uid": "http://example.com/policy:1012",
    "permission": [{
            "target": "http://example.com/music:1012",
            "action": "play"
     }]
}
```
offer without assigner

--------------------

**Example 13:**
```json
{
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Privacy",
    "uid": "http://example.com/policy:7777",
    ...
}
```
unsupported policy type

--------------------

**Example 23:**
```json
{
    "@context": [
        "http://www.w3.org/ns/odrl.jsonld",
        { "dc": "http://purl.org/dc/terms/" }
    ],
    "@type": "Policy",
    "uid": "http://example.com/policy:8888",
    "dc:creator": "billie@example.com",
    "dc:issued": "2017-01-01:12:00",
    "dc:coverage": "https://www.iso.org/obp/ui/#iso:code:3166:AU-QLD",
    "dc:replaces": "http://example.com/policy:8887",
    "permission": [{   }]
}  
```
what's `"permission": [{   }]` supposed to mean?

--------------------

**Example 28:**
```json
{
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Agreement",
    "uid": "http://example.com/policy:4444",
    "inheritFrom": "http://example.com/policy:default",
    "permission": [{
        "target": "http://example.com/asset:5555",
        "action": [ "archive", "annotate", "display", "print" ],
        "assignee": "http://example.com/user:0001",
        "assigner": "http://example.com/org-01"
    }],
    "prohibition": [{
        "action": "aggregate"
    }]
}
```
missing assigner&assignee for prohibition

**Comment by riannella** [comment]
Ex 9 - fixed
Ex 13 - is valid - Privacy is defined in the ODRL Vocab (and mentioned as such in the example)
Ex 23 - added "..." which means the rest of the policy is here...
Ex 28 - fixed

Commit 33ad6920a5b0e4f1220f98f62def97e8bc0cfa5a

**Comment by simonstey** [comment]
> Ex 13 - is valid - Privacy is defined in the ODRL Vocab (and mentioned as such in the example)

why use a policy type that's not one of the officially supported policy types (e.g. as shown in [IM Diagram](https://w3c.github.io/poe/model/00Model.svg)

**Comment by riannella** [comment]
Updated the example to Agreement and simplified to be more about the duty.

Commit  7c700942d4e8fa96b3764244cb1406db4013055a

**Comment by simonstey** [comment]
closed #176

**Comment by vroddon** [comment]
Indeed, the IM reads  "An ODRL Policy of type Offer: must include at least one Party with assigner functional role." 
How should I express "this is a general offer for everybody"? (like an offer in Wal-Mart)

**Comment by riannella** [comment]
Offers are for anyone, but they must come from someone.

So, your example would have the assigner of "walmart.com"
