### ISSUE TITLE
Constraint: specs of classes and of instances of LeftOperand - editorial issues

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#179]
Going over the specifications regarding C/constraints  in Vocab Editor's Draft (of 11 May) I see these issues - and I'm aware of the already raised and discussed use of RFC 2119 terms. 

Constraint
* Has Constraint (4.15.2) - Definition: I suggest "Constraints applied to the Rule". (More than 1 constraint can be used - and they are more than just related.)
* Has Operator (4.15.4.) - Definition: I suggest "The logical operator function applied to the operands of a Constraint." 
* Right Operand (4.15.5) - Note: I suggest "Instances of the RightOperand class are used as the rightOperand of a Constraint." 
* Has Right Operand (4.15.6.): how to define the range of this property? Both literal values and an instance of RightsOperand can be used. (Ontology expertise required.)
* Has Right Operand Reference (4.15.7) - Definition change "A reference to a web resource providing the value for the right operand of a Constraint." ... and the Note: "**Is** an IRI which must be ..."
* Left Operand (4.15.8) - Note:  I suggest "Instances of the LeftOperand class are used as the leftOperand of a Constraint." 
* Unit (4.15.10) and Datatype (4.15.11): the Definitions say they are "used for the constraint value". Should be: " ... of the value of the rightOperand or rightOperandReference of a Constraint"

Constraint Left Operands (4.16.)

General comment regarding the use of RFC 2119 in the Note of a LeftOperand: as the terms defined by this RFC set clear and strict rules I suggest that such rules should be moved to the Definition of the LeftOperands. 
Sub-comment: In examples a "may" or "can" is not written in upper case and "must" and "should" should not be used.

General comment regarding the definition of a data type of a rightOperand/Reference: the Definition should say "The dataType used with the constraint MUST/SHOULD be ...." and a reference to a data type defined by the XML Schema 1.1 Specs is used if currently used in the Note.

 * Payment Amount (4.16.16) Note: the note about the datatype should be merged with an action from the comment regarding dataType above.
* Product Context (4.16.18) - Note should be "The Asset image may only be **presented** in the XYZ Magazine"
* Unit of Count (4.16.30): I think this LeftOperand instance needs examples for a deeper understanding - "Unit of Count" is not a very common term.

**Comment by riannella** [comment]
Changes made.

"Has Right Operand" range - we leave unspecified.

RFC 2119 terms are now lowercase (this what the W3C respec script does)

commit: e7ee1e3f947f9ebfb17bbf6c7aaf18ce8da3688f
