### ISSUE TITLE
Definitions of Atomic Constraint Operators

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#180]
The specification of Constraint in the Info Model defines Atomic Constraints "in which the left and right operands are logically compared" and Compound Constraints "in which the left and right operands are existing Atomic Constraints" ... and I'm sure they are also compared. (Should be added in the Info Model)

The Definition of the Constraint Operators in the Vocab Editor's Draft (of 11 May) use this wording as template: "Indicating that a given value xxx the right operand of the Constraint".
Based on the specification of Atomic Constraints the "given value" is a value generated from the definition of the left operand. Therefore I propose to replace this template above by "Compares/Checks if the value generated from the definition of the leftOperand is ... the value of the rightOperand/Reference of a Constraint" (fine tuning of the wording is required) for Constraint Operators which are used for Atomic Constraints.

**Comment by sereAbi** [comment]
I updated the IM so that we specify that Compound Constraints "in which the left and right operands are existing Atomic Constraints" are also compared.
