### ISSUE TITLE
Normative and non-normative parties, actions, leftOperands, operators ...

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#182]
In the current ODRL Vocabulary Editor's Draft (16 May) I see many instances of Party, Action, LeftOperand, Operator with a non-normative status.
What is the future use of these instances: will/should be included into a Recommendation document at all? 
If not: should they be moved to a draft-like document that they don't get lost for any future work on e.g. profiles?
If yes: can they be adopted by a profile and made normative there?

Personal footnote: IPTC and I have spent a lot of effort on actions and leftOperands therefore I want to know more about their future use.

**Comment by riannella** [comment]
This is related to issue #155 and will be discussed at the F2F ;-)

As I outlined, my preference is to split the Vocab spec into two sections.
All the normative stuff (required by the IM) in the Core Vocab, and everything else in the Common Vocab.

Another, more radical approach :-0 would be to just to only have the IM as the normative spec (have all the formal IM-only vocab terms in an appendix there) and the all the Common terms go into a NOTE, and the 3 encodings can also go into another NOTE.

**Comment by vroddon** [comment]
We should discuss this in the F2F

**Comment by riannella** [comment]
Add Action use and transfer to the IM (top-level)

Split the current single Vocabulary section into two:
"4. ODRL Core Vocabulary" (normative)
"5. ODRL Common Vocabulary" (non-normative)
(latter used as a possible source for Profiles)


PROPOSED: That we will publish the non normative vocab terms as the 'ODRL Common Vocabulary' but *not* as a Profile.
PROPOSED: That we will create at least one profile from the Common Vocabulary and demonstrate its use in running code as one example of an ODRL implementation
 PROPOSED: That the vocabulary terms that form the Core Model will be published as normative elements in that Recommendation

**Comment by riannella** [comment]
Encoding section of Vocab -> non-normaticve
Leave only XML in there.

Move rdf and json-ld context to Conformance section (and list all the namespaces)

**Comment by riannella** [comment]
Added Namespaces list. XML encoding now informative. Updated intro.

commit a5990e3cdb1ab518b08ce281c700345411bd5b2d

**Comment by riannella** [comment]
Split the Vocab into Core and Common

commit: 920c7fbddd91cd3d158432931853e6f36f696cd0

**Comment by vroddon** [comment]
I have not seen the file still split, but this is a sensitive operation I would not like to do alone. Or should I propose in a different branch a first attempt?

**Comment by riannella** [comment]
I don't think we mean an actual physical split of the file.
It is more of a separation of the Core and Common parts in the Vocab Specification document.
