### ISSUE TITLE
Remove Scope - replace with Constraint

### ISSUE THREAD

**Issue by riannella** [w3c/poe#183]
That we remove the concept of scope and allow constraints on parties and assets

Add AssetCollection and AssetIndividual as subtypes of Asset. Do the same for Parties

Also
To remove the mention of URI templates in section 3.2 (for simplification) and media frags because it's unnecessary

**Comment by vroddon** [comment]
Please note that if Constraints can be imposed on Assets and Parties, the domain of two properties will have to change.

**Comment by riannella** [comment]
I have removed Scopes and added constraints to Party and Asset (in the Information Model).
Also added the Party/Asset/Individual/Collection classes

See the commit a18744d510defabb246324dafca2673319de2f4

**Comment by riannella** [comment]
Vocab:
Added Asset/Party Individual/Collection subclasses, Added to constraint domain.
Deprecated all the Scope terms.

Commit: 2fd8e85adc458b288cb6c2d97f5301c12edcd60c

**Comment by riannella** [comment]
Updated the XML serialisation and schema for the above

commit: d1b76a9430e7b2879a215a8a59707d4210681544
