### ISSUE TITLE
Vocab feedback

### ISSUE THREAD

**Issue by riannella** [w3c/poe#185]
@aisaac

Renato told me it would be useful if I can continue the comments at https://lists.w3.org/Archives/Public/public-poe-comments/2017Apr/0008.html
I couldn't do it before today, sorry.
This time the nature of comments is a bit random. But they are mostly editorial.
NB: I’m still using the numbering as in the review: https://www.w3.org/TR/2017/WD-odrl-vocab-20170223/

- a bit everywhere in the document: it is not useful to declare that a resource is a subclass of owl:thing. Every class is a subclass of owl:Thing!
I’ve made this remark in the context of an earlier comment on the model about SKOS, but I prefer to re-iterate it separately so that it’s not forgotten.

- 4.13.1: an “in range of” could be useful to link odrl:Permission to odrl:permission, especially considering the awkwardness of their naming. It’s been done for other POE constructs in this document.
Same for Prohibition and maybe other POE constructs.

- 4.15.1 Action is a said to be a subclass of Concept, but the link doesn’t work. Is it supposed to be a link to skos:Concept?

- 4.16. There are many problems with the wording of definitions in this section.
First, it is dangerous to include in the definition of actions the fact that “The Assigner permits/prohibits the Assignee to”. In POE Actions are introduced in the context of permissions and prohibitions, indeed, but they could be used in other contexts, let alone for Duties (I've made comments about this elsewhere). E.g., odrl:transfer is questionable as a permission/prohibition action. I would have attached it to a Policy as a Duty. Anyway, I still find dangerous that the documentation categorizes rather generic actions according to their assumed destination in the model.
Definitions for individual actions read also strange when one compares with the definition of odrl:Action (“An operation that can be allowed [...]”). If one applies this definition with the definition of “use” (“The Assigner permits/prohibits the Assignee to use the Asset as agreed”) it doesn’t really work. What is the ‘operation’ that can be allowed as per the definition of odrl:Action? Is it the operation whereby "the assigner permits/prohibits something”? Not really.
Finally, many of these definitions are circular. E.g, “The Assigner permits/prohibits the Assignees to anonymize all or parts of the Asset.” doesn’t really define what the action of anonymising is.

- 4.16.17 “This action will modify an asset which is typically updated from time to time without creating a new asset like a database.”. "Like a database"? I don’t understand what this means.

- 4.16.20 I’m not sure what is meant for odlr:present. More precisely, I’m not sure I understand whether it is different from publishing. The fact that odrl:display and odrl:play are narrower concepts hints that Present is about some form of “performance”. But odrl:print is not really about performance nor presentation itseld. And how about odrl:stream? Why isn’t it here?

- 4.16.27. Transfer would be much less ambiguous if “Ownership” was added to it. Otherwise there can be confusion with electronic transfer of files. Also, the definition “The Assigner transfers/does not transfer the ownership” illustrates well the awkwardness of individual actions definitions as noted above. An “action” is defined here by the fact something happens or nothing happens!

- 4.16.28 I am tempted to suggest to add “Digital” here (i.e., naming the action as “Digital Transformation”, mentioning “a different digital format”, etc) because “transformation” can be ambiguous. Namely, it can cover things like (intellectual) adaptation of a work, which is a very precise notion in the rights domain, which POE is partly made for.

- 4.18 By now you won’t be surprised by the fact that I disapprove the pre-targetting of a set of actions for Duties :-) And why odrl:transfer (4.16.27, see above) is not here?

- 4.20.10 In English, using “Event Action” hints that what is going to be defined in this section will rather be an action. But it’s an event. Why not having used “Event”, simply?

- 4.20.13 The definition that says that the main language of the Asset is different from the original one after translation is surprising. In principle translation doesn’t change the language of an asset. It produces a new resource that is the translation of the original asset.

- 4.20 Wasn’t there any way to re-use the W3C Media Ontology and/or Web Annotation’s selectors? It is frustrating to see that POE has to reinvent so many wheels, and later on will have to pay the price of vocabulary maintenance for them.

- 5.1.1 I had comments about this section, but as it was said (https://github.com/w3c/poe/issues/184) that this section would be removed, I won’t spell them out.

**Comment by aisaac** [comment]
Just in case, my alias is @aisaac - unlike what's on the first line :-)

**Comment by riannella** [comment]
1) removed all subclass of owl:Thing

2) That is an identified bug - we will fix and should then appear #186 

3) Yes, it is supposed to be a link to skos:Concept, but is a bug in our auto-script. Need to fix @nevali #186 

4) Need to raise with WG - we have overloaded the definitions with roles and perms/prohibs

5) removed "like a database"

6) identified as an issue in #101 - solution is to remove it as a parent, and define it solely for "performance" 

7) Label updated

8) Probably best not to focus on the "digital" aspects. Updated definition:
"The Assigner permits/prohibits the Assignees to convert the Asset into a different format"

9) Noted in 4)

10) Fixed label

11) made it clear this is for the transformed Asset (same for fileFormat)

12) Not sure what you mean? Are you saying we use:
 https://www.w3.org/TR/annotation-model/#selectors
for constraints?

13) Now resolved as per #184 

commit: a4697a38fc0b0acae7ea65fd185f6ee9c710ad42

**Comment by aisaac** [comment]
1 -> OK
2 -> OK
3 -> OK
4 -> I'll wait then.
5 -> perfect!
6 -> this would be fine but I see #101 is still open to discussion so am going to wait for that.

7 -> almost perfect. I would complain that the URI has not been changed to be a bit more precise, but you've heard me about this issue before, I'll stop here on this one ;-) and be happy with the fact that the documentation is now much, much clearer.
Also I hope that the definition "The Assigner transfers/does not transfer the ownership" will be clarified as part of item 4.

8 -> ok, using 'convert' instead of 'make a copy' does clarify a lot.

9 -> actually this would be fixed by your answer for the first item of #164, so I think I'm good.

10 -> perfect!

11 -> I'm not sure talking about a 'transformed asset' is right in the context of translation. Anyway, it's much better now!

12 -> Yes this is what I meant. Note that the Web Annotation WG had discussions about aligning to Media Ontology fragments. They ended up with their own solution (but MA fragments are also valid for WA if I remember well), it may be useful for you to dig up their rationale. And then decide if you need to create your own solution (but then it would be the third available, probably that's too much!).

13 -> OK

Conclusion: out of the original comments/issues here, only 6 and 12 remain to be assessed.

**Comment by riannella** [comment]
6 has been done in commit: a4697a3

12 But we are not selecting "part of a resource" with ODRL Constraints. For example, date constraints on the usage of the Asset, or "purpose=education" ...

**Comment by riannella** [comment]
Updated all Actions and removed assigner/assignee and perm/prohibt from the definitions

Confirmed by WG thread: https://lists.w3.org/Archives/Public/public-poe-wg/2017May/0039.html

commit dfa9279bdfde28ae0dd1e01a3c565c4a561f8a79

**Comment by aisaac** [comment]
6. I'm afraid I won't have time to check everything in that (impressive!) commit right now, but I've looked at the first changes and they do fix the problem I had with the definition!

12. I won't argue that the ODRL constraints always amount to selecting a part of a resource. But some are clearly (e.g. the part of 18+ friends in user44's friend group, or the position within an asset).  And my hope was that looking at existing patterns for these requirements would fix some problems (i.e. the hijacking of URIs).

**Comment by aisaac** [comment]
I was asked by @riannella to check issues I'm involved in. I guess for this one it's up to whether anyone would like to react to the last point on 12. If there's no desire from the WG I guess it's acceptable, though perhaps a missed opportunity.

**Comment by riannella** [comment]
The WG seems ok with the current approach. @philarcher1 raised the correct use of URIs (a few weeks ago too).

**Comment by aisaac** [comment]
I would hope the WG is ok with the current approach for selectors!
I was suggesting to look at re-using exisitng patterns because it's a good practice (see BP15 at https://www.w3.org/TR/dwbp/#dataVocabularies).
But I also understand if the WG judges it has more pressing issues to solve. I have to reckon I've seen worse cases of ontology duplication, after all.

**Comment by riannella** [comment]
I believe that ODRL constraints required more than OA Selectors, such as operators (for example).

If there was a natural fit, we would have used it ;-)

**Comment by aisaac** [comment]
Well, this is the  most convincing answer I've received so far I think :-)
Maybe I've misunderstood something earlier: I was not under the impression that the OA selectors had been examined, and a clear case made that they were not capturing everything.
Now I believe that the issue can be closed!

**Comment by riannella** [comment]
Thanks
