### ISSUE TITLE
Auto Script Bugs

### ISSUE THREAD

**Issue by riannella** [w3c/poe#186]
1) When  you have a unionOf in a property like:

 rdfs:domain [
		a owl:Class ;
		owl:unionOf ( :Rule :Asset :Party ) ;
	] ;

The property does not then appear as "in range of" in the three classes.

The same for:

	rdfs:range [
		a owl:Class ;
		owl:unionOf ( :Duty :Action ) ;
	] .

The property then does not appear in "Inherited Properties"

2) Action is defined with:
	rdfs:subClassOf skos:Concept ;
but the auto-link to "skos:Concept" points to an internal "#term-" when it should link to the skos document

**Comment by riannella** [comment]
Fixed 2)

**Comment by simonstey** [comment]
>   When you have a unionOf in a property like:
>
>rdfs:domain [
a owl:Class ;
owl:unionOf ( :Rule :Asset :Party ) ;
] ;
>
>The property does not then appear as "in range of" in the three classes.

fwiw, that's because ->
https://github.com/w3c/poe/blob/36d1a6a91e33112737853239de78076764dac01c/vocab/template.phtml#L297 

`^rdfs:range` stops at the blank node

**Comment by simonstey** [comment]
if I'm not mistaken, the correct path in case of a unionOf should be something along the lines of: `^rdf:first/(^rdf:rest)*/^owl:unionOf/^rdf:range`

(untested though)

or even `(^rdf:first/(^rdf:rest)*/^owl:unionOf)?/^rdf:range`

**Comment by simonstey** [comment]
rdfs:range of course

**Comment by riannella** [comment]
nice find @simonstey !

But it did not work...

We need to find the right sparql query...?

**Comment by simonstey** [comment]
how did you run the script? I might find some time to fiddle around with that today

**Comment by riannella** [comment]
To generate index.html, you will need to install:
  http://librdf.org/raptor/rapper.html

Then you can edit template.phtml (and ODRL22.ttl etc) and "make"

Sometimes I need to "make" 3 times for it to work!

**Comment by riannella** [comment]
I managed to do a dump of what EasyRDF stores.
Here is an example:

```
http://www.w3.org/ns/odrl/2/partOf (Phpspecgen_Property)
  -> rdf:type -> rdf:Property, owl:ObjectProperty, skos:Concept
  -> rdfs:isDefinedBy -> odrl:
  -> rdfs:label -> "Part Of"@en
  -> skos:definition -> "Identifies an Asset/PartyCollection that the Asset/Party is a member of."@en
  -> rdfs:domain -> _:genid1
  -> rdfs:range -> _:genid4
  
  
_:genid1 (Phpspecgen_Class)
  -> rdf:type -> owl:Class
  -> owl:unionOf -> _:genid2

_:genid2 (EasyRdf_Collection)
  -> rdf:first -> odrl:Asset
  -> rdf:rest -> _:genid3

_:genid3 (EasyRdf_Collection)
  -> rdf:first -> odrl:Party
  -> rdf:rest -> rdf:nil
  
 _:genid3 (EasyRdf_Collection)
  -> rdf:first -> odrl:Party
  -> rdf:rest -> rdf:nil

_:genid4 (Phpspecgen_Class)
  -> rdf:type -> owl:Class
  -> owl:unionOf -> _:genid5

_:genid5 (EasyRdf_Collection)
  -> rdf:first -> odrl:AssetCollection
  -> rdf:rest -> _:genid6

_:genid6 (EasyRdf_Collection)
  -> rdf:first -> odrl:PartyCollection
  -> rdf:rest -> rdf:nil
```

**Comment by simonstey** [comment]
I think I've fixed it.. updated [template.phtml](https://github.com/w3c/poe/commit/772f384a2af5d13530b1d1226fca40c05e508b16) and [classes.php](https://github.com/w3c/poe/commit/be448260f64f9536e74e413cd4a2a5e53868b5a1)

**Comment by riannella** [comment]
Yes - great work @simonstey  !!!!
