### ISSUE TITLE
assigneeTo and assignerTo inverse properties?

### ISSUE THREAD

**Issue by riannella** [w3c/poe#190]
We have two external entities we refer to: Assets and Parties.

For Assets, we now have the inverse property hasPolicy for target.
(so an Asset, in the wild, can assert a relationship to an ODRL Policy)

Should we consider also the same for Parties?
That is:
  :assigneeTo owl:inverseOf :assignee ;
  :assignerTo owl:inverseOf :assigner ;

Then, a party can assert they are the assignee/assigner to a Policy.

This may be useful for "instant licenses" so an party can say:

  :billie odrl:assigneeTo :policy100

Thoughts?

**Comment by simonstey** [comment]
> Should we consider also the same for Parties?
That is:
:assigneeTo owl:inverseOf :assignee ;
:assignerTo owl:inverseOf :assigner ;

- `odrl:assigne(r|e)To`->`odrl:assigne(r|e)Of`
- what about all the other ["functional roles" of parties](http://w3c.github.io/poe/model/#function)?

> Then, a party can assert they are the assignee/assigner **to a Policy**.

Not exactly, it's **to all Rules** of a Policy, cf. [2.3.1 Function](http://w3c.github.io/poe/model/#function) which says: 

> A function property is used to link a **Rule to a Party**, indicating the function undertaken by the Party **in respect to the Rule** that links to it. The function property itself is abstract; sub-properties represent explicit semantics of the functional role between the **Party and the Rule**.

Which actually makes the definitions of assigner/assignee given in [2.3.1 Function](http://w3c.github.io/poe/model/#function) incorrect: 

>  **assigner:** indicates **the Party that is issuing the Policy**. For example, the Party granting a Permission or requiring an agreed Duty to be performed.
    **assignee:** indicates that **the Party that is the recipient the Policy**. For example, the Party being granted a Permission or required to perform an agreed Duty.

For example:
```turtle
<http://example.com/policy:01> 
    a odrl:Policy ;
    odrl:permission [
        a odrl:Permission ;
        odrl:assigner ex:Alice ;
        odrl:target ex:target1 ;
        odrl:action odrl:reproduce ;
    ] ;
    odrl:prohibition [
        a odrl:Prohibition ;
        odrl:assigner ex:Bob ;
        odrl:target ex:target2 ;
        odrl:action odrl:print ;
    ] .
```
- who is the `odrl:assigner` of `<http://example.com/policy:01>`? 
- is it both `ex:Alice` and `ex:Bob` even though they both assigned only one rule each?
- if `ex:Alice` becomes the `odrl:assigner` of `<http://example.com/policy:01>`, wouldn't she become the assigner of the prohibition too (according to [2.7 Policy Rule Composition](http://w3c.github.io/poe/model/#composition))?

**Comment by riannella** [comment]
Fixed the Policy/Rule issue with assigner/e
commit: bc11e69f0ca87d1f5555a3df3cd886f93a104e7a

1) yes, "assignerOf" and "assigneeOf" ;-)
2) Other functional roles: we should only deal with the "core"

3) Policy has two assigners (bob and alice)
4) Yes, as a Policy, but as a Rule, they are have one Rule each.
5) Yes (if she was to become odrl:assignerOf policy:01)

**Comment by simonstey** [comment]
> Policy has two assigners (bob and alice)
>
> Yes, as a Policy, but as a Rule, they are have one Rule each.
>
> Yes (if she was to become odrl:assignerOf policy:01)

My point is that there's a subtle but important difference between:

1. _"A policy has/contains two assigners"_ -> only implying that |AS| = 2, with AS being the set of all assigners of rules in the policy 
2. _"Alice and Bob are both the assigner of the policy"_ -> implying that |AS| >= 2, **and** that both Alice and Bob are the assigners of **all** Rules in the policy.

**Comment by riannella** [comment]
Yes, agree. Functional roles only apply to Rules.

So, we would not typically say that a "Policy has two assigners" -> we would say that a "Policy has two Rules, and each of those has one assigner".

**Comment by nitmws** [comment]
We must avoid any statement indicating an assignee/r party and a policy have a direct relationship (in which direction ever). This should be stated only regarding a Rule.
And the same applies to hasPolicy (see #188): no statement about a Policy having a target asset and in the inverse that an Asset is the target of a Policy. Such statement can only be made regarding Rules too.

**Comment by riannella** [comment]
I've added the new inverse properties:
  https://w3c.github.io/poe/model/#policy-assigned

Comments? (haven''t added to Vocab yet)

commit: ebee0d47953fa1db0ca72e7d7dad912a3a9c5f2e

**Comment by riannella** [comment]
Added to Vocab.

commit: a65c9de73abe6a99c4e4be11e579d887a116b2fa

**Comment by simonstey** [comment]
>I've added the new inverse properties:
https://w3c.github.io/poe/model/#policy-assigned

the description references http://example.com/policy:1011 while the example uses http://example.com/policy:1010

**Comment by riannella** [comment]
fixed

commit: 60012d41b51fb006894d38538e568157cf1285a6
