### ISSUE TITLE
Specifications of includedIn and implies need improvements

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#192]
I refer to Asset in the Information Model Editor's draft of 12 June - http://w3c.github.io/poe/model/#asset

**Re includedIn**

* For Policy, Asset and Party classes the properties are explicitly listed, this should be done for `includedIn `and `implies `of the Action class too.
* Definition of `includedIn`, starting with "The purpose of the includedIn ...": "the latter" and "the former" should be replaced by explicit statements and the unclear statement about conflicts with other actions should be dropped. 
E.g. "The purpose of the includedIn property is to explicitly assert that the semantics of the referenced instance of an other Action encompasses (includes) the semantics of this instance of Action." ... and add "This implies that a permission or prohibition of an encompassing Action is inherited by all actions with an includedIn relationship."
* Is `includedIn `transitive? Has "print" to assert `odrl:includedIn odrl:present` and `odrl:includedIn odrl:use` or is `odrl:includedIn odrl:present` sufficient as long as `odrl:present odrl:includedIn odrl:use` is asserted? I'm in favour of making it transitive, this needs to be added to the definition.
* The statement "... if play is permitted in a Policy and use is prohibited in the same Policy, ..." is only true if the mentioned Permission and Prohibition share the same target Asset - and different target Assets in (different Rules of) a Policy are allowed.
* The underlying link of "Policy Conflict Strategy" has a typo.

**Re implies**

* The statement "For Actions that form dependencies (eg Action X requires Action Y)  ..." is misleading: also `includedIn `sets relationships between instances of Action. 
* My suggestion: start the paragraph with "The `implies `property asserts that this instance of Action implies that the other instance of Action is not prohibited." ... and add "`implies `can be used for Action instances which have no `includedIn `relationship."
* The example should be "For example, if a `share `Action implies explicitly the `distribute `Action, then if `share `is permitted in a Policy and `distribute `is prohibited in the same Policy - and both actions apply to the same target Asset - this would cause a conflict in the Policy. If an implied other action is not prohibited this does not cause a conflict."

**Comment by riannella** [comment]
IncludedIn
1) Done
2) Done
3) Agree - should be transitive
4) Done 
5) fixed

Implies
1/2) Done
3) Done

commit: cd6890751c8187e49b728a941d35b8f8ac8f1c08

**Comment by nitmws** [comment]
Re Information Model of 13 June / section 2.4 Action:
The statement "Action terms must be defined using the includedIn property with either use or transfer as the parent term. " does not reflect having a transitive includedIn. Should be like "Action terms must be defined using the includedIn property referring to an encompassing Action and either use or transfer as the top level parent term by transitive means."

Re Vocabulary of 13 June:
The specification tables of Action instances show Included In now but as value only "use" or "transfer". But we have defined in earlier versions that display, play and print have present as encompassing Action and extract has reproduce as encompassing Action.

**Comment by riannella** [comment]
1) Updated

2) Updated reproduce/extract 

As for "present" - this has been discussed in issue #101 
The resolution (at the time!) was that Present did not encompass all the 3 children, and thoses relationships were removed. This can be challenged now that we have a clearer definition (and motivation) for includedIn

commit 5202a25729de97486e99b9ace17f217eed432ca5

**Comment by riannella** [comment]
Now that "includedIn" is more "encompasses" (rather than a pure hierarchy) then I propose we more precisely define "Present" as "To perform and visualise a multimedia Asset"
with 
Play: To perform an multimedia Asset
Display: To visualise a multimedia Asset

I don't think "print" fits in?

**Comment by nitmws** [comment]
The history of this mini-tree in ODRL 2.1 is:
Present = to perform or exhibit an Asset to an audience.
Print =  to print an Asset onto paper or to create a hard copy.
Play = to perform an audio Asset to an audience.
Display = to display the visual media Asset to an audience or the public.

Present encompassed that an audience can experience any kind of presentation of an asset. Frankly the focus was set on a media asset - the definition did not tell that unfortunately. (Display of a database would be interesting ;-)
And print provided an experience by a hard copy, play an audio experience, and display a visual (potentially plus audio) experience.
I agree that print does not fit very well as sibling of play and display as it is in fact more a subclass of display.

So I suggest as definitions
Present: to perform or exhibit a media Asset to an audience + IncludedIn Use
Play: to perform an audio media asset + IncludedIn Present
Display:  to perform a visual media asset with an optional audio media asset (Note: covers both still and moving images, possibly with audio) + IncludedIn Present
Print: to perform any fitting media asset as hard copy + IncludedIn Present or Use

Note regarding #101: actions like present, play and display implicitly include a presentation to an audience by the natural language semantics of these terms. If the assignee wants to constraint the audience this can be done but I disagree to removing the term audience from the definition of the action. Use cases I'm familiar with is to define characteristics of the audience (private friends of the assignee, students of a school/university) or a size in connection with a licence fee.

**Comment by riannella** [comment]
I think if you want Present to be some form of **public performance**, then it should not then be includedBy play and display.

The latter are aimed at "personal use" (and yes, you can show your friends at home, but not hire a 10,000 seat stadium and "play" the latest hollywood movie).

But, you can **explicitly** add wider recipients to "play" if needed (or just use the new Present).

**Comment by nitmws** [comment]
Sorry, I disagree. 
Play means to let the sound of an audio media asset fill a space for the purpose of letting person(s) listens to this sound. This is the physical action for a specific generic purpose. The same applies to display and also to print.
The count of the persons consuming the media asset is another story. It is well known that e.g. media assets have different licence fees for different counts - and this can be scoped by a constraint. But please let's not create different actions for different sizes of the audience.

**Comment by vroddon** [comment]
@nitmws, 

In the area of contracts on rights on multimedia assets, public performance is a very commonly traded right. How should this be expressed in ODRL then?

**Comment by nitmws** [comment]
@vroddon use "display" as action and by my understanding: if no constraint is set the asset can be displayed to an unlimited audience.

**Comment by riannella** [comment]
@nitmws let me pose two use cases ;-)

1) I buy song x from Apple to listen on my iPod - is this odrl:play?
2) I buy song x from Sony to play at (a very full) Wembley Stadium - is this odrl:play ?

**Comment by riannella** [comment]
Public Performance (or more technically, the right to Communicate) is an exclusive right of copyright owners, and hence, can be traded to others.

**Comment by riannella** [comment]
Here is the latest proposal:

Play: To play a multimedia Asset
Display: To visualise a multimedia Asset
Present: To publicly perform the Asset

comments?

**Comment by vroddon** [comment]
Absolutely unimportant, but I don't quite catch the difference between "play" and "display".

**Comment by riannella** [comment]
@vroddon did you mean "unimportant" ?

How about these:

Play: To create a sequential and transient rendition of an Asset.
Display: To create a static and transient rendition of an Asset
Print: To create a tangible and permanent rendition of an Asset

and Display will be "includedIn" Play ?

**Comment by vroddon** [comment]
Wow! very technical. Still, I don't catch the meaning. As a newcomer, if I wanted to express the act of viewing a picture in my smartphone... ...would it be a play or a display?
Intuitively I would say "display" has to do with still image assets (photos), whereas "play" has more to do with audiovisual (audio, video). 
Yes, I said "unimportant" as I don't want to divert efforts from other discussions... ...but now I realize that a beginner will ask the same about this. Perhaps we can add an example to the definitions (in a note maybe).

**Comment by riannella** [comment]
Yes, we will add an example in the skos:note

**Comment by riannella** [comment]
Updated the terms.
Commit: 33df1fe93fb170514606de61787f45d3e636e353
