### ISSUE TITLE
not all contraint operators are logical operators

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#194]
http://w3c.github.io/poe/model/#constraint: 
> Constraints can be represented as Atomic Constraints - in which the left and right operands are **logically compared** - or as Compound Constraints in which the left and right operands are existing Atomic Constraints, **which are also logically compared**.

that's wrong, you can't use logical operators in atomic constraints.

Relational operators [1]:
```
    < : less than
    <= : less than or equal to
    > : greater than
    >= : greater than or equal to
    == : equal to
    /= : not equal to
```

Logical operators [2]:
```
    .NOT. : logical not
    .AND. : logical and
    .OR. : logical or
    .EQV. : logical equivalence
    .NEQV. : logical not equivalence
```

[1] http://www.cs.mtu.edu/~shene/COURSES/cs201/NOTES/chap03/relational.html
[2] http://www.cs.mtu.edu/~shene/COURSES/cs201/NOTES/chap03/logical.html

--------------

Also 

> A Rule becomes effective if all of **its Constraints are satisfied**. 

:+1: 

> If the logical expression evaluates to true **the result of the Constraint is satisfied**. 

:-1: (the constraint is satisfied, not its result)

**Comment by riannella** [comment]
Updated narrative (removed 'logical')

commit: 4fecef42057870c0fbf415297bb1e37b84c9f2c7

**Comment by riannella** [comment]
@simonstey are you ok with my comments I made on your commit comments?

**Comment by riannella** [comment]
#199 will address this now
