### ISSUE TITLE
Checking the dynamic use of partOf

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#196]
That's the use case:
An asset entity uses hasPolicy, the id of this asset is http://example.org/assets/131432. The referred policy (http://example.com/policy:1033) defines as target asset a collection of many assets (http://example.com/assetCollection:8378) intentionally including this asset http://example.org/assets/131432. 

To check:

* MUST this asset be included into the Policy document/resource with a relationship odrl:partOf?
* or is it sufficient to state as property of this asset that it is odrl:partOf and the asset's id does not appear in the policy - e.g. (nar: is the namespace of the IPTC News Architecture)
```
# the Policy
{
   "@context": "http://www.w3.org/ns/odrl.jsonld",
   "@type": "Offer",
   "uid": "http://example.com/policy:1033",
   "permission": [{
       "target": "http://example.com/assetCollection:8378",
       "action": "display",
       "assigner": "http://example.com/party:0001"
   }]
}

# the Asset entity
{
   "@type": "nar:newsItem",
   "@id": "http://example.org/assets/131432",
   "nar:headline": "Brexit negotiations have started today",
   ...
   "odrl:partOf": "http://example.com/assetCollection:8378",
   "odrl:hasPolicy": "http://example.com/policy:1033",
   ...
}
```

Such a use case is essential for the news industry as a persistent policy should be able to cover "just created" new news items.

A similar use case could apply to Party and PartyCollection - e.g. new students, does each one has to be added to the policy?

**Comment by riannella** [comment]
odrl:partOf would typically be used in the Asset definition as you have done  (not the Policy).

But you could also do:

 "permission": [{
       "target": [{
           "@type": "AssetCollection",
           "uid":  "http://example.com/archive1011" },
          { "@type": "Asset",
           "uid":  "http://example.com/archive1012",
           "partOf":  "http://example.com/archive1011"}
       "action": "....",
  




See another example here: https://www.w3.org/2016/poe/wiki/Policy_Inference

**Comment by nitmws** [comment]
Ok, I suggest to add a copy of example 6 as second example (6b) to Target Policy in the Information Model with
`"odrl:partOf": "http://example.com/assetCollection:8378",`
in the graph and the explanation that being part of a collection can be expressed this way.

**Comment by simonstey** [comment]
> Such a use case is essential for the news industry as a persistent policy should be able to cover "just created" new news items.
> 
> A similar use case could apply to Party and PartyCollection - e.g. new students, does each one has to be added to the policy?

```turtle
:alice odrl:memberOf <http://example.com/students> .

:asset1 odrl:partOf <http://example.com/assetCollection:8378> .

<http://example.com/policy:1033> 
    a odrl:Offer ;
    odrl:permission [
        a odrl:Permission ;
        odrl:target <http://example.com/assetCollection:8378> ;
        odrl:action odrl:display ;
        odrl:assignee <http://example.com/students> ;
    ] .
``` 
-> `:alice` is permitted to display `:asset1` 

-------------
adding `:bob` as new member of `<http://example.com/students>` and `:asset1` as new part of asset collection `<http://example.com/assetCollection:8378>`:
```turtle
:alice odrl:memberOf <http://example.com/students> .
:bob odrl:memberOf <http://example.com/students> .

:asset1 odrl:partOf <http://example.com/assetCollection:8378> .
:asset2 odrl:partOf <http://example.com/assetCollection:8378> .

<http://example.com/policy:1033> 
    a odrl:Offer ;
    odrl:permission [
        a odrl:Permission ;
        odrl:target <http://example.com/assetCollection:8378> ;
        odrl:action odrl:display ;
        odrl:assignee <http://example.com/students> ;
    ] .
``` 
-> `:alice` is permitted to display `:asset1` and `:asset2`
-> `:bob` is permitted to display `:asset1` and `:asset2`

**Comment by riannella** [comment]
I've added new partOf sections to Asset/Party and added examples.

commit: 64e83c716a92e20052286b7630ea7d70d7f80a1b
