### ISSUE TITLE
XML Schema design

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#197]
Having a look a the XML Schema https://github.com/w3c/poe/blob/gh-pages/vocab/ODRL22.xsd of 2 June and trying to take the position of an ODRL newbie:

* In general: why is the naming of elements so different from the JSON shown in the Information Model document? XML has no target, assigner, assignee etc. It looks like the XML schema sets of focus on the classes and asserts a subclass by an attribute. But the Rule class does not appear, only its subclasses Prohibition and Permission - why only these two. (yes, I'm aware that their structure is different - but hard to get for a newbie.)
This makes it hard for an implementer to get familiar with both serializations.
* why is the root element Policy in upper case but all of its children in lower case - does this show any basic difference between them?
* the child choice of Policy claims there must be at least 1 of the children - but that doesn't reflect the Information Model: it claims - see #188 - a policy must have at least 1 permission or prohibition. For the XML Schema a policy with only an asset is ok.
* constraint has xs:ID as datatype of @id. @name (= leftOperand) has anyURI. But a string being a valid xs:ID does not have to be a valid xs:anyURI. In a Compound Constraint the name has to refer to a constraint by its (u)id - that does not fit -> **Bug**!
* permission has a choice with cardinality 1..unbounded and this choice has the elements asset and action with cardinality 1..unbounded. But that does make an asset and an action element mandatory children of permission, my XMLspy is happy with this permission 
```
<o:permission>
    <o:party function="o:assigner"/>
</o:permission>
```
The same applies to prohibition. Looks like a **bug** in the XML Schema.
* constraint @rightOperand has a datatype odrl:listOfValues being a list of xs:string. A URI should fit into that - but why can multiple rightOperand values be applied to the constraint in XML? A bug?

Basic question: must the POE/ODRL XML Schema be close to or even compatible with the ODDRL 2.1 Schema, or would it be possible to rename elements and attributes to names used in the Information Model and in JSON.

Sub-question: did anybody check the backward compatibility of the POE/ODRL XML Schema against the ODRL 2.1 schema. Major issues are if ODRL 2.1 features are not supported by POE/ODRL.

**Comment by simonstey** [comment]
> Basic question: must the POE/ODRL XML Schema be close to or even compatible with the ODDRL 2.1 Schema, or would it be possible to rename elements and attributes to names used in the Information Model and in JSON.

it must be compatible/consistent with the current IM&Vocab

**Comment by riannella** [comment]
1) The naming of xml entities was designed to fit the most flexible model in that most "elements" will be URIs (defined by the ontology).
So that is why we have the "function" attribute and the values can be "...odrl/2/assignee" etc.
This then means anyone can have any URI as the functional role and you don't need to modify the XML Schema to add any new elements or attribute values. The XML serialisations becomes a framework to plugin the ODRL URIs. There is not need to serialise the Rule class as it never explicitly appears in serialisations (not even turtle/json-ld)

2) No reason. At the time, the root element had a capital P ;-)

3) This is a limitation on the XML Schema cardinality mechanism. There is no way to effectively say that out of the 6 possible elements, that "one of two must appear". I've added a comment.
(implementors may use schematron for additional validation)

4) Fixed, now URI or IDREF

5) See 3) above

6) We support multiple values for operators like isAnyOf 

Basic Q: The XML Schema is the "best fit" for the ODRL model (nothing will be perfect)

Sub-question: yes, me ;-) V2.2 is a superset of V2.1

commit: c8cb4c4669e83a906484332746c904fbe8e7dd1c

**Comment by riannella** [comment]
3) Actually, we could add some xs:assert elements, such as:

`<xs:assert test="(@type='http://www.w3.org/ns/odrl/2/Offer' and ( (count(./o:permission) > 0 ) or (count(./o:prohibition) > 0 ) ))"/>`

But this will get messy quickly and we need articulate all the Types

**Comment by nitmws** [comment]
Re @riannella 

re 1. I'm aware that an XML element with generic semantics and with an attribute to narrow down semantics (e.g. for a subproperty in RDF) is a very flexible solution. 
The ODRL IM defines only two functions of Party: assigner and assignee, all other functions are "add ons" (and I think should be from another namespace). This way a new function gets a new name/identifier in a not-ODRL namespace, e.g. `"xyz:paymentReceiver" : "http://example.com/company/acme99"` . The same could be achieved in XML: defining `<assignee>` and `<assigner>` as Party instances in the ODRL namespace, and the "add on" party is `<xyz:paymentReceiver id="http://example.com/company/acme99" />` - the required `any ##other` extension point already exists in the XML Schema.
Summary: what ODRL defines on its own is an element in the ODRL namespace, optional additional things have to be in another namespace and are taken by extension points. This supports having identifiers of  Things reflected by the QName of an element and it would be closer to the JSON serialisation.

re 3. There is a design to enforce required elements but this needs a slight Schema redesign: all mandatory elements have to be children of a sequence, all the optional elements are children of a choice which is also a child of the sequence (after the mandatory elements). I've tested this design and it delivers what the IM requires. 
```
<xs:complexType name="Permission">
	<xs:sequence minOccurs="1">
		<xs:element ref="o:asset" maxOccurs="unbounded"/>
		<xs:element ref="o:action"/>
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="o:constraint"/>
			<xs:element ref="o:duty"/>
			<xs:element ref="o:party"/>
		</xs:choice>
		<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attributeGroup ref="o:idAttributes"/>
</xs:complexType>
```
re 6. Sorry, my question was about rightOperand, not operator.

**Comment by riannella** [comment]
1) if we follow that model, then XML implementors need to create/maintain two items for the same thing: the URI for the term, and the xml element. The current model, all is needed is the URI for the term (that other serialisations can use too)

Dave Compton at TR is an ODRL XML implementor (from what I have seen). Perhaps ask him what is preference is? Doing this change will break every exisiting xml implementation.

3) I did look at that, but the problem you run into is that this is also a valid policy:
<Policy....>  
   <asset uid=""/>
   <assigner uid="/>
   <permission>
     <action name=""/>
  </permission>
</Policy>

The only option is <xs:assert> rules.

**Comment by nitmws** [comment]
re @riannella 

re 1. hm, RDF/XML defines "RDF/XML uses XML QNames as defined in Namespaces in XML [XML-NAMES] to represent IRIs." (https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-intro) - this way http://purl.org/dc/elements/1.1/title and <dc:title xmlns:dc="http://purl.org/dc/elements/1.1/">  provide the same identifier.
I'll ask Dave.

re 3. sorry, can't get your reasoning. Do you claim a Policy with only an assigner is a valid policy?

**Comment by riannella** [comment]
Sorry...it ignored some of my xml elements. Example is:
```
<Policy....>  
   <asset uid=""/>
   <assigner uid="/>
   <permission>
     <action name=""/>
  </permission>
</Policy>
```

**Comment by riannella** [comment]
1)...hmmm...But aren't we talking just plain old XML? (not RDF/XML)

**Comment by nitmws** [comment]
For "plain old" XML a rule like "append the namespace URI and the local name to create a URI for the element" does not exist. This was "invented" by RDF.
See "plain old" namespace rules at https://www.w3.org/TR/xml-names/#ns-using - example:
`<edi:price xmlns:edi='http://ecommerce.example.org/schema' units='Euro'>32.18</edi:price>`
This would result in this URI for the price element `http://ecommerce.example.org/schemaprice` - not an invalid URI but hard to use in practice. (http://ecommerce.example.org/schemaprice and http://ecommerce.example.org/schemataxClass vs. http://ecommerce.example.org/schema#price and http://ecommerce.example.org/schema#taxClass, the latter is much easier to publish by a single core document/resource.)
Or look at the "old" HTML namespace: xmlns:html='http://www.w3.org/1999/xhtml
Only the "RDF-aware" namespace URIs required to have a separator at the end, e.g. # or /

**Comment by simonstey** [comment]
> Only the "RDF-aware" namespace URIs **required** to have a separator at the end, e.g. # or /

are they? 
https://www.w3.org/TR/rdf11-concepts/#section-IRIs says:
> IRIs in the RDF abstract syntax MUST be absolute, and **MAY** contain a fragment identifier.

**Comment by nitmws** [comment]
https://www.w3.org/TR/rdf11-concepts/#dfn-namespace-iri talks about IRIs used for namespaces - and does not explicitly require # or / at the end in this section. But all the namespace IRIs used in the RDF 1.1 documents use one of them and also the majority of Turtle or JSON-LD W3C documents, this is setting a strong message at least. I don't know if an explicit requirement exists somewhere else and have to time to search for.

**Comment by riannella** [comment]
@nitmws Is the proposal to rewrite the XML Schema to support new <elements> instead of referring to URIs from the Vocab (and other Profiles) ?

**Comment by riannella** [comment]
@nitmws What do you want to do/propose with this issue?
