### ISSUE TITLE
Use of cardinality restrictions in the ontology?

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#198]
At the call on 19 June - https://www.w3.org/2017/06/19-poe-minutes - the question was raised if something required for testing is missing in the ontology.
I think the definition of the cardinality of object and data properties is missing as the free-text of the Information talks about it but this is not reflected by the ontology.

OWL 2 defines how to express cardinalities https://www.w3.org/TR/owl2-syntax/#Object_Property_Cardinality_Restrictions and https://www.w3.org/TR/owl2-syntax/#Data_Property_Cardinality_Restrictions

The specification of the Information Model that "a Rule MUST have an Action via the action property" could be expressed this way:
```
:Rule a rdfs:Class , owl:Class, skos:Concept ;
    rdfs:subClassOf [ rdf:type owl:Restriction ;
                        owl:onProperty :action ;
                        owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger ;
                        owl:onClass :Action
                      ] .
```

(btw:  I guess we need an "ontology" Github label)

**Comment by iherman** [comment]
@nitmws : I agree the ontology should express these things if possible; it may also help in specifying our testing goals.

I am _not_ a good OWL2 expert, I would expect @simonstey to see this. But I think the same expression can be made slightly more simple:

```
:Rule a rdfs:Class , owl:Class, skos:Concept ;
    rdfs:subClassOf [ rdf:type owl:Restriction ;
                      owl:onProperty :action ;
                      owl:cardinality "1"^^xsd:nonNegativeInteger ;
                    ].
```

But: does the IM means "a Rule MUST have an Action via the action property" there must be exactly one, or whether there must be at least one? Because if the latter, then ``owl:minCardinality`` should be used.

(As an aside: I always found the [OWL 2 Primer](https://www.w3.org/TR/owl2-primer/) an excellent source and a helpful document...)

**Comment by simonstey** [comment]
>@nitmws: At the call on 19 June - https://www.w3.org/2017/06/19-poe-minutes - the question was raised if something required for testing is missing in the ontology. [...]
>
>**OWL 2 defines how to express cardinalities** [...] The specification of the Information Model that "a Rule MUST have an Action via the action property" could be expressed this way:

and so does [SHACL](https://www.w3.org/TR/shacl/#core-components-count) (cf. https://github.com/simonstey/ODRL-SHACL-Shapes/wiki/3.5-Rule) :
```turtle
# a Rule must have at least one value for odrl:action
ex:MinCountRuleShape
   a sh:NodeShape ;
   sh:targetClass odrl:Rule ;
   sh:property [
      sh:path odrl:action;
      sh:minCount 1 ;
   ] .

# all values of odrl:action must be of type odrl:Action
ex:ActionPropertyShape
   a sh:NodeShape ;
   sh:targetObjectsOf odrl:action ;
   sh:class odrl:Action .
```

Deciding whether to use OWL ([OWA](https://en.wikipedia.org/wiki/Open-world_assumption)), SHACL ([CWA](https://en.wikipedia.org/wiki/Closed-world_assumption)), or both for expressing those restrictions really depends on the respective use cases.

For example: 
+ You would use **OWL**, if you want to be able to _assert_ that any policy that has at least 1 assigner and 1 assignee for each of its rules is an agreement policy.
+ You would use **SHACL**, if you want to be able to _check_ whether all agreement policies have at least 1 assigner and 1 assignee for each of their rules.

**Comment by iherman** [comment]
@simonstey you are right. From the point of view of the CR process, and based on what you describe, SHACL might actually be a better option.

(I will have to read the latest SHACL document again:-)

**Comment by nitmws** [comment]
@iherman and @simonstey I see the points of your considerations but take the view of an ODRL newbie - the guys we have to convince ODRL is an easy-to-use standard: 

The restriction code at the top of this thread was not written down by me but by Protege (5.2.) and Protege also shows this restriction clearly in the User Interface. So if a guy investigating the ODRL ontology would see cardinality restrictions s/he could create policies accordingly. 
If the cardinality check is only done with SHACL such a guy has to be/get familiar with SHACL too, only then  s/he would be able to read the cardinality constraints.

My conclusion: ODRL should provide both, OWL constraints to reflect a complete Information Model to a user and SHACL rules to check existing policies properly.

**Comment by nitmws** [comment]
> But: does the IM means "a Rule MUST have an Action via the action property" there must be exactly one, or whether there must be at least one? Because if the latter, then owl:minCardinality should be used.


@iherman this statement shows a key problem of the current specifications: the free-text defines primarily cardinality in an (slightly) ambiguous way. To pin down the wording to be definitely unambiguous the free-text would get more verbose. Therefore I think the definition of cardinality by the ontology would set a clear status.

**Comment by iherman** [comment]
@nitmws 

> My conclusion: ODRL should provide both, OWL constraints to reflect a complete Information Model to a user and SHACL rules to check existing policies properly.

Maybe true. But I try to be realistic: do we have the time and energy to do both within our remaining charter time?

**Comment by nitmws** [comment]
@iherman I agree both need more time but delivering a half-baked standard shouldn't be our goal. I guess adding the cardinality constraints to the ontology should not exceed 4 hours of work - and I'm ready to commit.
I only need to find an agreement with @riannella that the ttl is not edited by him while I edit the cardinalities.
Another facet of this action is: I hope I'll interpret the free-text wording in a widely agreed way --> the cardinality needs to be reviewed.

**Comment by simonstey** [comment]
> If the cardinality check is only done with SHACL such a guy has to be/get familiar with SHACL too, only then s/he would be able to read the cardinality constraints.

The cardinality check can **only** be done with SHACL. OWL was never really intended to be used for the purpose of constraint validation. Again, I'm not saying that we have to choose between OWL or SHACL, but we have to use the right tool for the right purpose.

If the only reason to adopt OWL is so that Protege renders restrictions nicely, we might even consider dropping it all together and have RDFS/SKOS only.

In any case, a user of ODRL doesn't have to be familiar with OWL or SHACL at all anyway. That's why we have our information model.

**Comment by iherman** [comment]
>> If the cardinality check is only done with SHACL such a guy has to be/get familiar with SHACL too, only then s/he would be able to read the cardinality constraints.
>
> The cardinality check can only be done with SHACL. OWL was never really intended to be used for the purpose of constraint validation. 

That is an important point. It can actually be misleading. A cardinality constraint in OWL + an OWL reasoner may simply deduce that some individual are identical (to be more exact, they are `owl:sameAs`) and not reveal any errors. And that deduction results may actually lead to problems.

**Comment by nitmws** [comment]
> In any case, a user of ODRL doesn't have to be familiar with OWL or SHACL at all anyway. That's why we have our information model.

@simonstey you may be right by an academic view but from my experience with teams having to implement a standard they need a) something which shows in a strict way structures, properties and their cardinality as guideline for their serializations and b) something which checks if their instance of a serialisation complies with the specification.

(Aside: why was something like the JSON Schema created? It is far from perfect but there are development tools supporting feature a) and b) above - making developers almost happy.)

Currently ODRL provides to potential adopters:

* the Information Model document: it specifies classes and properties and should include their cardinality, but (currently) details are disputed. And it shows examples as JSON serialisation which is already a step out of an abstract definition.
* the Vocabulary document: is a human readable rendition of an also existing OWL ontology, it defines classes and properties and could define cardinality, but the ontology cannot be used for validation.
* an emerging SHACL document: it should be able to validate a graph against the Information Model.
* an XML Schema: it could be used to specify the XML serialisation of a policy instance and could be used to validate it against the schema. But the current schema has bugs and a design different from the JSON in the IM examples - #197 

Honestly, this makes it hard to encourage developers to use ODRL.

**Comment by simonstey** [comment]
>  you may be right by an academic view but from my experience with teams having to implement a standard they need **a) something which shows in a strict way structures, properties and their cardinality as guideline for their serializations**

 the IM should be exactly that. and as long as anyone feels that that's not the case (me included), the IM needs to be reworked and fixed.

**Comment by nitmws** [comment]
@simonstey I agree. But what is needed or missing to achieve that?

I see these basic, more formal needs:

* A consistent formal terminology. Should ODRL follow the RDF terminology and define classes and properties etc? (I support that.)
* What needs to be defined for a class. (e.g. a name and subclass of what other class(es) it is)
* What needs to be defined for a property. (e.g. a name, its domain and range, the cardinality in the domain classes)
* A consistent use of classes vs. properties. E.g. Policy Class defines "A Policy must include the permission and/or prohibition Rule", while in other places "a Policy must include a Permission and/or Prohibition" is told.

**Comment by riannella** [comment]
Some comments ;-)

1) If you feel the IM is incorrect/ambiguous then please indicate the precise place and make a recommendation (eg para 2 of section X says Y and perhaps should be Z, or why do you say Foo in para 9 of section W)

2) It will be impossible to express the full IM in an ontology/schema file.

**Comment by nitmws** [comment]
re 1. I've started to add notes to a printout of the IM. Where to put that - I prefer a Wiki page, easier to edit than a Github issue. A bit tricky is the dynamic status of the IM: reviewing takes time and in this period the wording may have changed ...

re 2. ok, but then we should write down what is covered by the ontology and what not.

**Comment by riannella** [comment]
Github issues are the best and most transparent way.

**Comment by nitmws** [comment]
But how to do that in practice? If I suggest to change 20 paragraphs should I open 20 issues? Or all in one issue, but then it will be very hard to track the discussion on specific suggestions (which is already the case in some Github issues)

**Comment by riannella** [comment]
20 github issues 👍

**Comment by nitmws** [comment]
OK, a first set of issues combined in Github issue #200
