### ISSUE TITLE
Clarify role of conflict resolution

### ISSUE THREAD

**Issue by riannella** [w3c/poe#20]
Conflict is not only used for resolving merge issues but also between perms/prohibits in the same policy

**Comment by sereAbi** [comment]
We can add to the conflict description in Sec. 4.1 that conflict may also be used to set priorities over the Permissions/Prohibitions in the same policy.

**Comment by sereAbi** [comment]
I updated the conflict description as mentioned above.

**Comment by riannella** [comment]
Completed
