### ISSUE TITLE
IM wording for classes and their relationships

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#200]
Going over the [Information Model (IM) document](https://w3c.github.io/poe/model) I notice that the wording of relationships between classes is not clear and/or inconsistent.

1. Is RDF the data model behind the IM? No clear statement about it anywhere. But [1.2 Conformance](https://w3c.github.io/poe/model/#conformance) tells "The examples throughout the document are serialized as [json-ld]" and many examples use properties from the rdfs: namespace - my conclusion: the IM builds on RDF (and it would help to write this down), and my suggestion: RDF terms should be used.
2. Among the key "building blocks" of ODRL only Policy is named as Class in the headline, all others not but [2. ODRL Information Model](https://w3c.github.io/poe/model/#infoModel) claims all are classes. My suggestions: name Asset, Party, Action, Rule and Constraint as ... Class in the headline and in the free-text definition ...
3. ... and do the same for subclasses like Set, Offer, Agreement, AssetCollection, PartyCollection, Permission, Prohibition and Duty.
4. ... and do something equivalent for the definition of properties like Relation, PartOf, ...: add Property already to the headline.
4. open issue: are the Atomic Constraint class and the Compound Constraint class a subclass of Constraint or independent classes? ("subclass" does not occur in 2.6 Constraint)
5. Properties of a class: from the Policy class down to the Compound Constraint class all classes have a list of properties with this heading "The .... class has the following properties:" - that's good.
6. How the properties are defined is inconsistent. Many of the Github issue discussions show a need for a/ a definition of the cardinality of the property in the (domain) class and b/ a definition of the class(es) a property establishes a relationship to (the Range in RDF terms).
Example: the Rules class defines "... must have an Action via the action property" and "... may have one or more Parties via a sub-property of the function property" - my assumption was "a single action property only, but many e.g. assignees", but that's contradicted in 2.7 Policy Rule Composition.
7. "containing" classes: e.g.  section [2.7 Policy Rule Composition](https://w3c.github.io/poe/model/#composition) says "A Policy may **contain** multiple Rules, and each Rule may contain multiple Assets, Parties, Actions, Constraints, and Duties." Sorry, but what is the **contain** property or is this meant "A Policy may contain Rules by permission and prohibition properties ..."? 
As in RDF a relationship between classes can only be established by a property this must be reflected in the normative wording of the IM.
8. ... therefore this statement in 2.7 is unclear: "A Policy may also contain Assets, Parties, and Actions at the Policy level, ..." by which properties, please? The [list of properties of Policy Class](https://w3c.github.io/poe/model/#policy) does not include a single property for this purpose. But in e.g. example 26 an "assigner" is shown at the top level.

**Comment by riannella** [comment]
1) I think the main reason we don't explicitly state it (just as the Annotation spec does not: https://www.w3.org/TR/annotation-model/) is that the ODRL IM is **more** than just the RDF model. We do use Class and property terms.

2) I've added "Class" to all the main headings for consistency, and the first para uses "Class", then after that just using the Class name with Capital first letter seems ok? (see Annotation spec too ;-)

3) Under the IM Figure we state:
**The ODRL Information Model includes the following classes:**

So the reader should know that for the rest of the document?

4) We explicitly state they are all properties, like in:
**The Asset class has the following properties:**
So wouldn't adding "property" after each and every term get repetitive?

5) They are both the same Constraint class. They only differ in the object of their left/right operands.

6) thanks ;-)

7) Don't forget that 2.7 introduces "short-cuts" but the rest of the IM talks about the normative model - that is the end-process of un-shortening the short-cuts in 2.7.

Is there any parts of the normative IM that have unclear cardinalities?

8) Changed to "related to"

9) see 8)

commit: 5d3410270c50b9ccf3f5411be869956a551d60a8

**Comment by nitmws** [comment]
@riannella thanks for all the changes you have applied so far.
Re your list above:
1. What does "**more** than just the RDF model" mean? Class and Property are defined by the RDF Schema and this is part of RDF (see https://www.w3.org/standards/techs/rdf). (Note: the Web Annotation Rec tells "The examples throughout the document are serialized as [JSON-LD] using the Context given in Appendix A of the Annotation Vocabulary"  and the Vocabulary makes heavy use of RDF(S) and OWL - I guess nobody will assume the Web Annotation does not build on RDF.)
2. thanks
3. In practice such a "single point of information" does not work. If one looks into [2.5.1 Permission](http://w3c.github.io/poe/model/#permission) and can't find there that this is a subclass it would be hard to argue "you should have looked at the list of classed below the IM figure". If an overview makes a basic definition (like: "this is a subclass") then this should be reused in a detailed definition.
4. I would appreciate having "Property" in the headline. 
like 2.1 Asset Class --> 2.2.1 Relation Property --> 2.2.2 Part Of Property - to override the assumption all sub-items of a section about a Class are subclasses.
5. Sorry, the lists of properties for Atomic and Compound Constraint are quite different and defining different sets of properties and a different use of them for instances of the same class does not fit well into the ODRL design. Ok, that's not an IM wording issue, should be discussed by a specific issue.
6. welcome
7. To be precise: I suggest to use such wording templates for defining properties:
a/ cardinality 0..1: A {domain class name} may have one or none {property name}  for {range class name}
b/ cardinality 1: A {domain class name} must have one {property name}  for {range class name}
c/ cardinality 0..unbounded : A {domain class name} may have none, one or many {property name}  for {range class name}
d/ cardinality 1..unbounded : A {domain class name} must have one and may have many {property name}  for {range class name}
(note: hm, 2.7 doesn't show a "non-normative" statement, can't get your thought)
8. thanks for a good start in 2.7. But there are still such "contains", e.g. 2. Information Model -> list of classes, Permission: "... The Permission may also **include** the Duty  ..." or 2.1.1 Set "... An ODRL Policy of type Set MUST **include** at least one Rule. ..." (my browser shows 59 occurrences of "include" in the IM document, thanks for sorting them out)
9. sorry, the related to does not help much in this case. The list of properties of the Policy Class (still) does not show properties for a target Asset, an assigner Party etc. But that's more an issue as discussed in #202

**Comment by riannella** [comment]
1) RDF is a Model and the ODRL IM is also a Model, but technically there is no "model behind the IM".   They use common terms like Class and Property (which mean the same) but the IM, for example, has "inheritance" with specific meaning, which is different (in some cases) to RDF.
However, the Vocab is where we say...this is how the IM is mapped to RDF(/owl):

> The ODRL Vocabulary and Expression specifies the set of RDF classes, predicates and named entities that are used by the ODRL Information Model [odrl-model]

3) Ok, added Class to sections headings

4) Ok, added Property to section headings

7) I've updated all the list of properties.
But for 0..1 i've used "MAY have none or one"
@sereAbi  please check ;-)

8) I've replaced as many "includes" as i can ;-)

commit 61a597ade0db8ba4fc5e1b5646c80bf1f4879074

**Comment by nitmws** [comment]
@riannella thanks for the many changes - the definitions of properties look much more consistent now, I hope this is also interpreted as better.

Re 1: I'm afraid this is a topic for about 10 years of discussion ;-) 
My maybe very pragmatic view is: if a Model can be mapped and expressed by RDF means it cannot include contradictions to the RDF Model.
