### ISSUE TITLE
Note on Policy Inference

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#201]
@simonstey has provided a [Policy Inference](https://www.w3.org/2016/poe/wiki/Policy_Inference) with a very clear and useful workflow of expanding compact assertions of a policy to a list of atomic permissions and prohibitions.

Pondering how this can be used for checking if a user is permitted/prohibited to take an action on an asset I got aware of a foggy area in such a practical context: the odrl:partOf (in the document also the older odrl:memberOf) relationships.
The key issue is that at the moment of processing a Policy the processor might not know all the partOf_s W3C and of Dataset1.
I think the use case a processor is facing is: a specific user wants to taken an action on a specific asset, this needs to be evaluated. First the processor must find out if a partOf relationship is set between the specific user and the assignee W3C and if the specific asset has a partOf relationship with the target Dataset1. Such partOf relationships will be set in many cases outside a policy and this may cause practical problems.
By that the Inferred column of the Policy Inference paper is richer than it will be for such a "check the permission" use case.
The nice side: less expanded atomic rules will be created.

**Comment by simonstey** [comment]
> I think the use case a processor is facing is: a specific user wants to taken an action on a specific asset, this needs to be evaluated. First the processor must find out if a partOf relationship is set between the specific user and the assignee W3C and if the specific asset has a partOf relationship with the target Dataset1. Such partOf relationships will be set in many cases outside a policy and this may cause practical problems.

what practical problems? if there's no indication about any partOf/memberOf/.. relation, then you simply can't compute any inferences.

For example:
```turtle
# :Alice requests the permission to odrl:play asset :PartA:
<http://example.com/request:01>
    a odrl:Request;
    odrl:permission [
        a odrl:Permission ;
        odrl:target :PartA ;
        odrl:action odrl:play ;        
        odrl:assignee :Alice
    ] .

# :Alice is permitted to odrl:present :Dataset1
<http://example.com/policy:01>
    a odrl:Policy;
    odrl:permission [
        a odrl:Permission ;
        odrl:target :Dataset1 ;
        odrl:action odrl:present;        
        odrl:assignee :Alice
    ] .
```
one way to evaluate such a request is to:  
+ merge it with existing policies and check whether any conflicts arise; if that's the case -> **deny**
+ for each policy, check whether the set of (atomic) rules of the request is a subset of the set of (atomic) rules of the policy ![\forall p \in P : R_{request} \subseteq R_p](https://latex.codecogs.com/gif.latex?\forall&space;p&space;\in&space;P&space;:&space;R_{request}&space;\subseteq&space;R_p); if that's the case -> **grant**
+ otherwise ->  **unknown**

So if we don't know that `odrl:play` is actually a narrower term for `odrl:present` and that `:PartA` is actually a part of `:Dataset1`, the response to Alice's request would simply be **unknown** (or any other default).

**Comment by nitmws** [comment]
@simonstey I see as "practical problem" that the policies on the Policy Inference page look like including all required information for evaluating requests. In practice a Policy will include only W3C as assignee and processing the odr:Request needs to check if ex:Alice has a odrl:partOf relationship with ex:W3C. This requires information beyond the data in an odrl:Agreement with only` odrl:assignee ex:W3C` and `odrl:target ex:Dataset1`. How to evaluate a Request against an Agreement after having all required data is no problem.

**Comment by simonstey** [comment]
> In practice a Policy will include only W3C as assignee and processing the odr:Request needs to check if ex:Alice has a odrl:partOf relationship with ex:W3C. **This requires information beyond the data in an odrl:Agreement with only` odrl:assignee ex:W3C` and `odrl:target ex:Dataset1`.**

as long as those triples reside in the same RDF graph as the policies it's fine. 

btw., you also don't know whether a policy expression actually includes all of its rules.. In RDF, those two serializations are equivalent:

```turtle
<http://example.com/policy:01>
    a odrl:Policy;
    odrl:permission [
        a odrl:Permission ;
        odrl:target :PartA ;
        odrl:action odrl:play ;        
        odrl:assignee :Alice
    ] .

<http://example.com/policy:01>
    a odrl:Policy;
    odrl:prohibition [
        a odrl:Prohibition ;
        odrl:target :Dataset1 ;
        odrl:action odrl:present;        
        odrl:assignee :Alice
    ] .
```
is equivalent to ->
```turtle
<http://example.com/policy:01>
    a odrl:Policy;
    odrl:permission [
        a odrl:Permission ;
        odrl:target :PartA ;
        odrl:action odrl:play ;        
        odrl:assignee :Alice
    ]  ;
    odrl:prohibition [
        a odrl:Prohibition ;
        odrl:target :Dataset1 ;
        odrl:action odrl:present;        
        odrl:assignee :Alice
    ] .
```
so whenever an ODRL processor processes/evaluates/validates policies, it does that based on all information that's available to it at that time. whether that's the rules of a policy or relationships between assets/parties/actions.

**Comment by nitmws** [comment]
> btw., you also don't know whether a policy expression actually includes all of its rules..

Right, this needs to be considered and managed by the provider/publisher of the Policies. This could result in having only a single Permission/Prohibition in Policies and for the evaluation they have to be combined - hm, I'm not aware that the IM tells anything about that case, it defines only inheritance as relationship between Policies.

Further it could be the case that the same Permission/Prohibition (= same asset(s), same target(s), same assigner, same assignee(s), same action(s), same constraints) is in multiple Policies - in such an environment it could help to have ids for the instances of Permission and Prohibition.

(Btw: the policy with the single prohibition above should have <http://example.com/policy:02> as id, I guess.)

**Comment by simonstey** [comment]
> (Btw: the policy with the single prohibition above should have http://example.com/policy:02 as id, I guess.)

no and that's exactly my point (and also kinda @aisaac's in #164). 

In RDF, a policy like:
```turtle
<http://example.com/policy:01>
    a odrl:Policy;
    odrl:permission [
        a odrl:Permission ;
        odrl:target :PartA ;
        odrl:action odrl:play ;        
        odrl:assignee :Alice
    ] ;
	odrl:prohibition [
        a odrl:Prohibition ;
        odrl:target :Dataset1 ;
        odrl:action odrl:present;        
        odrl:assignee :Alice
    ] .
```
is actually just a more readable version of:
```turtle
<http://example.com/policy:01> a odrl:Policy .
<http://example.com/policy:01> odrl:permission _:b1 . 
_:b1 a odrl:Permission .
_:b1 odrl:target :PartA .
_:b1 odrl:action odrl:play .     
_:b1 odrl:assignee :Alice .
<http://example.com/policy:01> odrl:prohibition _:b2 .
_:b2 a odrl:Prohibition .
_:b2 odrl:target :Dataset1 .
_:b2 odrl:action odrl:present .        
_:b2 odrl:assignee :Alice .
```
which can also be represented as:
```turtle
<http://example.com/policy:01>
    a odrl:Policy;
    odrl:permission [
        a odrl:Permission ;
        odrl:target :PartA ;
        odrl:action odrl:play ;        
        odrl:assignee :Alice
    ] .

<http://example.com/policy:01>
    a odrl:Policy;
    odrl:prohibition [
        a odrl:Prohibition ;
        odrl:target :Dataset1 ;
        odrl:action odrl:present;        
        odrl:assignee :Alice
    ] .
```

**Comment by nitmws** [comment]
Sorry, got it: two different statements about the same subject.

**Comment by riannella** [comment]
So what do we do with this issue?

**Comment by nitmws** [comment]
If we would include the content of the Policy Inference into the IM we should add a note that the partOf relationships may be provided by systems managing the assignee persons and not by the system managing the policy data. (I'm aware of the RDF-thinking that each identified node simply exists, regardless of any underlying system. But in practice the issue is: what is included in the JSON object of a policy, a long list of partOf entities (staff of a company, students of a university) or only the identifier of the ....Collection.)

**Comment by riannella** [comment]
I don't think we should include detailed narrative like the Policy Inference wiki page in the IM.
Thats better in the Formal Semantics or Best Practices.

**Comment by nitmws** [comment]
Ok, then the Model label should be replaced by a FormalSemantics and/or BestPractices label.

**Comment by vroddon** [comment]
Can we assume that the [policy inference](https://www.w3.org/2016/poe/wiki/Policy_Inference) has been entirely accepted?

**Comment by riannella** [comment]
Yes, I think that is the general conclusion now that we have added the new properties to the IM.

(Note: the final expanded policy should have close to 100 Rules ??)

**Comment by vroddon** [comment]
@riannella, I am afraid that the policy inferences defined here https://www.w3.org/2016/poe/wiki/Policy_Inference by @simonstey should also be part of the normalization step. 

They can be implemented as SPARQL Update queries (I just added an example of SPARQL Update transformation in the Validation document https://www.w3.org/2016/poe/wiki/Validation). 

The SPARQL queries can be really long.

**Comment by iherman** [comment]
Discussed on the call on 2018-01-15, decided that this issue is not relevant for the BP document (was input for the tests)
