### ISSUE TITLE
IM: upgrade Short-cut Instances of Classes in Policy Rule Composition to a section

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#202]
I refer to the [Information Model](https://w3c.github.io/poe/model/#) (IM) document of 23 June.

Its section [2.7 Policy Rule Composition](https://w3c.github.io/poe/model/#composition) is not only about composing the Rules of a Policy, the region starting with "An ODRL Policy may also declare multiple Assets, ..."  is about adding instances of Asset, Party or Action as properties to the Policy (called "at the Policy level") and about rules for integrating such instances into Permissions and Prohibitions. As this is a very special and important topic it should be upgraded to a section of the IM document. And I suggest to move this section before Policy Rule Composition as short-cuts have implications on Rules.

Further the IM needs a wider and more consistent view on theses so called short-cuts:

* Properties different from the ones currently defined for a Policy Class (uid, permission, prohibition, conflict, inheritAllowed, profile) have different roles a this "policy level":
  * target, assigner, assignee and action are properties which should be added to the existing permission and prohibition Rules of the Policy
  * while constraint properties must not be added to permission or prohibition rules, they may only be referenced by a Compound Constraint in one or more permissions or prohibitions
* As such properties may occur as properties of a Policy the [2.1. Policy Class](https://w3c.github.io/poe/model/#policy) section must include a statement about such occurrences. A basic part of that statement should be that these properties are not a property of the policy, they are only properties of Permissions and Prohibitions of this Policy, placed their as syntactic sugar.
In a short version this statement refers at least to the sections describing the two types of "short-cuts" (in fact constraint properties are not a short-cut).
* As target, assigner, assignee and action may be "direct" properties of a Permission or Prohibition but may occur also as shortcut instances already the sections about the Permission Class and the Prohibition Class should include a statement about that, best with a reference to the Short-cut Instances section for details.
* This item above is also a reason for putting the Short-cut Instances section prior to Policy rule Composition: first the IM must explain that properties may occur at different locations but having the same semantic role and then the Composition section can explain how multiple instances of a property need to be expanded.

**Comment by nitmws** [comment]
Add on: [2.9 Policy Inheritance](https://w3c.github.io/poe/model/#inhertiance) defines how a (child) policy could inherit from a (parent) policy.
What about short-cuts in the parent policy?
*  will target, assigner, assignee and action at the "policy-level" also be replicated to all Permissions/Prohibitions of the child policy?
* may a Compound Constraint in a child policy refer to a constraint residing at the "policy-level" of the parent policy?

**Comment by simonstey** [comment]
> will target, assigner, assignee and action at the "policy-level" also be replicated to all Permissions/Prohibitions of the child policy?

good question.. it depends on whether the parent policy must be expanded before it can inherit its rules.

> may a Compound Constraint in a child policy refer to a constraint residing at the "policy-level" of the parent policy?

if it's not a blank node, why not?

**Comment by nitmws** [comment]
> if it's not a blank node, why not?

The discussion in #193 sounded like the referenced constraint should be in the same policy - next question: should a parent policy be considered as "same policy"?

**Comment by simonstey** [comment]
> The discussion in #193 sounded like the referenced constraint should be in the same policy
```turtle
<http://example.com/policy:parent>
    a odrl:Policy;
    odrl:constraint :c1 ;
    odrl:permission [
        a odrl:Permission ;
        odrl:target :PartA ;
        odrl:action odrl:play ;        
        odrl:assignee :Alice
    ] .

<http://example.com/policy:child>
    a odrl:Policy;
    odrl:inheritFrom <http://example.com/policy:parent> ;
    odrl:prohibition [
        a odrl:Prohibition ;
        odrl:target :Dataset1 ;
        odrl:action odrl:present;        
        odrl:assignee :Alice ; 
        odrl:constraint [
            odrl:leftOperand :c1 ;
            odrl:operator odrl:or ;
            odrl:rightOperand :c1 ;
        ] ;
    ] .

:c1 a odrl:Constraint .
```
?
> should a parent policy be considered as "same policy"?

the parent policy is not the same as the child policy (unless they are owl:sameAs) . they might be equivalent in terms of their semantics though.

**Comment by riannella** [comment]
@nitmws first comments:

The "short-cuts" are related to the  2.7 Policy Rule Composition section in that they explain how you then generate the atomic policies. I've added a subsection and some narrative that the atomic policy is recommended.

I think the key point is that we don't want to promote short-cuts all over the IM document. We want them to produce atomic policies - and the compact ones are just an interim measure.

That is, we don't want to dilute the normative IM with the short-cuts!

re: Inheritance
Step 2 in the Inheritance processing model says include all the policy-level assets, parties, actions.
And Step 3 says - make it atomic..

commit: f3fcf6ee357beee314d79bcead84a6894a6e46a6

**Comment by riannella** [comment]
And perhaps we make the whole section 2.7 non-normative too

**Comment by nitmws** [comment]
@riannella thanks for your considerations, they provide background.
I'm not sure if the approach "make short-cuts non-normative" will work:
* currently only 1. Introduction and 3. ODRL Profiles of the IM are non-normative - both have no impact on classes and their properties
* the e.g. Rule Class defines in the IM that it may have any sub-property of the relation property, this covers non-normative sub-properties defined in the in the [Common Vocabulary](http://w3c.github.io/poe/vocab/#assetRelationsCommon). This way reading the IM an implementer can infer "using the output asset relationship is ok"
* Currently the definition of the Policy Class in the IM does not say anything about using target, assignee, assigner etc (= the short-cuts) as property. An implementer seeing a policy instance using these properties may get confused, which should be avoided.

**I suggest this solution:**
* In the IM add to the list of [Policy Class](http://w3c.github.io/poe/model/#policy) properties this bullet: "Other properties may occur. They are used to provide Constraints referenced by Compound Constraints  or as non-normative short-cuts of Compact Policies and must not be considered as property of the Policy Class." (Links to Compound Constraint and to Compact Policy may be applied.)
* In the [Compact Policy](http://w3c.github.io/poe/model/#composition-compact) define these rules for "collecting" properties applicable to permissions and prohibitions of this Policy (note: this is using a different approach: check the Permission and Prohibition class for properties and include the short-cuts at the Policy-level):
  * For Permissions: a target or assigner or assigner or action or duty property applying to the Permission is a property of the Permission or a property of the Policy. Any of these properties of  a Policy is the same as a property of the Permission.
  * For Prohibitions: a target or assigner or assigner or action or duty property applying to the Prohibition is a property of the Prohibition or a property of the Policy. Any of these properties of  a Policy is the same as a property of the Prohibition.
* This Compact Policy may be declared as non-normative.
* I see no need to add anything to the[ Compound Constraint](http://w3c.github.io/poe/model/#constraint-compound), it shows already how constraint properties at the policy-level are used.

**Comment by riannella** [comment]
I have done the first suggestion above.

But am not sure about what you mean for the second? Are you saying we need reverse rules too?

commit: e0db360d54f174a9d30d9f61320be5a7c54afad7

**Comment by nitmws** [comment]
@riannella thanks for following the first suggestion.

re the second: my general suggested change of the narrative is that the IM only talks about short-cuts where they become effective and that's at the Rule level.
In details:
* [2.7.1 Compact Policy](http://w3c.github.io/poe/model/#composition-compact) currently tells "An ODRL Policy MAY also relate to multiple Assets, Parties, and Actions at the Policy level (not just within a specific Rule)." - which is a contradiction to "... must not be considered as property of the Policy Class." 
* The processing model at the bottom of 2.7.1. talks about how to apply properties at the Policy level to Rules of the Policy. I suggest to replace this by a model in which the Permissions and Prohibitions bring together properties at the local level with properties at the Policy level (see my intro above) - simply said: the model should advise a Rule checking "where are the target(s), assigner(s) ... relevant for me".
* I suggest to **replace the first para by the wording below**:
A target or assigner or assigner or action or duty property of a Permission or Prohibition of a Policy may be shared across multiple rules and in this case such properties may be applied formally as property of the Policy, but not semantically. This is a _short-cut_ method to support more **compact** serialisations. 
The processing model for expanding short-cuts used by Permissions or Prohibitions is:
  * For Permissions: a target or assigner or assigner or action or duty property applying to the Permission is a property of the Permission or a formal property of the Policy. Any of these shared formal properties of a Policy is semantically the same as a property of the Permission.
  * For Prohibitions: a target or assigner or assigner or action _or duty (??)_ property applying to the Prohibition is a property of the Prohibition or a formal property of the Policy. Any of these shared formal properties of a Policy is semantically the same as a property of the Prohibition.
* {para 1 continued, unindented}
Further follow the processing model to create _atomic_ Rules in the Policy (defined in the previous section).
It is RECOMMENDED that compact ODRL Policies be expanded to atomic Policies when being processed for conformance or exchanged for interoperability, to reflect the normative ODRL Information Model.
* Note on "or duty (??)" in the Prohibition rule: this will depend on the outcome of the discussion about the use of duty properties at the policy level (#162). By my current overview a Duty at the Policy-level is should be allowed only for the Set subclass. Will this trigger the same processing model as for Permission and Duty?
* {wording above Example 26} The example below shows such shared properties applied to a Policy
* {wording above Example 27} The example below shows how these shared properties are expanded to the Permissions of the Policy following the rule above:
* No wording below Example 27

**Comment by riannella** [comment]
The short-cuts can be used by any relation/function sub-property (not just target/assignee/assigner)

And I don't think we add duty now....

So the processing model you suggest is to look at each Rule first, then see if there are any relevant policy-level properties, if so, then add them to the Rule ?

**Comment by nitmws** [comment]
Re short-cuts: I've set a focus on the properties defined by the (core) ODRL. If liked by all we could open that feature to all sub-properties of relation and function. (Practical view: if a property `abc1:klm4711 <http://example.com/entity991818>` resides at the policy level: how to find out if this is a sub-property of relation or function? Processing this needs more information than the raw serialisation.)

Re processing. Yes, that's my approach: neglect these properties as property of the Policy Class, search for the properties of a Rule and include properties at the policy level into that. This should be expressed by my suggested language above - has to be adapted if we open the short-cuts to any sub-property of relation/function. I would prefer to name explicitly the sub-properties defined by the core ODRL (as it is done above) and to to add "and other sub-properties of function or relation".

**Comment by riannella** [comment]
1) as per the ODRL Profile rules, abc:klm4711 would have to be defined as a sub-property of function or relation to be used as a part of an ODRL policy.

2) Updated:  4570845f9dc92486473049cad86fe4561bedb7e6

**Comment by nitmws** [comment]
@riannella re your update:
* 2.7.1 first sentence:
currently: "An ODRL Policy may share properties with its Rules."
That's ambiguous as by strict reading this makes the properties an active property of the Policy ("properties shared by a Policy with its Rules"). 
I suggest: "An ODRL Policy may hold properties which are shared among its Rules."
* re item 1 above: I suggest to add that requirement to the definition of relation and function: 
"Any sub-properties of relation (such as target), _they have to be defined by (core?) ODRL or an ODRL Profile_."
This would clarify where a receiver of an ODRL Policy has to look to find the definition of a sub-property of relation or function. (... this would apply also to profile-specific actions, operators etc.)

**Comment by riannella** [comment]
Updated commit: 1821b610d1d0b47d75fc4a3c91057a6bab78dd0b

**Comment by simonstey** [comment]
> An ODRL Policy may hold properties which are shared amongst its Rules. Such properties may be applied formally as property Rules but not semantically of the Policy.

what? I've no idea what any of this means..

> Any sub-properties of relation (such as target) defined in the ODRL Common Vocabulary [odrl-vocab] and ODRL Profiles. 

but `odrl:target` isn't part of the common vocab

**Comment by nitmws** [comment]
I share these concerns. 
What about "An ODRL Policy may hold properties which are used by its Rules, semantically they do not apply to the Policy."
Re the second issue: do we have now an agreed term for the normative part of ODRL - maybe "core ODRL"? (I've lost track of this discussion.)

**Comment by riannella** [comment]
1) I have updated the text

2) I have removed the "defined in..." as the property MUST already have been defined in the Core/Common/Profile to be used in an ODRL Policy anyway...

commit 5c8453943d92e2d09b4a8c7039e5075f45bd7776

**Comment by nitmws** [comment]
re 1: thanks, a typo issue: "... (such as assigner." The closing ) bracket is missing.
re 2: the approach sounds ok - is this explicitly defined anywhere or just inferred from the IM as a whole? Further this raises an interesting question: if a profile does not want to cover an action defined in the Common Vocabulary: does it have to exclude it explicitly? Maybe better to discuss this in another Github Issue.

**Comment by riannella** [comment]
1) fixed

2) I think a profile would explicitly list all Common vocab terms it wants to support.

**Comment by nitmws** [comment]
re 2: yes, IPTC has on its agenda to review the Common Vocab terms for adoption by RightsML. But I think the union of the two sets "core ODRL-defined properties" and "properties defined by the profile applied to this Policy" has less elements than the union of the three sets "core ODRL-defined properties", "properties defined by the profile applied to this Policy" and "ODRL Common Vocabulary-defined properties". And actually only the first union should be valid for an ODRL Policy. In other words: the Common Vocabulary may have properties which are not adopted by the profile applied to a policy - and makes these properties unknown to the receiver of the policy.
I've started a discussion about that as #210
