### ISSUE TITLE
Constraint Narrative

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#203]
> Constraints are used to express limitations, restrictions, or interpretations that are applied to these classes.

that's wrong, they are applied to instances of those classes not on the classes themselves -> remove entire sentence 

> Constraints can be represented as Atomic Constraints - in which the left and right operands are compared - or as Compound Constraints in which the left and right operands are existing Atomic Constraints, which are also compared. 

according to that, each compound constraint is also an atomic constraint

> A constraint is evaluated as a kind of "black box" from an external system 

no.. a constraint is evaluated as the constraint it is, it's the constraint evaluation that we treat as a black box.

> (e.g., any kind of reasoning engine), 

what? -> remove

> and the outcome of this evaluation is of the form true (if the constraint is satisfied) or false (if the constraint is not satisfied).

remove (it's also kinda weirdly phrased)

> ODRL Processors must check the satisfiability all constraints at the time of processing the relevant Action, Asset, and Party.

checking **satisfiability of** a constraint != checking whether a constraint **is satisfied** under a given interpretation ->

1. A OR B is satisfiable; there are interpretations that make A OR B true (e.g., whenever I(A) = 1 or I(B) = 1)
2. A OR B is not satisfied with I(A) = I(B) = 0

> If the constraint is satisfied then the action becomes valid for the enclosing Rule. If the constraint is not satisfied, then the action is not valid for the enclosing Rule.

+ what's the definition of a rule with an "invalid" action? 
+ what does that mean for parties/assets? 

> When multiple Constraints apply to the same Rule they are interpreted as conjunction. A Rule becomes effective if all of its Constraints are satisfied.

what if multiple constraints apply to the same party-/assetcollection?

**Comment by riannella** [comment]
Updated

commit: 17fcf93d84824fa2ee5d145e61ceae7467af3cfc

**Comment by simonstey** [comment]
> Parties and Assets become effective ~~is~~ if all of the Constraints on Party/Asset Collections are satisfied. 

what?
1. what's the definition of a party/asset that's not "in effect"?
2. if **all** of the constraints on p/a collections are satisfied? even those of completely unrelated collections?

**Comment by riannella** [comment]
1) "effect" only applies to Asset/PartyCollections that have constraints.
(single) Asset/Parties are just that.

So not  "in effect" means the constraint has not been satisfied.

2) better: 

> if all of **their** Constraints on the **source** Party/Asset Collections are satisfied. 

 ?

**Comment by simonstey** [comment]
>"effect" only applies to Asset/PartyCollections that have constraints.
(single) Asset/Parties are just that.

what's the definition of a ~~party/asset~~ Asset/PartyCollection that's not "in effect"?

> So not "in effect" means the constraint has not been satisfied.

1. no, if constraints of a rule aren't satisfied -> the rule is not in effect
if a rule is not in effect it means that this rule is "ignored" by further processing steps
2. this still doesn't answer my question though.. what does it mean for a ..collection to be "in effect/not in effect"?

constraints attached to p/a collections don't regulate whether their collections are in effect or not, but define subsets of their collections to which respective rules apply.

**Comment by simonstey** [comment]
i.e. instead of performing an expansion to atomic rules for **all** member of a p/a collection as outlined in https://www.w3.org/2016/poe/wiki/Policy_Inference#Semantics_of_Party_Relations, it's done for those that satisfy all constraints only.

**Comment by riannella** [comment]
> this still doesn't answer my question though.. what does it mean for a ..collection to be "in effect/not in effect"?

The "collection" is never "in or not in effect", but the Assets or Parties that satisfy the constraint are in/not in effect (ie they will be the effective targets/assignee/r's for the rule)

**Comment by simonstey** [comment]
> The "collection" is never "in or not in effect", ...

👍 
> ... but the Assets or Parties that satisfy the constraint are in/not in effect ...

👎 
> ... (ie they will be the effective targets/assignee/r's for the rule)

👍 

--> as I said earlier, constraints attached to p/a collections don't regulate whether their collections are in effect or not **(+ or whether members of those collections are generally in effect or not)**, but define subsets of those collections **(+ consisting of members that satisfy the constraints)** to which respective rules apply. 

-------

how would any **individual** asset be able to satisfy the asset constraint in [Example 21](https://w3c.github.io/poe/model/#constraint-asset):
>  The target also has a constraint that specifies further context on the characteristics of the AssetCollection items. In this case, the target Assets will be no more than 50 resources from the media catalogue, and each of those may be printed.

isn't that a constraint on the asset collection itself (i.e. have at most 50 members)?

**Comment by riannella** [comment]
I think we are saying the same thing...

When I say "but the Assets or Parties that satisfy the constraint are in/not in effect"
There "Assets or Parties" are the same members you mention in "consisting of members that satisfy the constraints" ???

Example 21 of course depends on what ex:set is defined as.
It was an attempt to address this requirement: http://w3c.github.io/poe/ucr/#POE.UC.17
Perhaps it is incorrect?

**Comment by riannella** [comment]
Perhaps we need to add "members..." to the narrative ?

**Comment by simonstey** [comment]
> Example 21 of course depends on what ex:set is defined as.
It was an attempt to address this requirement: http://w3c.github.io/poe/ucr/#POE.UC.17
Perhaps it is incorrect?

currently, constraints on collections are not evaluated on the collections themselves but on the members of their `odrl:source` collection only. the constraint in Example 21, however, is a constraint on the asset collection itself rather then one on its members 

-> as no member is able to satisfy such a constraint, the target asset collection is always empty

**Comment by riannella** [comment]
Sp perhaps for this example 21, we actually do use "uid" and not "source" ?

**Comment by riannella** [comment]
Updated the narrative to include _members/subset_.
Updated the example for Asset Constraint.

commit: b6e99c415b86f65d49f7b5f7a4bf1bfb5405873e
