### ISSUE TITLE
Remove inheritAllowed functionality & single inheritance restriction

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#204]
**inheritAllowed**: unless someone comes up with a convincing use case that would justify keeping it.

**single inheritance**: what's the reason for allowing single inheritance only?

**Comment by riannella** [comment]
I'm ok to remove inheritAllowed.
others?

RE: single inheritance - the main reason was to "reduce" complexity.
Is there a use case for it?

**Comment by simonstey** [comment]
> RE: single inheritance - the main reason was to "reduce" complexity.
Is there a use case for it?

<img src="https://user-images.githubusercontent.com/10495449/27722155-ef3f37de-5d65-11e7-8d68-bc868b574737.png" alt="License Merge" width="200px" />

```turtle
<http://example.com/license:CC-BY>
    a odrl:Policy;
    odrl:permission :CCperm1, :CCperm2 ;
    odrl:prohibition :CCproh1 ;
    odrl:duty :CCduty1 .

<http://example.com/license:ODbL>
    a odrl:Policy;
    odrl:permission :ODperm1 ;
    odrl:prohibition :ODproh1, :ODproh2 ;
    odrl:duty :ODduty1, :ODduty2 .

<http://example.com/license:LicenseX>
    a odrl:Policy;
    odrl:inheritFrom <http://example.com/license:CC-BY>, 
                     <http://example.com/license:ODbL> ;
    odrl:permission :CCperm1, :CCperm2, :ODperm1 ; # inherited
    odrl:prohibition :CCproh1, :ODproh1, :ODproh2 ; # inherited
    odrl:duty :CCduty1, :ODduty1, :ODduty2 . # inherited
```

**Comment by benedictws** [comment]
Surely multiple inheritance would only be a problem if we were to inherit state (aka odrl:status). But this is explicitly disallowed.

So perhaps we can drop the single inheritance restriction.

**Comment by riannella** [comment]
Agreed to both changes (WG teleconf 3 July 2017).

**Comment by riannella** [comment]
Changes made: c4c248126cc92ba699c71aaf7486da2f987af883
