### ISSUE TITLE
EXAMPLE 19 makes no sense

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#205]
https://w3c.github.io/poe/model/#constraint-compound: 
> Example Use Case:The Policy below shows a Permission to play the target asset that can either be a maximum of 100 times, or unlimited play until the end of 2017 but not both.

```json
{
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Offer",
    "uid": "http://example.com/policy:88",
    "permission": [{
        "target": "http://example.com/book/1999.mp3",
        "assigner": "http://example.com/org/paisley-park",
        "action": "play",
        "constraint": [{
                "leftOperand": "http://example.com/policy:88/C1",
                "operator": "xor",
                "rightOperand": "http://example.com/policy:88/C2"
            }],
    }],
   "constraint": [{
       "uid": "http://example.com/policy:88/C1",
       "leftOperand": "count",
       "operator": "lteq",
       "rightOperand": "100"
   },
   {
       "uid": "http://example.com/policy:88/C2",
       "leftOperand": "dateTime",
       "operator": "lteq",
       "rightOperand": "2017-12-31"
   }]
}  
```
what's the intended semantics of this permission? C1 is satisfied from the very beginning, so the permission is not in effect before 1.1.2018 and can then be exercised 100 times.

**Comment by riannella** [comment]
A **choice** needs to be made between C1 and C2 ("xor").
(and we make no assumptions on how that is done)

So an ODRL Evaluator would not look at the atomic constraints in isolation of the semantics of the (logical) operator.

**Comment by simonstey** [comment]
> **A choice needs to be made** between C1 and C2 ("xor").
(and we make no assumptions on how that is done)

but that's not how xor works..
http://mathworld.wolfram.com/XOR.html: 
> A connective in logic known as the "exclusive or," or exclusive disjunction. **It yields true if exactly one (but not both) of two conditions is true.** 

A | B | A xor B
:---: | :---: | :---:
0 | 0 | 0
1 | 0 | 1
0 | 1 | 1
1 | 1 | 0

> If the operator is xor then ~~at~~ **only one** of the Atomic Constraints (in the left or right operands) **MUST be satisfied** for the entire Compound Constraint to be satisfied.

Hence, to check whether an XOR compound constraint is satisfied **both** of its atomic constraints have to be validated, otherwise you don't know whether **only one** (but not both) of its atomic constraints is satisfied. 

Even though we don't specify how the validation of atomic constraints has to be done, we do know that if validating atomic constraint c1 at time t returns true, the condition specified by c1 holds at time t.
As such, following permission is only effective if either `<http://example.com/policy:88/C1>` or `<http://example.com/policy:88/C2>` are satisfied ->
1. it was exercised <= 100 times and today() > 2017-12-31
2. it was exercised > 100 times and today() <= 2017-12-31  

But it is not in effect if `<http://example.com/policy:88/C1>` and `<http://example.com/policy:88/C2>` are both satisfied or unsatisfied at the same time -> 
1. it was exercised <= 100 times and today() <= 2017-12-31
2. it was exercised > 100 times and today() > 2017-12-31  
```turtle
<http://example.com/policy:88>
    a odrl:Offer ;
    odrl:permission [ 
        odrl:target <http://example.com/book/1999.mp3> ;
        odrl:assigner <http://example.com/org/paisley-park> ;
        odrl:action odrl:play ;
        odrl:constraint [ 
            odrl:leftOperand <http://example.com/policy:88/C1> ;
            odrl:operator odrl:xor ;
            odrl:rightOperand <http://example.com/policy:88/C2> ;                                                     
        ]
    ] .

<http://example.com/policy:88/C1> 
    a odrl:Constraint ;
    odrl:leftOperand odrl:count ;
    odrl:operator odrl:lteq ;                              
    odrl:rightOperand "100" .

<http://example.com/policy:88/C2> 
    a odrl:Constraint ;
    odrl:leftOperand odrl:dateTime ;
    odrl:operator odrl:lteq ;                              
    odrl:rightOperand "2017-12-31" .
```
------------------

**Comment by riannella** [comment]
Hmm...so its a poor example ;-))

What if C1 was "purpose=education" and C2 was "meteredTime=P60M" ?

**Comment by simonstey** [comment]
> What if C1 was "purpose=education" and C2 was "meteredTime=P60M" ?

I don't understand the example given in https://w3c.github.io/poe/vocab/#term-meteredTime: 
> meteredTime eq P60M indicates that the action can be exercised for an accumulated period of 60 Minutes. **This means that the action can be ex~~p~~ercised for 5 minutes each day over 12 days.,** 

but i could also "consume" those 60min all at once, 1min/day over 60 days, etc. right? if that's the case -> s/can/could e.g./
> Only the **eq** operator SHOULD be used.

when's a meteredTime constraint considered to be satisfied then? if I have exercised the action for < 60min it's not = 60min so it's unsatisfied?

----------
anyway.. 
>  What if C1 was "purpose=education" and C2 was "meteredTime<=P60M" ?

assuming that a meteredTime constraint with <=  P60M is considered to be satisfied if constrained action wasn't exercised for > 60min, then a respective permission is in effect if:
1. the purpose != education for the first 60min the action is exercised
2. the purpose == education afterwards.

it is not in effect if the purpose == education and the action wasn't already exercised for more than 60min.

**Comment by simonstey** [comment]
if you want to state that unless your purpose == education, you can exercise the action for not more than 60min, you could use an OR:

C1 | C2 | C1 or C2
:---: | :---: | :---:
0 | 0 | 0
1 | 0 | 1
0 | 1 | 1
1 | 1 | 1

If your purpose == education ( I(C1) = 1 ), then I don't care how long you exercise the action 
If you've exercised the action for <= 60min ( I(C2) = 1 ), then the purpose doesn't matter.

If you've exercised the action for > 60min ( I(C2) = 0 ), then the purpose must be education ( I(C1) = 1 ).

**Comment by riannella** [comment]
Yes, meteredTime is the accumulated time to use the asset - and it can be broken down into as many parts as and as much elapsed time as you like.

(lt/lteq would be better as well for this time-based constraints....fix that...)

**Comment by riannella** [comment]
Now I remember why I didn't like "constraints on constraints" :-}

**Comment by riannella** [comment]
It probably makes more "semantic" sense to use the same left operand.
Such as:
 C1: media = "print"
 C2: media = "online"

**Comment by simonstey** [comment]
> It probably makes more "semantic" sense to use the same left operand.
Such as:
C1: media = "print"
C2: media = "online"

only if you want to explicitly rule out cases where media is both print and online, otherwise you would use again OR, e.g.:

```turtle
<http://example.com/policy:88>
    a odrl:Offer ;
    # if you pay 5 euro, we allow media only to be either print or online, but not both
    odrl:permission [ 
        odrl:target <http://example.com/book/1999.mp3> ;
        odrl:assigner <http://example.com/org/paisley-park> ;
        odrl:action odrl:play ;
        odrl:duty <pay5euro> ; 
        odrl:constraint [ 
            odrl:leftOperand <http://example.com/policy:88/C1> ;
            odrl:operator odrl:xor ; 
            odrl:rightOperand <http://example.com/policy:88/C2> ;                                                     
        ]
    ] ;
   # if you pay 8 euro, we allow media to be both print and online
   odrl:permission [ 
        odrl:target <http://example.com/book/1999.mp3> ;
        odrl:assigner <http://example.com/org/paisley-park> ;
        odrl:action odrl:play ;
        odrl:duty <pay8euro> ; 
        odrl:constraint [ 
            odrl:leftOperand <http://example.com/policy:88/C1> ;
            odrl:operator odrl:or ;
            odrl:rightOperand <http://example.com/policy:88/C2> ;                                                     
        ]
    ] .

**Comment by riannella** [comment]
> only if you want to explicitly rule out cases where media is both print and online

For the example use case in the IM, I think thats a better example (to show Compound Constraints)

For the second example above, the single atomic constraint could suffice too:
```
 odrl:constraint [ 
            odrl:leftOperand  odrl:media ;
            odrl:operator odrl:isAnyOf; 
            odrl:rightOperand "print, online" ;   
```

**Comment by riannella** [comment]
Updated example 19

commit b0db98a2d6c0cd7a026bd078cc57ce03e3f7d7fe

**Comment by simonstey** [comment]
>For the second example above, the single atomic constraint could suffice too:
>```
> odrl:constraint [ 
>            odrl:leftOperand  odrl:media ;
>            odrl:operator odrl:isAnyOf; 
>            odrl:rightOperand "print, online" ;   
>```

true.. I wouldn't use a single string as `odrl:rightOperand` to represent a collection though..

[better](https://www.w3.org/TR/turtle/#collections) -> 
```
 odrl:constraint [ 
            odrl:leftOperand  odrl:media ;
            odrl:operator odrl:isAnyOf ; 
            odrl:rightOperand ( "print" "online" ) ; 
]   
```
