### ISSUE TITLE
Clarify contradictory values of conflict attribute

### ISSUE THREAD

**Issue by riannella** [w3c/poe#21]
Need to clarify conflicting values of the conflict attribute. That is, one policy says perm and the other prohibit.

**Comment by simonstey** [comment]
Where we should also consider different types of dependencies between actions (see [1]).

| :policy1 | :policy2 | Type of Dependency |
| --- | --- | --- |
| odrl:permission **odrl:read** | odrl:prohibition **odrl:read** | direct (read==read) |
| odrl:permission **odrl:share** | odrl:prohibition **odrl:distribute** | implicit (sharing implies distributing) |
| odrl:permission **odrl:use** | odrl:prohibition **odrl:display** | explicit (use is more general than display) |

[1] http://link.springer.com/chapter/10.1007%2F978-3-319-21542-6_23

**Comment by sereAbi** [comment]
I added a new example that recalls some of the elements Simon highlighted above. I didn't provide any solution in the example, as I believe we need first to agree on it. 

To me, in case of direct dependency, and conflict=perm/conflict=prohibits for the two policies, the merging results into an invalid policy. 

In case of explicit dependency and conflict=perm/conflict=prohibits, then they can coexist, having in the merging policy the permission use and the prohibition display. But what about the conflict values here?

The case of implicit dependencies needs to be dealt with by including in the vocabulary the fact the e.g., sharing implies distributing. Again, what about the the conflict values?

Establishing a fix default value in case of merging of policies with conflicting conflict values is difficult. In general, prohibitions should have the priority over permissions.

**Comment by riannella** [comment]
I think the only option we have (for Example 3) is to say that if there is discrepancy between the two conflict values, then the result must be an invalid Policy

**Comment by riannella** [comment]
@simonstey Looking at your table above, how does that impact how the conflict attribute should be processed?

**Comment by sereAbi** [comment]
@riannella I agree, the easiest solution is to say that the resulting merging policy is invalid.

**Comment by riannella** [comment]
I've updated section 3.1.1
