### ISSUE TITLE
Reviews of ODRL Vocabulary ...  - Editor's Draft 3 August 2017

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#216]
Issue (= place for) for posting review comments about this ODRL Vocabulary and Expressions document

**Comment by nitmws** [comment]
Re Common Vocabulary - https://w3c.github.io/poe/vocab/#vocab-common

This section 4 reflects now that it holds terms which may be used by ODRL profiles.
In other words: these are terms which have been (well) defined by ODRL 2.1 and can still be used - the only required step is to adopt such a term for a profile.
But why are Creative Commons terms part of this Common Vocabulary? These terms are already defined by Creative Commons and don't need to be defined again. And a profile could adopt a mix of ODRL Common Vocab and Creative Commons terms as it likes.

Having a look into the ODRL22.ttl of 3 August shows:
```
<http://www.w3.org/ns/odrl/2/#actions>
    a skos:Collection ;
    skos:prefLabel "Actions for Rules"@en ;
    skos:member :use ;
    skos:member :transfer .

<http://www.w3.org/ns/odrl/2/#actionsCommon>
    a skos:Collection ;
    skos:prefLabel "Actions for Rules"@en ;
    skos:member :acceptTracking ;
    skos:member :aggregate ;
...
```  
The IRI of these vocabs make only a minimal distinction between Core and Common and the prefLabel no distinction at all.
As the difference between Core and Common is essential this should be reflected in the TTL too, e.g.
```
<http://www.w3.org/ns/odrl/2/#actionsCore>
    a skos:Collection ;
    skos:prefLabel "Actions of the ODRL Information Model for Rules"@en ;
    skos:member :use ;
    skos:member :transfer .

<http://www.w3.org/ns/odrl/2/#actionsCommon>
    a skos:Collection ;
    skos:prefLabel "Non-normative common actions for Rules which may be adopted by ODRL profiles."@en ;
    skos:member :acceptTracking ;
    skos:member :aggregate ;
...
```  

The same applies to Policy Subclasses, Party Function, Left Operands, Right Operands.

<hr>

** Re 3.13.1 Constraint 
Now: A boolean expression that refines the applicability of a Rule.
Should be: A boolean expression that refines the applicability of a Rule, or Party/Asset Collection.

** Re 3.13.2 Has Constraint
Now: Constraints applied to a Rule
Should be: Constraints applied to a Rule, or Party/Asset Collection
Now: One or more Constraints may be applied to a Rule.
Should be: One or more Constraints may be applied.

** Re 3.14.1 Logical Constraint
Now: A logical expression that refines the applicability of a Rule.
Issue: may a Logical Constraint be applied to Party/Asset Collection too? (The IM says no clear yes or no)

** Re 3.14.2 Operand
Sub-properties: andSequence is missing.

** Re 3.16.4 And Sequence
Class is defined as Operator - should be the Logical Constraint Operand 3.14.2

**Comment by riannella** [comment]
RE: But why are Creative Commons terms part of this Common Vocabulary

See #158 for full details.
- Since we deprecated terms in ODRL and recommended CC terms instead (so CC does appear in the spec anyway at http://w3c.github.io/poe/vocab/#deprecate)
- It may help build closer bridges to this community (a lot of users...)
(note: we are not defining them, just listing them as re-usable actions)


RE: As the difference between Core and Common is essential this should be reflected in the TTL too

All the common terms have:
  skos:scopeNote "Non-Normative"@en .

The spec is normative - so what is written there covers all the terms in that section (eg: http://w3c.github.io/poe/vocab/#vocab-common) 


Re 3.13.1 Constraint: fixed

Re 3.13.2 Has Constraint: fixed

Re 3.14.1 Logical Constraint: Yes, can be applied to asset/party collections

Re 3.14.2 Operand: fixed

Re 3.16.4 And Sequence: fixed

**Comment by nitmws** [comment]
Re Core Vocabulary and Common Vocabulary:
Differentiating them could quite easily be done by the HTML rendition at http://w3c.github.io/poe/vocab
But doing that in the Ontology (Turtle serialisation) is harder:
* in HTML the full section 4 is earmarked as "non-normative"
* in the TTL only the Common Vocabulary terms show this earmark, but not the Collections, e.g. <http://www.w3.org/ns/odrl/2/#constraintLeftOperandCommon>
* That the main reason for all the Collections is to support the automated rendering as HTML is invisible to most people.
* I suggest to add at least to the Collections of Common Vocabulary terms the earmark "non-normative".
* ... a big help would be to add the earmark "normative" to the other terms/concepts.

**Comment by nitmws** [comment]
Re Section 5 Vocabulary Expression
Looking at the TOC in the left sidebar shows as items
* "5. Vocabulary Expression"
* "5.1 XML Encoding"

The reader unfamiliar with ODRL details will assume: it can only be XML-serialized.

I suggest
* to add right below the 5. header a "5.1 Ontology and JSON-LD" header
* to change the now 5.2 header to "XML Serialization" - as we talk about "alternative seralization syntaxes" at the bottom of the new section 5.1

**Comment by riannella** [comment]
Changes made
