### ISSUE TITLE
ODRL Evaluator review - IM of 11 August 2017

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#217]
Having a look into the ODRL Evaluator section of the IM - http://w3c.github.io/poe/model/#odre - I noticed:
* it defines stati for Rules and Constraint
  * Rule: "in effect" or "not in effect"
  * Constraint: "satisfied" or "not satisfied"
  * implicitly for a Policy: "no rule in effect" or "one or more rules in effect"
  * (**it would be of help to have the stati if Rules and Constraints - and maybe also Policy - shown in the same way: in red with a special font**)
* ... therefore the requested output of the status of a Rule should be:
Permission to play http://example.com/asset:9898.movie: **in effect** (the same for the other sample results)
* The sub-section about evaluating Constraints claim that in the case of not being able to determine satisfied|not satisfied the status should be "not known". **If "not known" is an expected status it must be added to the list of possible Constraint stati in the first para.**
* ... **and it must be defined what happens to evaluating a Rule with Constraints of status "not known"**!
* A general issue: **the IM does not define what exactly a conflict is** but uses this term currently 45 times, quite frequently.
E.g. something like (in 1.3 Terminology ?) "**Conflict - A conflict is raised inside a Policy if assertions of Permission(s) and Prohibition(s) contradict each other.** _This could be e.g. a permission of action, assigner and assignee and a prohibition of the same action, assigner and assignee or if the action of the prohibition is the target of the includedIn relationship of the action of the permission._
(Note on the example part: conflicts could be much more complex - does a simple example obfuscate that or does it help?)
* conflicts - part 2: the definition of 2.10 Policy Conflict Strategy sets a specific status of a Policy: "invalid". So a Policy could be invalid due to syntax errors and due to contradictions at the semantic level - confusing. 
I suggest to change the definition of the "invalid" value to "**invalid: the entire Policy is set to the status of no Rules in effect if any conflict is detected.**"
* re Example 14: the shown **final output should be**:
http://example.com/MyPix:55 grants Permission to http://example.com/assignee:55 to display http://example.com/photoAlbum:55: in effect
http://example.com/MyPix:55 Prohibits http://example.com/assignee:55 from Archiving http://example.com/photoAlbum:55: not in effect

**Comment by riannella** [comment]
I think this section is being completely re-written by Ben.
