### ISSUE TITLE
wording of cardinality restrictions

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#218]
> A Rule MUST have one action property for Action.

it's not about the properties, it's about their values..

**bad/wrong:**
> A Rule MUST have one action property for Action.

> A Duty MAY have none or one consequence properties for Duty.

**better:**
> A Rule MUST have at least one value for `odrl:action`. Each value of `odrl:action` MUST be of type `odrl:Action`.

> A Duty MUST have at most one value for `odrl:consequence`. Each value of `odrl:consequence` MUST be of type `odrl:Duty`.

**Comment by riannella** [comment]
@simonstey (to be clear) are you saying this for every point in the document that mentions a property definition?

So where we say:

> A Policy may have none, one, or many inheritFrom properties to identify the parent Policy from which this child Policy inherits from.

it should be:

> A Policy MAY have none, one, or many values for the inheritFrom property to identify the parent Policy from which this child Policy inherits from. Each value of inheritFrom MUST be of type Policy.

Are you also saying we start to use the "odrl:" prefix throughout the document?

**Comment by riannella** [comment]
I suppose an interesting point is; if a thing has a property with no value, does it actually have that property ??

Does this permission have a target, assigner, action:

```
    "permission": [{
            "target": "",
            "assigner": "",
            "action": ""
     }]
```

**Comment by simonstey** [comment]
> I suppose an interesting point is; if a thing has a property with no value, does it actually have that property ??

that's not valid rdf though

**Comment by riannella** [comment]
So you can't have a property without a value?

**Comment by simonstey** [comment]
> So you can't have a property without a value?

no, each triple consists of a subject, predicate, and object.

**Comment by riannella** [comment]
Yes, ok...but I am not clear as to then what the difference is between:

A Rule MUST have one action property
A Rule MUST have one value for the action property

**Comment by nitmws** [comment]
In #215 I discussed the same, I build on that posting:

In RDF terms a cardinality defines how many times assertions with RDF triples using the same subject and predicate (property) but different objects (values) may occur. (Note: the term "property" for such a use of predicate was coined by RDF Schema https://www.w3.org/TR/rdf-schema/#ch_properties)

Example: the subject is a Permission rule, the predicate is odrl:action and one object or more than one objects are applied:
```
<http://example.org/permission:007>
    odrl:action <http://www.w3.org/ns/odrl/2/aggregate> . 

# above: occurrence = 1
# this is covered by the cardinality variants of odrl:action 
#     "one", "none or one", "none, one, or more", "one, or more"

<http://example.org/permission:007> odrl:action <http://www.w3.org/ns/odrl/2/aggregate> .  
<http://example.org/permission:007> odrl:action <http://www.w3.org/ns/odrl/2/digitize>  .  

# above: occurrence = 2
# covered by the cardinality variants of odrl:action "none, one, or more", "one, or more"

# this is the Turtle short form of the example above:
<http://example.org/permission:007>
    odrl:action <http://www.w3.org/ns/odrl/2/aggregate>, <http://www.w3.org/ns/odrl/2/digitize>  .  
```

The tricky thing is how to write down free-text cardinality statements:
* re subject: this is the persistent thing. This relates to "The XYZ Class (= the subject) has these properties ...." 
* re predicate/property: as the RDF example above shows in atomic RDF this predicate/property may really appear multiple times! And each time it is associated with a different object/value. Only the Turtle syntax may simplify that to a singe occurrence of the property, but this is a syntax issue and not an RDF issue. On the other hand a statement "XYZ Class may have many abc properties ..." may let people guess that the "many abc properties" may be different in some way ... (I suggested this in #215 but agree this misinterpretation may be a result.)
* re object/value: this is the part of the RDF triple which MUST be different in each one of the assertions.

My suggestion:
* The example "A Policy may have none, one, or many inheritFrom **properties ...**" is not completely wrong as none to many times an RDF triple with odrl:inherit from a predicate may appear.
* But _more bullet proof_ is "A Policy may have none, one, or many inheritFrom **property values  ...**" = making "property value(s)" a term.
This tells what will appear multiple times even in a simplified syntax - and inserting "values" is only a small and less error prone edit. (We have maaaany cardinality statements in the IM.)
* Frankly I prefer this over "... having ... values for the inheritFrom property ..." as this sounds like "the property exists always, the cardinality defines how many values are associated with it" and this may result in what @simonstey classified as bad: `"action": ""` _is invalid RDF_.

**Comment by riannella** [comment]
I have updated all the property references with "...value" and added "type of..." as well.

I have also updated the IM model figure to now include **all** Classes !

Please let me know your thoughts asap...

**Comment by nitmws** [comment]
The inserted "... value" looks ok.

The "type of ..." wording is a good approach to underline what in the ODRL ontology is the Range.
Having a look at the 17 August IM version I noticed:
* not all properties have a "type of" yet. Example: `conflict `in the Policy Class --> type of ConflictTerm.
* the term of the type should be a singular. Example Set Class: "... value of type Rules" --> "... value of type Rule"

**Comment by vroddon** [comment]
Excellent!
Some of the properties were missing in the previous version, like inheritFrom. 

Having a systematic (but not fully complete, e.g. "target" is not there) vision of the model is great, but perhaps additional simplified figures can be made.

If I closed my eyes and I imaged I knew nothing about ODRL, I only would wonder about the terms "relation" and "function" (much interchangeable words which are rather unspecific). Instead, I would like to see "target" and "assigner / assignee". Also, in such a didactic-figure, I would use colours, much like in ODRL1.1. Thus, every "constraint-related" might have one colour, rule&subclasses another colour and so on.

**Comment by riannella** [comment]
@nitmws fixed

**Comment by riannella** [comment]
@vroddon added terms (and removed Figure 2)

**Comment by riannella** [comment]
@vroddon What about these colours:
![odrl-model](https://user-images.githubusercontent.com/13191615/29440157-ea166b8a-8405-11e7-8d22-b92a6fbd8994.png)

**Comment by vroddon** [comment]
Awesome! This looks beautiful!
