### ISSUE TITLE
Definition of ODRL

### ISSUE THREAD

**Issue by vroddon** [w3c/poe#219]
The current Information Model does not define what ODRL is. The spec starts (see http://w3c.github.io/poe/model/) as follows:

> The Open Digital Rights Language (ODRL) provides a flexible and interoperable information model, vocabulary, [...]

I believe that we need to start the document as every Wikipedia article does: "ODRL is... a language ....". 
I would choose a careful wording, as the definition will be quoted once and again.

**Comment by riannella** [comment]
(Currently, ODRL is defined as a "REL" on wikipedia ! https://en.wikipedia.org/wiki/ODRL)

Both specs open with: 

> The Open Digital Rights Language (ODRL) provides a flexible and interoperable information model, vocabulary, and encoding mechanisms for describing statements about content usage.

How about:

The Open Digital Rights Language (ODRL) **is a policy expression language that** provides a flexible and interoperable information model, vocabulary, and encoding mechanisms for describing statements about content usage.

**Comment by vroddon** [comment]
A fresh read of the [charter](https://www.w3.org/2016/poe/charter) may also help to improve the abstract. The current abstract reads:

> The Open Digital Rights Language (ODRL) provides a flexible and interoperable information model, vocabulary, and encoding mechanisms for describing statements about the usage of content and services. The ODRL Information Model describes the underlying concepts, entities, and relationships that form the foundational basis for the semantics of the ODRL statements.
> 
> Policies are used to explicitly state what are the permitted and prohibited actions over a certain resource, as well as the obligations required to be meet by stakeholders. In addition, policies may be integrated with constraints (e.g., time constraints) which apply to such actions to impose further restrictions to the uses of the resource.
I suggest a few changes:

- change the word "describe" by "represent" in the first paragraph to be more precise and to avoid an inelegant repetition of the word.

- replace "ODRL statement" by "ODRL policy", to introduce that policy is the main element of an ODRL expression. Otherwise "policies" appears as the first word in the second paragraph without introduction.

- replace "policies may be integrated with constraints" by "policies may be limited by"

- replace "explicitly state" with "represent"

- replace "resource" by "asset"

- shorten a redundant part of a phrase, introduce "duty" instead (I added the word "payment" which may be unpleasant, though).

My suggested abstract would read:

The Open Digital Rights Language (ODRL) is a policy expression language that provides a flexible and interoperable information model, vocabulary, and encoding mechanisms for representing statements about the usage of content and services. The ODRL Information Model describes the underlying concepts, entities, and relationships that form the foundational basis for the semantics of the ODRL policies.

Policies are used to represent permitted and prohibited actions over a certain asset, as well as the obligations required to be meet by stakeholders. In addition, policies may be limited by constraints (e.g., temporal or spatial constraints) and duties (e.g. payments) may be imposed on permissions.

**Comment by riannella** [comment]
Updated

**Comment by nitmws** [comment]
This checking of the basic ODRL definition reminds me of an earlier discussion: what kind(s) of asset is covered by ODRL:
* the IM wording uses in many cases "Asset resource" or only "resource"
* I recall from a discussion at a call: "ODRL will be a W3C recommendation and in the W3C context a resource is a digital thing."
* If this is really the agreed view of Asset then we should use "**digital Asset resource**" or "**digital resource**" (as the Digital of ODRL does not define the type of assets) ... 
* ... as I guess in the cultural heritage area it could be of interest to use the same policy language for licensing the use of a photo of a painting and the use of the real painting asset.
* Final check: do we really want to exclude "analogue things" - which have identifiers, like a painting or a sculpture of a museum?

**Comment by riannella** [comment]
My feelings is that we should be agnostic as to the form of the Asset.
ODRL only cares about Asset URIs - if a URI identifies a non-digital asset, then great ;-)

**Comment by nitmws** [comment]
Ok, good to read that.
Then I suggest modify 2.2 Asset Class, 1st sentence, list of examples: " .. applications**, services or any non-digital object having a unique identifier.**" ... to give at least a hint that the Asset could also be non-digital.

**Comment by riannella** [comment]
done
