### ISSUE TITLE
Clarify inheritance and over-riden entities

### ISSUE THREAD

**Issue by riannella** [w3c/poe#22]
We need to make clear exactly what gets inherited and what gets over-riden (if anything)

**Comment by simonstey** [comment]
inheritance in terms of https://www.w3.org/community/odrl/model/2.1/#section-211 ?

**Comment by riannella** [comment]
Yes. There needs to be more narrative on how inheritance works (and exploring more complex use cases).

**Comment by sereAbi** [comment]
I updated Example 3 in the Information Model to clarify better how inheritance works. Please check and adapt if needed.

**Comment by simonstey** [comment]
## Definition
> The default value of the `inherit` attribute is true

there is no `inherit` attribute -> `inheritAllowed`?

> Only if the `inheritAllowed` attribute has the value true MAY the following be used: 

where can they MAY be used? in the parent policy? in one/some/all child policies of the parent policy?

>  inheritFrom: the identifier from which this Policy inherits from it’s parent Policy (OPTIONAL)

what? _the identifier from which this Policy inherits_ == parent policies identifier? 
it's -> its

>  inheritRelation: the identifier for the relationship type of this inheritance structure (OPTIONAL)
[...]
For example, an Assigner and Assignee may have a historical arrangement related to the specific use of content they make available to each other. The business model  (identified with a URI) is used in the inheritRelation attribute in their subsequent ODRL policies they exchange. **This will require the ODRL policy to be interpreted with the additional information identified by the URI**. For example, **this may include additional permission actions or constraints** (etc) that is documented in their business model arrangement.

so `inheritRelation` is basically a workaround to allow some sort of multi-inheritance? why isn't that _additional information_ part of the parent policy in the first place? 

> The Child Policy MUST override the Parent Policy. i.e.: If the same Action appears in the Parent, ...

the parent and ...?

> ... then it is replaced by the Child version, ...

the action is replaced by the child's version of the action? 
so `odrl:read` becomes `odrl:read`?

> ... otherwise the Parent Actions are added to the Child’s Actions.

?? where exactly are they added to? adding `odrl:read` to `odrl:play` -> 
```Turtle
odrl:play 
	a odrl:Action;
	odrl:action odrl:read .
```
? 

**Imo, it's about aligning the rules defined in the parent policy and its respective child policies.**

> Moreover, due to the inheritance relation, the child Policy inherits from the parent that the Party http://example.com/assignee:88 can also reproduce http://example.com/asset:1111.

why is that? 

### Minor Remarks
old | new
------------ | -------------
`"inheritallowed"` | ` "inheritAllowed" `
`"inheritFrom": "http://example.com/policy:1111"` | ` "inheritFrom": "http://example.com/parent_policy:1111" `
`"inheritfrom": "http://example.com/policy:2222"` | ` "inheritFrom": "http://example.com/parent_policy:2222" `

**Comment by sereAbi** [comment]
Thanks for your comments Simon. I fixed the minor issues in the json-ld of the example. Concerning the explanation in the IM about inheritance, I think we need first to agree about the issues you raised and that I shared (drafting the example it becomes clear that these points weren't clear enough). 

Renato, do we discuss this issue on Monday in the slot assigned to the IM?

**Comment by simonstey** [comment]
> I fixed the minor issues in the json-ld of the example.

it's missing a context and is therefore only plain json right? (not 100% sure on that though)

**Comment by sereAbi** [comment]
Yes, it's the json encoding, sorry.

**Comment by riannella** [comment]
@simonstey fixed some of your first concerns.

inheritRelation is a way to allow other existing business rules to be expressed (that are typically not machine readable). It was from the IPTC.  There is an email thread here: https://lists.w3.org/Archives/Public/public-odrl/2013Apr/0052.html

**Comment by riannella** [comment]
I think the "original" idea of inheritance - where actions and parities are "merged" is no longer valid (or even was!). I think we now look at inheritance as an "import" function, where the parent Rules are simply copied into the child.

**Comment by simonstey** [comment]
> inheritRelation is a way to allow other existing business rules to be expressed (that are typically not machine readable). It was from the IPTC. There is an email thread here: https://lists.w3.org/Archives/Public/public-odrl/2013Apr/0052.html

thx for the pointer! 
I still think that inheritRelation shouldn't be part of the core language (and I'm surprised that it actually made it into ODRL in the first place). In his email, Michael even wrote:

> I think the essential modification **-by a RightsML profile -** is to define that the referenced parent does not have to be an ODRL policy.

Keeping this property in ODRL basically allows to not only bypass ODRL entirely:

> Such terms MAY be defined in the ODRL Vocabulary [vocab-odrl] or ODRL Profiles. [...] 

but also requires any engine to be able to process and interpret those additional _permission actions or constraints (etc)_:

> This will require the ODRL policy to be interpreted with the additional information identified by the URI. For example, this may include additional permission actions or constraints (etc) that is documented in their business model arrangement.

However, having such a property in ODRL would also justify having a similar one for constraints too.  I.e., we basically just point to a URI containing constraint definitions which may or may not be defined in ODRL, which in the end doesn't really matter because we require engines to be able to interpret them anyway. 😛

**Comment by riannella** [comment]
Michael's comment was inheritRelation does not have to an ODRL Policy - it can point to a written agreement between the two parties (that is what happens in the IPTC community)
Yes, inheritRelation changes the processing landscape. 
But the point is, if you see it and don't understand it, then you proceed at your own risk...

**Comment by riannella** [comment]
I am proposing we refine the inheritance to be a the Rule level, not the action level - as the latter is too complex to process.

**Comment by riannella** [comment]
Followed the model outlined here: https://lists.w3.org/Archives/Public/public-poe-wg/2017Jan/0005.html

Narrative and examples have been updated

**Comment by simonstey** [comment]
[3.1.5 Policy Inheritance](http://w3c.github.io/poe/model/#inhertiance): 

> ODRL supports a simple inheritance mechanism in which a (child) Policy may inherit **all the information compositions** of another (parent) Policy. The inheritance is aimed at including **data compositions** between Policies.

What are **information compositions**? What are **data compositions**?

**Comment by riannella** [comment]
They are the same.

Rewrite as:

ODRL supports a simple inheritance mechanism in which a (child) Policy may inherit all the information entities that the (parent) Policy is composed of. The inheritance is aimed at including the  information entities between Policies.

This is then what section 3.1.1 talks about.

**Comment by riannella** [comment]
updated

**Comment by simonstey** [comment]
> Michael's comment was inheritRelation does not have to an ODRL Policy - it can point to a written agreement between the two parties (that is what happens in the IPTC community)
Yes, inheritRelation changes the processing landscape.
**But the point is, if you see it and don't understand it, then you proceed at your own risk...**

It's not that easy though.. 
if implementations want to conform with the standard, they have to implement (i.e., correctly deal with) all normative features of respective standard. 

So if an ODRL implementation wants to process a policy (containing an `inheritRelation`) in a standard-conform manner, what needs to be done?

Considering following (non-normative) example:

> For example, an Assigner and Assignee may have a historical arrangement related to the specific use of content they make available to each other. The business model (identified with a URI) is used in the inheritRelation attribute in their subsequent ODRL Policies they exchange. **This will require the ODRL Policy to be interpreted with the additional information identified by the URI.** For example, this may include additional permission Actions or constraints (etc) that is documented in their business model arrangement.

plus ->

> Michael's comment was **inheritRelation does not have to an ODRL Policy - it can point to a written agreement between the two parties** (that is what happens in the IPTC community)

would require implementations to do NLP so they can properly interpret the policy?

coming back to:
> But the point is, if you see it and don't understand it, then you proceed at your own risk...

if it's ok for implementations to simply ignore that property, then why have it in the first place?

**PROPOSAL: Remove `odrl:inheritRelation` from ODRL Core and leave it for implementations to implement such a feature.**

**Comment by riannella** [comment]
At a very atomic level, the semantics of odrl:inheritRelation mimics a duty in that two parties agree to follow some (external) policy.

So, perhaps we can use a Duty instead:

       "duty": [{
            "action": "odrl:reviewPolicy",
            "target": "http://ap.com/agreements/foo-001"
            }]

**Comment by riannella** [comment]
WG decided to remove inheritRelation

**Comment by riannella** [comment]
Removed inheritRelation attribute from Model and deprecated from Vocab
