### ISSUE TITLE
IM - simple typos

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#220]
IM of 17 August - 1.3 Terminology / Duty:

Now:  If the obligation is meet, then the Duty is fulfilled
Should be:  If the obligation is **met**, then the Duty is fulfilled

2.5.4 Obligation property with a Policy, 1st para:

Now: That is, the obligation has been meet.
Should be: That is, the obligation has been **met**.

**Comment by riannella** [comment]
fixed
