### ISSUE TITLE
Which property of type Duty has a consequence property?

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#222]
The IM of 21 August defines in 2.5.3 Duty Class

> Note that the consequence property must not be used on a Duty that is already a consequence for a Permission duty or Policy obligation.

There is an issue:
* The Duty Class defines: A Duty may have none, one or many consequence property values of type Duty.
* Result: the properties obligation, duty, remedy and consequence are of type Duty and have therefore a consequence property
* The Note above excludes a consequence property inside a consequence instance only for duty and obligation ...
* ... therefore remedies may have an unlimited nesting of consequences.

Suggested solution 1: change the definition of the consequence property of the Duty Class to:
A Duty may have none, one or many consequence property values of type Duty if used with any property except the consequence property itself. (This stops nesting consequences.)

Suggested solution 2: exclude the consequence property from the basic Duty Class. Then define the Duty-Extended Class as sub-class of Duty Class and add the consequence property and set the type to Duty Class. Then apply the Duty-Extended Class to obligation, duty and remedy.

**Comment by nitmws** [comment]
Uff, in 2.5.7 I've found that: "A remedy must not refer to a Duty that includes a consequence Duty."

Could we please define which properties of type Duty have a consequence in a single place = at the level of the Duty.

**Comment by riannella** [comment]
Followed Solution one, with:

> A Duty MAY have none, one or many <code>consequence</code> property values of type Duty only when the Duty is related to a Permission with the duty property.

**Comment by nitmws** [comment]
Wait a second @riannella : 
* as I got it the intention of these exclusions was to avoid an endless nesting of consequences
* but I assume a duty **and** an obligation should have a consequence - but not a remedy
* your definition above the stops obligation to have one

**Comment by nitmws** [comment]
I went over the IM of 25 August and infer from it - with the correction above - these lists of properties of the Rule Class and its sub-classes and specific properties of type Duty.

Typographic notes:
* at the top of the lists: property name/name of class used as type
* ( ) = cardinality
* { } = abstract definition, must be overridden by a sub-property
* ... = as inherited
* _: = the abstract definition which is overridden by this sub-property

```
any property/Rule	
	action/Action (1)
	{relation}/Asset (0..1)
	{function}/Party (0..unbounded)
	{failure}/Rule (0..unbounded)
	constraint/Constraint classes (0..unbounded)
	uid/IRI (0..1)
	
permission/Permission (sub-class of Rule)
	action ...
	relation: target (1)
	relation: {others} ...
	function: assigner (0..1)
	function: assignee (0..1)
	function: {others} ...
	failure: none defined
	constraint ...
	uid ...
	
prohibition/Prohibition (sub-class of Rule)
	action ...
	relation: target (1)
	relation: {others} ...
	function: assigner (0..1)
	function: assignee (0..1)
	function: {others} ...
	failure: remedy (0..unbounded)
	constraint ...
	uid ...
	
obligation/Duty  (sub-class of Rule)
        action ...
	relation: target (0..1)
	relation: {others} ...
	function: assigner (0..1)
	function: assignee (0..1)
	function: {others} ...
	failure: consequence (0..unbounded)
	constraint ...
	uid ...
	
duty/Duty	
        action ...
	relation: target (0..1)
	relation: {others} ...
	function: assigner (0..1)
	function: assignee (0..1)
	function: {others} ...
	failure: consequence (0..unbounded)
	constraint ...
	uid ...

remedy/Duty	
        action ...
	relation: target (0..1)
	relation: {others} ...
	function: assigner (0..1)
	function: assignee (0..1)
	function: {others} ...
	failure: none defined
	constraint ...
	uid ...
	
consequence/Duty	
        action ...
	relation: target (0..1)
	relation: {others} ...
	function: assigner (0..1)
	function: assignee (0..1)
	function: {others} ...
	failure: none defined
	constraint ...
	uid ...
	
```

I hope that reflects the IM and where a consequence exists and where not correctly.

**Comment by riannella** [comment]
Whoops ;-) That should be:

`A Duty MAY have none, one or many <code>consequence</code> property values of type Duty only when the Duty is related to a Rule with the duty or obligation properties.
`
