### ISSUE TITLE
adding disclaimer to http://www.w3.org/TR/odrl

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#224]
(pinging @philarcher and @iherman)

Would it be possible to add a disclaimer/update notice to [ODRL 1.1's W3C Note from 19 September 2002](http://www.w3.org/TR/odrl) that points to ODRL's new IM/Vocab? Something like the one used for [OWL](https://www.w3.org/TR/owl-features/):
> New Version Available: OWL 2 (Document Status Update, 12 November 2009)
> 
> The OWL Working Group has produced a W3C Recommendation for a new version of OWL which adds features to this 2004 version, while remaining compatible. Please see OWL 2 Document Overview for an introduction to OWL 2 and a guide to the OWL 2 document set.

Having such a Note in TR space, especially with **odrl** as its shortName and being one of the first results popping up when searching for [odrl w3c](https://www.google.at/search?q=odrl+w3c), might cause confusion.

**Comment by iherman** [comment]
I would think this should be possible, but pinging @plehegar on this.

**Comment by philarcher** [comment]
Shouldn't be much of a problem. I well remember adding similar notes to 
the PICS specs, see

https://www.w3.org/PICS/
https://www.w3.org/TR/REC-PICS-services/
etc.

Phil

On 25/08/2017 06:08, Ivan Herman wrote:
> I would think this should be possible, but pinging @plehegar on this.
> 

-- 
Phil Archer
http://philarcher.org
+44 7887 767755
@philarcher1

**Comment by iherman** [comment]
>W3C's in-place modification policy is at
>
> http://www.w3.org/2003/01/republishing/
>
> This falls under "Some visible status updates, such as indicating newer versions".

So yes, this can be, and will be done.

**Comment by riannella** [comment]
@iherman I think we should add something similar to the OWL update:

> New Version Available: ODRL 2 (Document Status Update, X Month 2018)
> 
> The POE Working Group has produced new W3C Recommendations for updated versions of ODRL which supersedes features of this 2002 version. Please see the ODRL Information Model document for an overview of the updated language and the ODRL Vocabulary & Expression document for the language terms and serialisations.

**Comment by iherman** [comment]
I have made the change on my local copy. However, I think it is better not to make the update on the server until the new version is official, ie, it is published as a Recommendation (or, at the minimum, Proposed Recommendation). Otherwise we will have to change the status again and again, to keep it up with the current status.

**Comment by philarcher** [comment]
Yes, it's a 'Happy Recommendation Day' action :-)

Hope all is well - good to see progress continuing.

All the best from the other side

Phil

On 05/09/2017 08:21, Ivan Herman wrote:
> I have made the change on my local copy. However, I think it is better not to make the update on the server until the new version is official, ie, it is published as a Recommendation (or, at the minimum, Proposed Recommendation). Otherwise we will have to change the status again and again, to keep it up with the current status.
> 

-- 
Phil Archer
http://philarcher.org
+44 7887 767755
@philarcher1

**Comment by plehegar** [comment]
@iherman , will you make a proposal to the webmaster in order to update the Note?

**Comment by iherman** [comment]
@plehegar I did not realize I need to make a proposal but yes, I can do that. However, that is down the line when the Rec is published...

**Comment by riannella** [comment]
Also add a redirect from the Community Group documents to the new RECs

**Comment by iherman** [comment]
@riannella, I take care of the /TR/2002/... document; will you take care of the CG ones?

**Comment by riannella** [comment]
Redirects from CG reports are now in place.

**Comment by iherman** [comment]
The https://www.w3.org/TR/2002/NOTE-odrl-20020919/ note has also been updated with a reference to the Recommendations.
