### ISSUE TITLE
Misleading statements about failure properties

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#229]
## Correct
http://w3c.github.io/poe/model/#prohibition:
> **The remedy property (a sub-property of the failure property) expresses an agreed obligation that MUST be fulfilled in the case that the Prohibition has been violated.** That is, the remedy property asserts a Duty that must be fulfilled if the Prohibition is exercised. 

## Misleading
http://w3c.github.io/poe/model/#duty-prohib:
> **Note that if there is no remedy property declared for a Prohibition, then the Prohibition MUST NOT be exercised.** A remedy MUST NOT refer to a Duty that includes a consequence Duty.

=> just because a prohibition has a remedy attached doesn't mean that prohibited action MAY be exercised (under the condition that respective remedy is fulfilled). Regardless of whether prohibitions have remedies or not, prohibited actions **always MUST NOT be exercised**.

**Solution:** Remove "_Note that if there is no remedy property declared for a Prohibition, then the Prohibition MUST NOT be exercised._"

----

## Correct
http://w3c.github.io/poe/model/#duty:
> The consequence property (a sub-property of the failure property) is utilised to express the repercussions of not fulfilling an agreed Policy obligation or duty for a Permission. **If either of these fails to be fulfilled, then this will result in the consequence Duty also becoming a new requirement, meaning that the original obligation or duty, as well as the consequence Duty MUST all be fulfilled. **
http://w3c.github.io/poe/model/#duty-policy

## Misleading
http://w3c.github.io/poe/model/#duty-policy:
> A Policy MAY also include a consequence of not fulfilling an obligation. **Note that if there is no consequence property for an obligation Duty, then the obligation MUST be fulfilled.**

=> just because a duty has a consequence attached doesn't mean that it's optional. Regardless of whether duties have consequences or not, they are **always obligatory**.

**Solution:** Remove "_Note that if there is no consequence property for an obligation Duty, then the obligation MUST be fulfilled._"

**Comment by riannella** [comment]
Done.
commit: 129b11b888ef6ec2d6d30bf4f26c3df362532732
