### ISSUE TITLE
Clarify Party definition

### ISSUE THREAD

**Issue by riannella** [w3c/poe#23]
Need to define Party more generically, not based on role

**Comment by sereAbi** [comment]
To abstract away from Role in the definition of Party, we need to mention "function" which assigns the Party to the Rule by associating it the "role" it plays in the Rule. I'd add a reference to foaf in addition to vcard, as in the V&E document.

**Comment by sereAbi** [comment]
I updated the definition along these lines, and added reference to foaf.

**Comment by riannella** [comment]
Completed
