### ISSUE TITLE
rightOperand property: IM and Vocab not in sync

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#231]
The IM (of 1 September), 2.5.1 Constraint class defines for right operands:

> A Constraint must have either:
> * one rightOperand property value of type literal, IRI [rfc3987], or RightOperand; or,
> * one rightOperandReference property ...

The Vocab (of 1 September) defines for Has Right Operand (http://w3c.github.io/poe/vocab/#term-rightOperand) = the rightOperand property:
* no Range
* in a Note: "The value can be a literal or IRI."

The Vocab definition does not cover the RightOperand as alternative property value.

**Comment by riannella** [comment]
Updated range

Hope they are ok @vroddon

**Comment by vroddon** [comment]
Yes, indeed, the change is correct. 

Just out of curiosity, I checked the definition of xsd:anyURI to discover that indeed, it also covers IRIs. 
"Absolute or relative URIs and IRIs" https://www.w3.org/TR/rdf11-concepts/

**Comment by iherman** [comment]
Can then be close this issue?
