### ISSUE TITLE
Use of plural in the definition of classes and properties in the Vocab

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#232]
The Vocab (of 1 September) uses plurals in definitions of classes and properties of classes - I went over the Constraint section: http://w3c.github.io/poe/vocab/#constraints
* Has Constraint (property): "Constraints applied to a Rule"
* Refinement (property): "Constraints used to refine ..."
* Operator (class): "Operators for constraint expressions"
* Right Operand (class): "Right operands for constraint expressions." 
* Left Operand (class): "Left operands for constraint expressions."

Re properties: using the plural makes the reader think the property allows to reference more than 1 values in any case - but the cardinality is covered by definitions of classes and not be the definition of a property as such.
Re classes: the definition of a class covers in many, if not in all, cases a single Thing only. 

I suggest to "singularise" these definitions.

**Comment by riannella** [comment]
Fixed
