### ISSUE TITLE
One redundancy in the spec

### ISSUE THREAD

**Issue by vroddon** [w3c/poe#235]
In different sections we read:

> "A Policy must have at least one permission, prohibition, or obligation property values of type Rule. "
> "An ODRL Policy of subclass Set: must have at least one permission, prohibition, or obligation property value of type Rule."
> "An ODRL Policy of subclass Offer: must have at least one permission, prohibition, or obligation property values of type Rule."
> "An ODRL Policy of subclass Agreement: must have at least one permission, prohibition, or obligation property values of type Rule."

I believe the first sentence suffices. Every subclass of Policy (in the spec or not) is subject to that. Hence, the next three paragraphs can be safely removed.

**Comment by riannella** [comment]
Done
