### ISSUE TITLE
Validator/validation/valid-related terminology

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#237]
The IM of 1 September defines in 1.3 Terminology the term "ODRL Validator" as 

> A system that checks the conformance of ODRL Policy expressions with respect to the ODRL Information Model validation requirements.

It defines two key features:
1. checking conformance
2. being aware of validation requirements

**re 1: conformance with IM**
* 2.1 Policy Class defines that a Profile can define "conformance requirements" - I assume they don't have to be covered by a "Core IM" Valdiator.
* 2.6.8 outlines what an ODRL Validator has to validate - by examples: "For example, this includes property cardinality and relationships, and conforming to validation requirements."
* That's all about a Validator covering the conformance to the IM.
* What is missing: to write down what a Validator must validate outside an example, e.g. in the Terminology definition. (A general issue: the whole section 1 is not-normative!)
I suggest: 
**A system that checks the conformance of ODRL Policy expressions, including the cardinality of properties and if they are related to types of values as defined by the ODRL Information Model, and the Information Model's validation requirements.**

**re 2: validation requirements**
* The are defined in 2.5.2 Logical Constraints, 2.7 Policy Rule Composition, 2.7.1 Compact Policy, 2.8 Policy Metadata, 2.9 Policy Inheritance in a consistent way - that's fine

**The "valid" status of a Policy**
* Section 2.10 Policy Conflict Strategy defines checks clearly outside the definition of the ODRL Validator - and that this check has an impact on the valid/invalid state of a Policy. 
* This causes terminology confusion:
  * a processor called Validator returns for its validations as result the Policy is **(not) conforming** to the IM - and NOT that the Policy is **valid** or **invalid**
  * checking the conflicts inside a Policy - which is not done by the Validator -  returns as result **valid** or **invalid**
* Knowing that this would change a term with a long history but for making the IM more transparent I suggest: 
**the results of checking Policies for conflicts results in "in-conflict" and "no-conflict"**
... and the **enumeration term "invalid" should be changed to "unusable"**

**Comment by riannella** [comment]
I have changed the meaning of the "invalid" token to mean "void".
And not mentioned "valid" anymore.
Updated the rest.

**Comment by nitmws** [comment]
@riannella thanks for taking this step, but frankly still not a consistent solution: 
* the ODRL Validator definition in 1.3 does not cover checking Policies for conflicting Rules
* 2.10 tells: "If an ODRL Validator detect any conflicts in the Rules  ..." - this is not covered by 1.3
* and as I said above: I think a Validiator delivers only a single result: valid or invalid. As described in 2.10 it also delivers "the Policy is void" and this has to be matched against the conflict property value "invalid".

**Comment by simonstey** [comment]
> the ODRL Validator definition in 1.3 does not cover checking Policies for conflicting Rules

👍 as a Validator only checks for well-formedness (i.e., whether all policy expressions conform to the spec)

> 2.10 tells: "If an ODRL Validator detect any conflicts in the Rules ..." 

👎 that's actually wrong.. iirc an ODRL Validator only checks for **syntactic** validity, but not for **semantic** validity

**Comment by riannella** [comment]
So what checks for semantic validity?

**Comment by riannella** [comment]
Personally, I think we should have a single "ODRL Processor" that does everything. As no implementation will have these seperate things - and we are not testing for them individually for interoperability.

**Comment by riannella** [comment]
I have updated section 2.10 to only mention the requirements, not a system to check the requirements.

**Comment by simonstey** [comment]
https://github.com/w3c/poe/commit/d6fb940415e3a5877d08c3af9087b83c981d7a4a 
> If a Policy has the conflict property of invalid then the entire Policy MUST be void.

**only** when there are conflicts! otherwise, e.g. any policy not defining a conflict resolution strategy is void by default.

**Comment by riannella** [comment]
See #270
