### ISSUE TITLE
Confusing wording

### ISSUE THREAD

**Issue by vroddon** [w3c/poe#238]
In Section 2.2 of the IM we read:

> An Asset must have at least one relation sub-property value (of type Asset) indicating the explicit link relationship to the Asset.

And in Section 2.3 we read:

> A Party must have at least one function sub-property values (of type Party) indicating the functional role undertaken by the Party.

Am I the only one confused after reading this? Wouldn't it be better like this?

> **A Rule** must have at least one relation sub-property value (of type Asset) indicating the explicit link relationship to the Asset.
> **A Rule** must have at least one function sub-property values (of type Party) indicating the functional role undertaken by the Party.

(Bonus comment: what is the meaning of a rule not having a assigner? lacking an assingee is understood as everyone but... lacking an assigner? a work in the public domain? In such a case, please mind that we cannot have zero assigners and zero assignees)

**Comment by vroddon** [comment]
The Bonus comment was even more important.  EXAMPLE1 in the Information Model becomes invalid.

```
{
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Set",
    "uid": "http://example.com/policy:1010",
    "permission": [{
        "target": "http://example.com/asset:9898.movie",
        "action": "use"
    }]
}
```

**Comment by riannella** [comment]
I have removed both bullet points (as these are not, as you point out, properties of Asset/Party). And they are covered in the Rule section.

Bonus Answer: we don't say what it means in general.
We only are specific for Offer and Agreement subclasses to have these roles.

**Comment by vroddon** [comment]
Is Example1 then correct? Or should it be corrected?

**Comment by riannella** [comment]
It is correct. It conforms to the requirements of a "Set".

**Comment by vroddon** [comment]
Now it is perfectly clear.
