### ISSUE TITLE
Include Rule in the UML Model

### ISSUE THREAD

**Issue by riannella** [w3c/poe#24]
Include Rule in the normative Information Model? Rule appears in the Ontology as an abstract class already

**Comment by simonstey** [comment]
basically adopting https://www.w3.org/community/odrl/model/2.1/#section-52 ?

makes sense to me.. +1

**Comment by riannella** [comment]
Proposed updated UML Model (which has also been "modernised" !)
Will also add text similar to section 6.2
![odrl-model-2016](https://cloud.githubusercontent.com/assets/13191615/17664508/e9917942-6337-11e6-951b-23fc075d5b00.jpg)

**Comment by vroddon** [comment]
Looks much nicer --and we get rid of a cumbersome text advertising the software "Astah".
Which program have you used to generate the figure?

**Comment by riannella** [comment]
@vroddon I just used a graphics program (OmniGraffle on the Mac) as I could not find a UML editor that you could sufficiently configure the graphical elements of the UML classes and associations.

**Comment by sereAbi** [comment]
I'd add uid to the Policy box as done for the others.

**Comment by riannella** [comment]
Completed
