### ISSUE TITLE
use of @value for action constraints

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#241]
I used http://www.easyrdf.org/converter to translate [Example 13](https://w3c.github.io/poe/model/#constraint-action) into turtle
```json
{
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Offer",
    "uid": "http://example.com/policy:6161",
    "profile": "http://example.com/odrl:profile:10",
    "permission": [{
       "target": "http://example.com/document:1234",
       "assigner": "http://example.com/org:616",
       "action": [{
          "@value": "print",
          "refinement": [{
             "leftOperand": "percentage",
             "operator": "lteq",
             "rightOperand": "50.0"
          }]
      }]
   }]
}
```
results in:
```turtle
@prefix ns0: <http://www.w3.org/ns/odrl/2/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.com/policy:6161>
  a <http://www.w3.org/ns/odrl/2/Offer> ;
  ns0:permission [
    ns0:action "print"^^xsd:string ;
    ns0:assigner <http://example.com/org:616> ;
    ns0:target <http://example.com/document:1234>
  ] ;
  ns0:profile <http://example.com/odrl:profile:10> .
```

1. refinement is ignored because http://www.w3.org/ns/odrl.jsonld is not up2date
1.1. it throws an error if you replace refinement with constraint
2. print is interpreted as string because..
https://json-ld.org/spec/latest/json-ld/#syntax-tokens-and-keywords:
> **@id**
    Used to uniquely identify things that are being described in the document with IRIs or blank node identifiers. This keyword is described in section 3.3 Node Identifiers.
>
> **@value**
    Used to specify the data that is associated with a particular property in the graph. This keyword is described in section 4.10 String Internationalization and section 4.5 Typed Values.

--------------- 

=> adopt a similar approach as with asset/party constraints and replace @value with source

**Comment by riannella** [comment]
Does this error go away if you use the up-to-date JSON-LD context here:

   https://raw.githubusercontent.com/w3c/poe/gh-pages/vocab/ODRL22.jsonld

**Comment by nitmws** [comment]
@simonstey would using  @id do the job:
```
       "action": [{
         "@id": "odrl:print",
          "refinement": [{
             "leftOperand": "percentage",
             "operator": "lteq",
             "rightOperand": "50.0"
          }]
```
... or is the inline-adding of properties to an identified node not allowed.

Is the result using the property `source` for the "unrefined" action and the `refinement `property provides all the Refinements applying to it?
In this case the IM must define the source property, I guess (currently it is not).

**Comment by simonstey** [comment]
> @simonstey would using @id do the job:

for the same reasons we introduced the source property in the first place, unfortunately not /:

**Comment by vroddon** [comment]
What is wrong with the examples I provided? I did the conversion by hand.
See sample022 at http://odrlapi.appspot.com/.

@prefix odrl: <http://www.w3.org/ns/odrl/2/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dct: <http://purl.org/dc/terms/> .

```
#valid. (example 22 in the IM)
<http://odrlapi.appspot.com/samples/sample022>
    dct:source <http://w3c.github.io/poe/model/> ;
    a odrl:Agreement ;
    odrl:profile <http://example.com/odrl:profile:09> ;
    odrl:obligation [
        odrl:target <http://example.com/photoAlbum:55> ;
        odrl:assigner <http://example.com/org:43> ;
        odrl:assignee <http://example.com/person:44> ;
        odrl:action [
            rdf:value odrl:compensate ;
            odrl:refinement [
                odrl:leftOperand odrl:payAmount;
                odrl:operator odrl:eq;
                odrl:rightOperand 500;
                odrl:unit <http://dbpedia.org/resource/Euro>
            ] 
        ] 
    ] .

```

**Comment by riannella** [comment]
@iherman 

Can you copy
  https://raw.githubusercontent.com/w3c/poe/gh-pages/vocab/ODRL22.jsonld
to
  http://www.w3.org/ns/odrl.jsonld

thanks

**Comment by riannella** [comment]
@vroddon 

Your example is exactly how I suspected the translation to turtle would work

**Comment by riannella** [comment]
@simonstey 

i think all we need to do is updated:
`          "@value": "print",`
to
`"@value":  { "@id": "print" },`

That will then allow for the more simple case of `"action": "print",`

**Comment by simonstey** [comment]
> i think all we need to do is updated:
`"@value": "print",`
to
`"@value": { "@id": "print" },`

I'm no JSON-LD expert myself, but according to https://json-ld.org/spec/latest/json-ld/#value-objects:

> A value object MUST be a JSON object containing the @value key. It MAY also contain an @type, an @language, an @index, or an @context key but MUST NOT contain both an @type and an @language key at the same time. **A value object MUST NOT contain any other keys that expand to an absolute IRI or keyword.**
> 
> **The value associated with the @value key MUST be either a string, a number, true, false or null.**

as such, `rdf:value` can't be mapped to `@value`

=> `"rdf:value": { "@id": "print" },` should work though

**Comment by iherman** [comment]
@riannella, per https://github.com/w3c/poe/issues/241#issuecomment-327066375: done.

**Comment by riannella** [comment]
@simonstey Close...the output is now:

```
@prefix ns0: <http://www.w3.org/ns/odrl/2/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.com/policy:6161>
  a <http://www.w3.org/ns/odrl/2/Offer> ;
  ns0:permission [
    ns0:action [
      rdf:value <http://njh.me/print> ;
      ns0:refinement [
        ns0:leftOperand ns0:percentage ;
        ns0:operator ns0:lteq ;
        ns0:rightOperand "50.0"^^xsd:string
      ]
    ] ;
    ns0:assigner <http://example.com/org:616> ;
    ns0:target <http://example.com/document:1234>
  ] ;
  ns0:profile <http://example.com/odrl:profile:10> .

```

**Comment by simonstey** [comment]
> ~~=> `"rdf:value": { "@id": "print" },` should work though~~

=> `"rdf:value": { "@id": "odrl:print" },` should work though

**Comment by riannella** [comment]
Yes!!!!

```
@prefix ns0: <http://www.w3.org/ns/odrl/2/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.com/policy:6161>
  a <http://www.w3.org/ns/odrl/2/Offer> ;
  ns0:permission [
    ns0:action [
      rdf:value ns0:print ;
      ns0:refinement [
        ns0:leftOperand ns0:percentage ;
        ns0:operator ns0:lteq ;
        ns0:rightOperand "50.0"^^xsd:string
      ]
    ] ;
    ns0:assigner <http://example.com/org:616> ;
    ns0:target <http://example.com/document:1234>
  ] ;
  ns0:profile <http://example.com/odrl:profile:10> .
```

**Comment by riannella** [comment]
Do we have to add rdf:value to the JSON-LD context file ??

**Comment by riannella** [comment]
Updated now to use rdf:value
