### ISSUE TITLE
Validation: OWL consistency

### ISSUE THREAD

**Issue by vroddon** [w3c/poe#247]
The spec does not mention that valid policies must be **consistent with the ODRL Ontology**.  Should it? This is illustrated by observing http://odrlapi.appspot.com/samples/sample003, reproduced here for convenience:

```
<http://odrlapi.appspot.com/samples/sample003>
    a odrl:Offer, odrl:Agreement;
    dct:source "victor" ;
    odrl:permission [
        a odrl:Permission ;
        odrl:assigner <http://example.com/user:711> ;
        odrl:assignee <http://example.com/user:314> ;
        odrl:target <http://example.com/asset:9898> ;
        odrl:action odrl:reproduce
    ] .
```

Given that the ontology has declared some `owl:disjointWith` axioms, the joint model policy+ODRLontology is inconsistent.

I have just implemented this validation in the [ODRL Validator](http://odrlapi.appspot.com/)
However, the validation takes some 4-5 seconds extra and I will probably remove this validation in future versions. You can test it for the moment --but be patient, validations take long now.
This is the current error message:

> OWL Inconsistent. - Error ("conflict"): "Individual a member of disjoint classes"

**Comment by riannella** [comment]
I have added disjoint classes into the conversion to HTML

Let me know if there is anything else missing

**Comment by simonstey** [comment]
what's the rationale for declaring them owl:disjointWith in the first place? do we mention that requirement anywhere in the spec?

**Comment by riannella** [comment]
Doesn't this make sense from an ontological point-of-view?

**Comment by vroddon** [comment]
Well, they were all in ODRL2.1, I see no specific reasons to remove them or to keep them --much like declaring domain and range for the properties. 
Another example we have always had in the spec is the disjointness between Permission, Prohibition and Duty. I don't see how can a Permission be a Prohibition a the same time, for example.

But coming back to my original questions...
...should we add the consistency check as a validation? or is it something that every implementor will understand? For the moment I have left it as a "warning" only.
