### ISSUE TITLE
Wording in Logical Constraints

### ISSUE THREAD

**Issue by vroddon** [w3c/poe#250]
FIRST SUGGESTED CHANGE
The spec reads:

> The ODRL validation requirements for Logical Constraints includes:
> 
> 1. The operand must only be of the sub-properties; or, xone, and, andSequence. Additional sub-properties of operand may be defined by ODRL Profiles exclusively for the use of Logical Constraints.
> 2. All of the operand values must be unique Constraint instances.
> 3. These Constraint instances must be evaluated and the outcomes used to determine if the logical relationship is satisfied (based on the semantics of the operand sub-property).

I suggest removing the third element from the list (but keeping it out of the list). The reason is that the validation does not need to evaluate anything.

SECOND SUGGESTED CHANGE
The spec reads:

> An ODRL validator must support the following sub-properties of operand:

I suggest replacing the word "validator" by "evaluator".

**Comment by riannella** [comment]
Done
