### ISSUE TITLE
Mild contradictions in IM wrt validation

### ISSUE THREAD

**Issue by vroddon** [w3c/poe#252]
In IM 2.1.2:

> An ODRL Policy of subclass Offer: [...] must have one assigner property value (of type Party)

...is in mild contradiction with what is said in "Section 2.7 Policy Rule Composition", which accepts more than one value for the assigner property. 

At first the ODRL Validator validated that Offer had to have exactly one assigner, now it accepts several more because the expansion is automatically made. Perhaps that sentence (and equivalent ones affecting asset, action and assignees) in other parts of the spec have to be rethought.

The problem would solved by adding the word "atomic":
> An **atomic** ODRL Policy of subclass Offer: [...] must have one assigner property value (of type Party)

But then we would need to define first what atomic is etc. Unsure, perhaps it is better not changing anything.

**Comment by riannella** [comment]
Added the same note to Offer/Agreement section as we use in the Rule/Permission/Prohibition section

**Comment by vroddon** [comment]
@riannella What is the meaning of 'unique' in this sentence? (IM 2.5.2)

> All of the operand values must be unique Constraint instances.

Should we understand "not referenced by any other rule or any other policy the parser is aware of"?

**Comment by vroddon** [comment]
The meaning of example 24 makes me feel uneasy.
```
{
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Agreement",
    "uid": "http://example.com/policy:33CC",
    "profile": "http://example.com/odrl:profile:09",
    "prohibition": [{
        "target": "http://example.com/data:77",
        "assigner": "http://example.com/person:88",
        "assignee": "http://example.com/org:99",
        "action": "modify",
        "remedy": [{
            "action": "delete",
            "target": "http://example.com/data:77"
        }]
    }]
}
```
As it means: "you cannot modify data77. But if you happen to modify data77, then delete data77".
Instead of: "you cannot modify data77. But if you happen to modify data77, then delete THE DATA DERIVED FROM data77".

We hint about using other subproperty of odrl:relation, but this case will be very frequent and I would give further examples. In particular, I would propose:

```
#valid. (example 24 in the IM)
<http://odrlapi.appspot.com/samples/sample072>
    dct:source <http://w3c.github.io/poe/model/> ;
    a odrl:Agreement ;
    odrl:profile <http://example.com/odrl:profile:09> ;
    odrl:prohibition [
        odrl:target <http://example.com/data:77> ;
        XXX:resultingAsset <http://example.com/data:77DERIVED> ;
        odrl:assigner <http://example.com/person:88> ;
        odrl:assignee <http://example.com/person:99> ;
        odrl:action odrl:modify ;
        odrl:remedy [
            odrl:action "delete" ;
            odrl:target <http://example.com/data:77DERIVED> 
        ]
    ] .

```
@riannella should we add such an example anywhere?

**Comment by riannella** [comment]
What if we update the example to:
```
{
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Agreement",
    "uid": "http://example.com/policy:33CC",
    "profile": "http://example.com/odrl:profile:09",
    "prohibition": [{
        "target": "http://example.com/data:77",
        "assigner": "http://example.com/person:88",
        "assignee": "http://example.com/org:99",
        "action": "index",
        "remedy": [{
            "action": "anonymize",
            "target": "http://example.com/data:77"
        }]
    }]
}
```

**Comment by riannella** [comment]
@vroddon 

"unique" means that the specific instances for that specific constraint operand are not the same.

**Comment by vroddon** [comment]
Thanks! --'unique' concept is now clear to me.

**Comment by vroddon** [comment]
Thanks! --the example now is now more meaningful.

(My experience tells me that many contracts/licenses like imposing constraints on the derivative work. But this is something that can be reflected in the best practices note)

**Comment by riannella** [comment]
Example updated
