### ISSUE TITLE
How much infererence for validation?

### ISSUE THREAD

**Issue by vroddon** [w3c/poe#253]
Please, let us consider this example (written [in May](https://www.w3.org/2016/poe/wiki/Best_Practices)):
```
@prefix odrl: <http://www.w3.org/ns/odrl/2/> .
@prefix dct: <http://purl.org/dc/terms/> .

<http://example.org/policy/1> 
  odrl:permission [
    odrl:target <http://example.com/asset/1> ;
    odrl:assignee <http://example.com/party/Alice> ;
    odrl:action odrl:use
  ] .
```
This simple RDF policy is not validated because in principle no policy is found whatsoever.
A simple inference from odrl:permission's domain (odrl:Policy) would produce the necessary axiom:
`<http://example.org/policy/1> a odrl:Policy ;
`
I like these compact policies, which will be more easily adopted&understood.
But I don't like adding more reasoning burden to the validator. Can we add type inference, as least for some classes?

**Comment by riannella** [comment]
I would assume that a reasoner would infer that <http://example.org/policy/1> is a Policy (as you indicated).

But I don't think we should say a Validator should be an inference engine as well ?

**Comment by vroddon** [comment]
Correct. I understand inference is a previous pre-processing (or normalization or canonicalization) step.
https://www.w3.org/2016/poe/wiki/Validation#Normalization

**Comment by vroddon** [comment]
Please note that RDFS inference is not the only one that is required.
Whereas some SHACL shapes could make use of 
`sh:targetObjectsOf sh:entailment ;`
Some of the preprocessing is needed. For example, the transformation related to "hasPolicy".
A possible task would be to identify exactly which validations require which entailments/normalization transformations.
