### ISSUE TITLE
Wording and RDF semantics: Collection - List - Sequence ...

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#256]
Digging deeper into the RDF behind the *Collection Classes of ODRL for #226 I noticed the IM uses a terminology which is not clear:
* **collection in the IM**: e.g. in 2.2 and 2.3 - "Asset/PartyCollection - an Asset/Party that is a _collection_ of resources." The further definition of the *Collection does not say a word about ordering, it only talks about "all items in the collection" - in terms of RDF 1.1 Semantics, see below, they could be a Collection or a Container.
* **Collection in the RDF 1.1 Semantics** - https://www.w3.org/TR/rdf11-mt/#rdf-collections - is defined as

> RDF provides a vocabulary for describing collections, i.e.'list structures', in terms of head-tail links. Collections differ from containers in allowing branching structure and in having an explicit terminator, allowing applications to determine the exact set of items in the collection.

* ... these "head-tail links" implement in fact an order of the items - and uses the rdf:first and rdf:rest relationships for the links.
* A **Container is in RDF 1.1 Semantics** a kind of enumeration (= Things are only members of the Container but have no relationships among them) - with three specific types
- in an rdf:Bag the Things are not ordered
- in an rdf:Seq the Things are ordered
- in an rdf:Alt the Things are alternatives, only one of them may be used
* **JSON-LD does not use "collection" as a term**, only as an linguistic attribute, e.g. "JSON-LD uses the same array representation as JSON, the _collection_ is unordered by default" (https://www.w3.org/TR/json-ld/ - section 3.1)
* ... but JSON-LD differentiates between unordered arrays (see above) and "ordered collections" (see section 6.11): to make an array ordered the JSON-LD keyword  @list must be used. (I didn't find quickly a clear statement by JSON-LD if a @list is RDFied to a rdf:List or something else.)
* ... and the ODRL IM defines in section 2.5.2 that the @list keyword must be used for the sequence of constraints related to an andSequence.
* The internal confusion in the RDF Universe is 
  * that the RDF 1.1 Semantics document uses different terms in headlines and in the vocabulary: D.3 is headlined and shows an "RDF Collection" but the class representing this is named rdf:List.
  * that JSON-LD uses terms which are coined by RDF 1.1 with different semantics, and free-text like "unordered array" is not related to a corresponding RDF 1.1 term.

I see this **state of not clear definitions in the ODRL IM:**
1. Key issue: I see not strategy to follow the RDF 1.1 terms - which should be a preference as ODRL IM builds on RDF.
2. Currently the RDF expression/serialisation of these "collections" is not defined:
  * AssetCollection
  * PartyCollection
  * ... they are not an ordered list and could be implemented following RDF 1.1 terminology by the RDF Container rdf:Bag.
2. "Half-baked" is Constraint Class - rightOperand - "list of ..."
as it is not clear: is the RDF semantics of rdf:list applied to this list? By what has  been discussed in #255 it could also be an unordered list, an rdf:Bag. And: does an ordered list have to be an rdf:List - or could it be also an rdf:Seq?
3. unclear is 2.5.2 Logical Constraint Class as it uses JSON-LD terminology for a part of the definition:
- the definition of the only property says "... its value is a list of the existing Constraint instances."
- further down for the andSequence is stated, it must use the @list keyword in JSON-LD
- open issue: may the "list of existing ..." related to "or", "xone" and "and" be unordered lists?

What do our RDF experts think about that?

**Comment by simonstey** [comment]
ad1:
> collection in the IM: e.g. in 2.2 and 2.3 - "Asset/PartyCollection - an Asset/Party that is a collection of resources." The further definition of the *Collection does not say a word about ordering, it only talks about "all items in the collection" - in terms of RDF 1.1 Semantics, see below, they could be a Collection or a Container.

despite having similar names, both Asset/PartyCollection have nothing to do with collections in RDF

**Comment by nitmws** [comment]
... I agree at the information model level but then we should clarify that in the used language:
* an instance of *Collection is a single entity by the view of ODRL
* this instance should support a function to check if an identified entity is a member.

**Comment by iherman** [comment]
Some additional facts, @nitmws:


>[…] in terms of RDF 1.1 Semantics, see below, they could be a Collection or a Container.
> * Collection in the RDF 1.1 Semantics** - https://www.w3.org/TR/rdf11-mt/#rdf-collections - is defined as
>
> […] 
> * these "head-tail links" implement in fact an order of the items - and uses the rdf:first and rdf:rest relationships for the links.
> * **A Containerner is in RDF 1.1 Semantics** a kind of enumeration (= Things are only members of the Container but have no relationships among them) - with three specific types
> […]

There is a difference between these two, however. Containers (that was defined in the very first RDF version in the last milleneum whereas Collections came in the current one...) are considered as ill-defined by many. The main issue is that they are not "closed"; in an open world paradigm (of which RDF is part of) it is unknown whether another entity is listed somewhere else for that container, if I follow your analogy with enumerations. The RDF Semantics actually warns:

> “… Since the RDF container vocabulary is so limited, many natural assumptions concerning RDF containers cannot be formally sanctioned by the RDF formal semantics. This should not be taken as meaning that these assumptions are false, but only that RDF does not formally entail that they must be true.”
>
> “… If the container is of an ordered type, then the ordering of items in the container is intended to be indicated by the numerical ordering of the container membership properties, which are assumed to be single-valued. However, these informal conditions are not reflected in any formal RDF entailments.”

Bottom line: _we should to avoid using Containers_. Collections are of course fine.

> […]
> * ... but JSON-LD differentiates between unordered arrays (see above) and "ordered collections" (see section 6.11): to make an array ordered the JSON-LD keyword  @list must be (I didn't find quickly a clear statement by JSON-LD if a @list is RDFied to a rdf:List or something else.)

The RDFization (isn't that a nice word?:-) of a JSON arrays is:

- Without a `@list` it is simply a collection of triples sharing the same object and properties.  I.e., it is _**not**_ an `rdf:Bag`.
- With a `@list`, as you properly say, it is converted into an RDF Collection. (I agree it is not easy to find, it is stated in the last bullet item in https://www.w3.org/TR/2014/REC-json-ld-20140116/#h2_data-model)

> […]
> 
> I see this *state of not clear definitions in the ODRL IM:**
> 1. Key issue: I see not strategy to follow the RDF 1.1 terms - which should be a preference as ODRL IM builds on RDF.
> 2 Currently the RDF expression/serialisation of these "collections" is not defined:
>   * AssetCollection
>   * PartyCollection
>   * ... they are not an ordered list and could be implemented following RDF 1.1 terminology by the RDF Container rdf:Bag.

As said above, we shouldn't do that. 

> 3. "Half-baked" is Constraint Class - rightOperand - "list of ..." as it is unclear: is the RDF semantics of rdf:list applied to this list? By what has  been discussed in #255 it could also be an unordered list, an rdf:Bag. And: does an ordered have to be an rdf:List - or could it be also an rdf:Seq?

Same as above.

> 4. unclear is 2.5.2 Logical Constraint Class as it uses JSON-LD terminology for a part of the definition:
>   * the definition of the only property says "... its value is a list of the existing Constraint instances."
>   * further down for the andSequence is stated, it must use the @list keyword in JSON-LD
>   * open issue: may the "list of existing ..." related to "or", "xone" and "and" be unordered lists?
> 
> RDF experts think about that?

On a very high level, an `AssetCollection` can be a set (in the colloquial sense of the word!) of RDF triples, sharing the subject and the predicate. I would agree with you that the term "Collection" may not be the best term used in conjunction with the RDF terminology; that being said, I am a bit worried about changing the term in that late stage, it may be error-prone.

But I am only an RDF expert, sort of… :-)

**Comment by riannella** [comment]
As Editor, I am seeing no change(s) now proposed here?

**Comment by nitmws** [comment]
I suggest to change the definition of the *Collection sub-class of Asset and Party:

Asset/PartyCollection - **an Asset/Party that is a single resource representing a set of member resources. This indicates that all the members of the set will ... .**

Note: we have to be aware that the two sections about refinement of Asset/PartyCollection use the term "member" heavily. Therefore we must define in the generic definition what a member is and of what it is a member. (And I'm afraid it is too late to rename the partOf property to memberOf.)

Another formal issue: 
* The Asset/Party Class definition defines a partOf property
* The Asset/PartyCollection Class is defined as sub-class of the Asset/Party Class and therefore it inherits all properties of the Asset/Party Class, including partOf ...
* ... was it planned to have a Asset/PartyCollection instance which is a partOf another Asset/Party Collection instance - and this can be nested indefinitely?
* if not: we should define partOf is a property of the Asset/Party Class only and not of any sub-class.

**Comment by riannella** [comment]
Done.

> ... was it planned to have a Asset/PartyCollection instance which is a partOf another Asset/Party Collection instance - and this can be nested indefinitely?

PartOf has Domain of Asset/Party and Range of Asset/PartyCollection

**Comment by nitmws** [comment]
As a Domain includes sub-classes the (endless) nesting is planned.
Good to know ...

**Comment by simonstey** [comment]
> if not: we should define partOf is a property of the Asset/Party Class only **and not of any sub-class.**

you can't simply "override" rdfs semantics

> As a Domain includes sub-classes the (endless) nesting is planned.
Good to know ...

why would someone plan that?

**Comment by vroddon** [comment]
wasn't that ironic? or Michael simply wanted to say "multi-level nesting"?
I observe that the current spec is not saying that there must not be cycles in the collections (whereas for policy inheritance we have a sentence). But this is absolutely unimportant, I think.

**Comment by nitmws** [comment]
An IPTC standard including such an unlimited nesting was categorized by Microsoft and Oracle as "cannot be implemented". Ok, some years ago, but I still hear from people responsible for technical implementations at IPTC members that they do not like an unlimited nesting.
That's only shared experience.

**Comment by simonstey** [comment]
fwiw, a cyclic subclass graph makes all involved classes equal (iirc) because:

A equivalentClass B 
=>
A subclassOf B
B subclassOf A

> wasn't that ironic?

i know

**Comment by simonstey** [comment]
(messed up formatting)

**Comment by nitmws** [comment]
Now I come back to open details of my initial posting: 

What kind of RDF serialization should be be used for the lists of `rightOperand` and `rightOperandReference `?

And is it ok to make the list of RightOperands of a Logical Constraint a @list / rdf:List in all cases? Would make implementations easier.

**Comment by vroddon** [comment]
@simonstey Oh! Again I was not explicit enough. I was not meaning subclassing but partOf:
```
A partOf B
B partOf A
```
But still, the idea is the same :)

> fwiw, a cyclic subclass graph makes all involved classes equal (iirc) because:
> 
> A equivalentClass B
> 
> A subclassOf B
> B subclassOf A

**Comment by vroddon** [comment]
@nitmws 

I understand rdf:List. 

> What kind of RDF serialization should be be used for the lists of rightOperand and rightOperandReference?

A couple of the validations in https://www.w3.org/2016/poe/wiki/Validation will have to change, though

**Comment by riannella** [comment]
Yup, rdf:List

The IM only points out that you must use an ordered list in some specific cases (eg andSequence)

**Comment by nitmws** [comment]
Would it be possible to write this down? Because the free text term "list" does not implicitly map to rdf:List.
(This has a relevance for interoperability: if Policy Creator A uses rdf:Bag, Creator B used rdf:Seq and Creator C used rdf:List for a list with undefined ordering - e.g. list of IRIs with a `rightOperand `- this would be valid by the current IM, but not nice for receivers.)

**Comment by riannella** [comment]
Added to encoding section
