### ISSUE TITLE
IM diagrams issues

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#257]
Simple to solve issue: the Figure 2 diagram of the IM document (of 14 September, morning issue :-) ) names a Rule -- PartyCollection relationship "assingee" - should be "assignee"
And this should be fixed in the Candidate Release.

Not so quickly to solve - and I guess it may be fixed Proposed Recommendation: in Figure 1 lines are going from Action, Asset Collection and Party Collection towards Constraint/Logical Constraint
* this line is only explicitly named as "refinement" for Action --> Constraint
* following the line from the two *Collection boxes to Constraint no name is associated with it. But: relationships from different classes to a single class can have different (property) names - e.g. relationships to the Duty class.
--> is it be possible to move the name "refined" behind the crossing point?
* the line arriving at Constraint/Logical Constraint is in dark red - the colour used only from the subject class Action. The colours of the lines from the Asset Collection - amber - and from the Party Collection - violet - disappear at the crossing point with the line in dark red. 
If the three lines are merged at this crossing point the final leg from this crossing point to the ...Constraint classes should have a different colour, e.g. bright dark blue.

**Comment by riannella** [comment]
fixed

f02c5c842f1ec8b7930f7a3f65a77bbdee5d09f6
