### ISSUE TITLE
source of a *Collection (and also Asset/Party?)

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#258]
The diagrams of Figure 1 and 2 and Examples 16 and 17 show a property named source. But in the definitions of *Collection Classes it is not listed.

#164 brought this property up as RDF (serialisation) requirement  - "not to hijack URIs".

In 2.5.5 and 2.5.6 of the IM a Note tells "... the source property MUST be used to reference the ...Collection." but by the style of definitions in the IM a property of a class should be listed in the section defining a class - even if it is needed for a specific purpose only.

**Questions**: 
1. is the use of source also required for refining an Asset or Party (and not a ...Collection) - or is the direct use of an Asset/Party IRI not hijacking it?
The case of refining a single Asset or Party is not covered in any serialisation example.
2. is the use of source required only for refinements or does this issue "not to hijack URIs" also apply to the use of a *Collection without a refinement?

RDF experts please let us know.

**Comment by iherman** [comment]
Probably an editorial aside, but, in Figure 1, the line going "down" from `source` is unclear. It crosses the line labeled as `refinement` (instead of 'bridging' it), it changes colour at that crossing point, and has no arrow head either way...

CC @riannella

**Comment by nitmws** [comment]
@iherman please have a look into #257 - it covers exactly what you describe here - and I understand this crossing as a point merging the lines (= relationships)

**Comment by iherman** [comment]
@nitmws I am not sure I understand your question. But if I guess it right: the 'URI hijacking' refers to a situation when the same subject is reused on the Semantic Web. E.g., if there is a statement somewhere saying 

``
<https://www.ivan-herman.net/#me> ex:isA ex:computer_scientist .
``

then third parties have to be careful whether they would assign new triples for that subject. Something like

``
<https://www.ivan-herman.net/#me> ex:isA ex:mathematician .
``

may be (sort of) o.k., but

``
<https://www.ivan-herman.net/#me> ex:isA ex:musician .
``

wouldn't be.

I do not think the usage of `source` is problematic. It designates, via a URL, an _object_, which is fine.

B.t.w., the issue of hijacking is really essential (and needs extra care) when the subject is a term in a _vocabulary_. You do not want, for example, to declare in your vocabulary a predicate in _another_ vocabulary to be functional. That may have far reaching consequences if, in this case, OWL inference engines take all statements concerning that predicate into account.

**Comment by riannella** [comment]
Ok, done. Added "source" property in the same style as the rest.

Answer 1 - you can ONLY refine Asset/PartyCollections
Answer2 - you use uid if you just only want to identify a Asset/PartyCollections
