### ISSUE TITLE
ODRL Validation/Validation issues

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#261]
Going over the [ODRL Validation](https://www.w3.org/2016/poe/wiki/Validation) document, 1.2 Validation section I noticed:

1. I suggest to follow the spelling of classes and properties in the IM: classes starting with uppercase characters (Rule, Constraint, Duty), properties with lowercase characters. That's a big issue as we have names of classes and properties where only the case of the first characters is making the difference: Duty - duty.
1. Use of plural: I suggest to use, primarily in the headers, the singular of classes, properties etc. Why: it is not clear if the raised issue applies to each item of the pluralised things or to the set of all of them. Example: "... rules must have exactly one assignee" (does that mean: the 20 rules in a policy must have the same single assignee?)  should be replaced by "... each rule must have exactly one assignee".
2. How to check what kind of class is referenced by a property
"Policies must have at least one rule" does this check by testing if one of the properties odrl:permission, odrl:prohibition, or odrl:obligation exist. But what if they reference an instance of the Action and not the Rule class? (Note: in my ODRL testground I expand the JSON-LD IM examples with @context to JSON-LD without context - by https://www.npmjs.com/package/jsonld - and this expanded JSON-LD does not show the type of the value referenced by e.g. odrl:permission.)
3. Headers "Source and AssetCollections" and "Source and PartyCollections" : append "... with refinements" as this is the essential part
4. re "Constraints must have exactly one rightOperand" - more a question: the IM [defines as value of rightOperand](http://w3c.github.io/poe/model/#constraint-class) a single item or a list of items. Does SHACL understand a list as a single thing?
5. *:DATATYPE: I guess this must be *:datatype

**Comment by vroddon** [comment]
@nitmws Even if the ODRL Validation document was informally written, I have made an effort to be more rigurous and follow your guidelines. In particular:

-  OK to the use of singular and plurals
-  OK to the capitalization of defined terms, except in the titles to gain clarity. In addition fixed-size font has been used to refer to ODRL elements.
-  Types are declared at least after one of the normalization steps. Most of them can be inferred from domain/range by an RDFS reasoner, Set cannot; Collections doubtfully.
- I have improved the titles, I think.
- rdf:DATATYPE and odrl:DELETE are formatted this way by the Wiki system.
- I have implemented the first of the transformations as a SPARQL Update query. However, I cannot do this for the five transformations --especially the Policy Inheritance algorithm, which is relatively complex.

**Comment by nitmws** [comment]
@vroddon almost perfect: some "rule" should be "Rule" and "a duty that includes a consequence duty" --> "a Duty that includes a consequence Duty"

As this document is now part of the ODRL CR Test Regime it may be formally informal but implementers will need it!

I come back to my item 5 above: is a list understood as single thing by SHACL?

re rdf:DATATYPE: a quick googling didn't show a solution ... knows anybody one as in fact things with that identifier do not exist. Copy and pasting will cause errors.

**Comment by vroddon** [comment]
Please feel free to edit the wiki.

Given that the value for rightOperand can be either literal or IRI, the only validation I can think of is:
"_It cannot be a blank node whose type is not RightOperand_".

Consequently, the new sample I have just uploaded (sample076, see below) is not being correctly parsed, I guess that according to the spec this should be invalid. I wonder whether it worths imposing these extreme validations.

```
@prefix odrl: <http://www.w3.org/ns/odrl/2/> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

#invalid. rightOperand is a blank node and has no type RightOperand
<http://odrlapi.appspot.com/samples/sample076>
    dct:source "victor" ;
    a odrl:Offer ;
    odrl:profile <http://example.com/odrl:profile:07> ;
    odrl:permission [
        odrl:target <http://example.com/game:9090> ;
        odrl:assigner <http://example.com/org:xyz> ;
        odrl:action odrl:play ;
        odrl:constraint [
            odrl:leftOperand odrl:dateTime ;
            odrl:operator odrl:lteq ;
            odrl:rightOperand [
                rdfs:comment "Right operand without URI"
            ]
        ]            
    ] .

```
RDF question: yes. You can try this examples in the validator. This is valid (the parenthesis are to use rdf:list):
```
        odrl:constraint [
            odrl:leftOperand odrl:dateTime ;
            odrl:operator odrl:lteq ;
            odrl:rightOperand ("a" "b")
        ]    

```

But this is invalid:

```
        odrl:constraint [
            odrl:leftOperand odrl:dateTime ;
            odrl:operator odrl:lteq ;
            odrl:rightOperand "a" ;
            odrl:rightOperand "b"
        ]  
```
I don't think I understand the problem about http://www.w3.org/2000/01/rdf-schema#Datatype.
I read the https://www.w3.org/TR/swbp-xsch-datatypes/ page, but... where is the actual problem? (if it is only the format presentation, then we simply comment on it)

**Comment by riannella** [comment]
@vroddon The spec says "... one rightOperand property value..." - so there MUST be a value there, not just the property. So your first example above must be found to be invalid.

**Comment by vroddon** [comment]
@riannella The problem is that technically, rightOperand has only one value. The example is better seen as N-TRIPLES.
```
@prefix odrl: <http://www.w3.org/ns/odrl/2/> .
@prefix ex: <http://www.example.com> .

ex:A odrl:rightOperand ("a" "b") .
```
is translated as:
```
_:genid1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "a" .
_:genid1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:genid2 .
_:genid2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "b" .
_:genid2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
<http://www.example.comA> <http://www.w3.org/ns/odrl/2/rightOperand> _:genid1 
```

There is only one triple using rightOperand

**Comment by simonstey** [comment]
fwiw, those shapes check whether a rightoperand is either _a literal, or IRI [rfc3987], or RightOperand;_ or a well-formed RDF list:
```turtle
odrl:ROShape
  a sh:NodeShape ;
  sh:targetObjectsOf odrl:rightOperand ; 
  sh:xone ( 
    [ 
      sh:or ( 
        [ sh:nodeKind sh:IRIOrLiteral ] 
        [ sh:class odrl:RightOperand ] # redundant?
      )
    ]
    [ sh:node odrl:ListNodeShape ]
  ) .

odrl:ListNodeShape
  a sh:NodeShape ;
  sh:or ( 
    [
      sh:hasValue rdf:nil ;
      sh:property [
        sh:path rdf:first ;
        sh:maxCount 0 ;
      ] ;
      sh:property [
        sh:path rdf:rest ;
        sh:maxCount 0 ;
      ] ;
    ]
    [
      sh:not [ sh:hasValue rdf:nil ] ;
      sh:property [
        sh:path rdf:first ;
        sh:maxCount 1 ;
        sh:minCount 1 ;
      ] ;
      sh:property [
        sh:path rdf:rest ;
        sh:maxCount 1 ;
        sh:minCount 1 ;
      ] ;
    ] 
  ) .
```

(listshape was taken from https://www.w3.org/TR/shacl/#shacl-shacl)

**Comment by riannella** [comment]
This can be closed now
