### ISSUE TITLE
Problem in JSON-LD?

### ISSUE THREAD

**Issue by vroddon** [w3c/poe#263]
The JSON-LD examples are not being correctly parsed. 
If you try [easyrdf](http://www.easyrdf.org/converter) or [rdf-translator](http://rdf-translator.appspot.com/) you will see that examples have stopped being correctly parsed. 

```
{
"@context": {
    "odrl": "http://www.w3.org/ns/odrl.jsonld"
    },
    "@type": "odrl:Set",
    "@id": "http://example.com/policy:1010",
    "permission": [{
        "target": "http://example.com/asset:9898",
        "action": "odrl:read"
    }],
    "prohibition": [{
        "target": "http://example.com/asset:9898",
        "action": "odrl:reproduce"
    }]
}
```

is converted into:

`<http://example.com/policy:1010> a <http://www.w3.org/ns/odrl.jsonld#Set> .`

**Comment by iherman** [comment]
I cannot really look at the context file on an iPAD, but I succeeded to have look. I have the impression that this is the ontology file in json-ld rather than a context file. It seems that there has been some mistake when the content of '/ns' was updated a few days ago.

@riannella, can you check and tell me what I should change?

**Comment by riannella** [comment]
Everything is fine if you set the context and namespace separately:

```
"@context": [
        "http://www.w3.org/ns/odrl.jsonld",
        { "odrl": "http://www.w3.org/ns/odrl/2/" }
    ],
```

**Comment by vroddon** [comment]
@riannella Thanks! The example below now works perfectly well. 
Maybe we don't need to change the IM example, but perhaps we can give the hit you wrote somewhere.
```
{
"@context": [
        "http://www.w3.org/ns/odrl.jsonld",
        { "odrl": "http://www.w3.org/ns/odrl/2/" }
    ],
    "@type": "odrl:Set",
    "@id": "http://example.com/policy:1010",
    "permission": [{
        "target": "http://example.com/asset:9898",
        "action": "odrl:read"
    }],
    "prohibition": [{
        "target": "http://example.com/asset:9898",
        "action": "odrl:reproduce"
    }]
}
```
