### ISSUE TITLE
fixing selected examples

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#268]
https://w3c.github.io/poe/model/#constraint-rule **Example 13**:
> Example Use Case: In the Policy Offer example below, the permission allows the target asset to be distributed, and includes a constraint of a dateTime condition **that the permission must be exercised** before 2018-01-01.

**must** makes it an obligation => s/must be exercised before/can only be exercised until

-----

https://w3c.github.io/poe/model/#duty-perm **Example 22**:
> [...] The duty also has a constraint of event is less than policyUsage, meaning the duty rule must be exercised (ie the compensation) **before the permission rule can be exercised.** 

https://w3c.github.io/poe/vocab/#term-policyUsage: 
> This can be used to express constraints related to the time the policy is exercised. For example,  event lt policyUsage expresses a constraint on the Action to occur **before the policy is exercised.**

=> if a policy has >= 2 rules, when is it considered to be exercised?

-----

https://w3c.github.io/poe/model/#metadata **Example 30** isn't formatted properly

**Comment by riannella** [comment]
Example 13 fixed.

Fixed policyUsage: should be "rule"

Fixed Ex 30
