### ISSUE TITLE
inconsistent requirements wrt. profile definitions

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#272]
**[A]** http://w3c.github.io/poe/model/#policy:
> + A Policy MAY have **none**, one, or many profile property values (of type IRI [rfc3987]) to identify the ODRL Profile that this Policy conforms to. (See the ODRL Profiles section for more details.)
> [..]
> 
> An ODRL Policy must **either**:
> + Only use terms defined in the ODRL Core Vocabulary [odrl-vocab], **or**
> + Use an ODRL Profile that declares the supported vocabulary used by expressions in the Policy.
>
> **In the former case, the profile property MUST NOT be used.** In the latter case, the profile property MUST be used to indicate the IRIs of the ODRL Profile(s). 

----

**[B]** http://w3c.github.io/poe/model/#profile-conformance:
> In an ODRL Policy, the profile property MUST be specified to indicate the identifier (IRI) of the ODRL Profile for which the Policy expression conforms to.

----

**[C]** http://w3c.github.io/poe/model/#profile-core: 
> In circumstances that require the ODRL Core Profile to be identified, **that is the Policy only conforms to the ODRL Core Vocabulary**, then the following identifier MAY be used for the Core Profile: http://www.w3.org/ns/odrl/2/core

----

=> it's not possible to conform to **[A,B,C]** all at the same time

**Comment by nitmws** [comment]
(I guess this comes from the step-by-step progress in the understanding and specification of profile.)

I suggest:
* all the wordings have a key issue: there are the ODRL IM and the Core Vocabulary/Profile each and every ODRL Policy has to conform to ... but this may be **extended** (and not be replaced!) by using a Profile!
Therefore: a Profile has only to include terms which are not already defined by the ODRL Core IM/Vocabulary/Profile.
* [A] is the latest specification. Should be adjusted to clarify the role of a Profile as extending the ODRL Core (which is well explained in [3.1 profile purpose](http://w3c.github.io/poe/model/#profile-motivation)), e.g.
A Policy may have none, one, or many profile property values (of type IRI [rfc3987]) to identify the ODRL Profile that this Policy conforms to **beyond the ODRL Core Vocabulary. In the case of no profile property the Policy has to conform to the ODRL Core Vocabulary.** 
* [B] needs a rewording like 
In an ODRL Policy, the profile property MAY be used to indicate the identifier(s) (IRI) of the ODRL Profile(s) the Policy conforms to beyond the ODRL Core. There may be multiple identifiers used to indicate that an ODRL Policy conforms to multiple ODRL Profiles.
* [C] is a tricky thing: in the current IM there is no clear and explicit statement like "the ODRL IM is the default profile of any ODRL Policy". Having such a statement in [A] - see above - this [C] would be quite ok. I only suggest to remove " that is the Policy only conforms to the ODRL Core Vocabulary", may cause confusion, I see real need.

(Footnote: what @simonstey has pointed at is a general problem with the IM: pieces of knowledge and specification about the same topic are spread across multiple sections. This doesn't make reading and understanding easier and it is apparently hard for the WG to make the document consistent.)

**Comment by riannella** [comment]
I have updated the narrative now to make the intentions clearer.
