### ISSUE TITLE
Common Vocabulary Concepts/Terms used/referenced in Core Vocabulary Section

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#273]
https://w3c.github.io/poe/vocab/#policyConcepts:
> 3 ODRL Core Vocabulary
The ODRL Core Vocabulary defines the semantics for the concepts and terms from the ODRL Information Model [odrl-model]. The ODRL Core Vocabulary represents the minimally supported terms for ODRL Policies.
>
> 3.1 Policy
3.1.1 Policy
  Sub-classes: Agreement, **Assertion**, Offer, **Privacy**, **Request**, Set, **Ticket**

=> Concepts/Terms that are not part of the Core vocab. should either be (manually) removed from Section 3 or appropriately annotated/flagged.

**Comment by riannella** [comment]
That would "break" the semantic linkages between the classes/properties.

The non-core classes are not being **defined** in section 3 (only referenced) - they are defined in section 4.

**Comment by nitmws** [comment]
I've created presentations about ODRL for IPTC meetings and it is really hard to provide an easy to follow distinction between terms from the Core Vocabulary and the Common Vocabulary:
* both are of the same namespace
* such a linking like in 3.1.1 does not help to make a distinction.
* one has to check if a term with the ODRL namespace URI is listed in chapter 3 or 4.

Question: is it really required to list the Policy sub-classes from the Common Vocabulary in 3.1.1? I guess any sub-class defined by a Profile will not show up in 3.1.1, so why these ones?

**Comment by riannella** [comment]
Answer: Keeping them there shows the ontology relationships.

If we remove them, then we need to remove all references to common terms in the core, like:
  https://w3c.github.io/poe/vocab/#term-use
  https://w3c.github.io/poe/vocab/#term-function
etc

Even the parent classes of:
  https://w3c.github.io/poe/vocab/#partyConcepts
etc

**Comment by riannella** [comment]
Proposed resolution: do nothing
