### ISSUE TITLE
Error in the ODRL JSON-LD context resource

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#277]
@vroddon and I have been working on the transformation of Turtle RDF used on the [Validation page](https://www.w3.org/2016/poe/wiki/Validation) into JSON-LD RDF - and ran into errors, even when using the  jsonld.js Node.js module created by the JSON-LD people. 
I raised a Github issue there https://github.com/digitalbazaar/jsonld.js/issues/201# and got this response:

The problem is the following constructs in ODRL22.jsonld:

> "uid":     {"@type": "@id", "@id": "@id"},
> "type":    {"@type": "@id", "@id": "@type"},

uid isn't even being used but those constructs are apparently not handled well with any recent jsonld.js (recent 0.4.x or dev 0.5.x). Are you just trying to setup aliases for @id and @type? The following change will do that:

> -    "uid":     {"@type": "@id", "@id": "@id"},
> -    "type":    {"@type": "@id", "@id": "@type"},
> +    "uid":     "@id",
> +    "type":    "@type",

@dlongley @gkellogg: Does the above have defined behavior or should implementations error on it? If it's defined then we should add some test suite tests for it. If not, should this be defined in 1.1 or what should implementations do? Clearly jsonld.js shouldn't be spitting out "undefined" nonsense when this happens. Would be better to just have an error.

(see https://github.com/digitalbazaar/jsonld.js/issues/201#issuecomment-334816999)

**Result: the ODRL context file/resource - http://www.w3.org/ns/odrl.jsonld - should be fixed**

(This change to the ODRL context shows correct in the results of a test software for this transformation:  https://github.com/nitmws/rdf-jsonld-transformation-test1)

**Comment by iherman** [comment]
@nitmws do you have a confirmation about those? I can do the changes and, at the end of the day, I will have to push it up to /ns...

**Comment by nitmws** [comment]
@iherman what kind of confirmation do you expect?
* the advice was given by David I. Lehn, working for Digital Bazaar - https://github.com/davidlehn
* I have applied the suggested change to a copy of the ODRL-context in a test application created for the purpose of transforming ODRL Turtle to JSON-LD and the *=compact.json files in https://github.com/nitmws/rdf-jsonld-transformation-test1/tree/master/testdata show the expected results: no "undefined" properties and the uid property and others where we expect it. (The modified context file is at https://github.com/nitmws/rdf-jsonld-transformation-test1/blob/master/ODRL22.jsonld)

This is what we have on the table.

**Comment by iherman** [comment]
Sorry @nitmws, there were two threads (this one and one on the mailing list) and I was not sure of the status.

I have updated /ns/odrl.jsonld and, of course, the version on the repo with a copy of yours.

If it works now, the issue can be closed...

**Comment by nitmws** [comment]
From my side this change solves the problems I noticed but I would be happy to see a response from @vroddon as he told me "the ids of the blank nodes are not working well" - then I created this transformation tool and this transformation tool showed "undefined" instead of "uid". Do the ids of the blank nodes in Victors system work well now?

**Comment by vroddon** [comment]
Well, the automatic transformation was generating named blank nodes. We want them really "anonymous".

**Comment by vroddon** [comment]
I am no expert at JSON-LD.
I have, however, updated the JSON samples at http://odrlapi.appspot.com/ with the transformation provided by @nitmws 

Can we close this issue?

**Comment by iherman** [comment]
Please do!

Ivan

---
Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by nitmws** [comment]
@vroddon did not raise objections - issue closed
