### ISSUE TITLE
IM: Constraint and Logical Constraint do not have a uid property

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#278]
Having a look at the IM Editor Draft of 11 October, [Constraint section](http://w3c.github.io/poe/model/#constraint):
For the Logical Constraint the values of the operand are defined as "its value is a list of the existing Constraint instances." 
Example 15 shows this example of an "existing Constraint instance" as:
```
{
...
               "xone": [ { "@id": "http://example.com/p:88/C1" },
                         { "@id": "http://example.com/p:88/C2" } ]
...}

{
   "@context": "http://www.w3.org/ns/odrl.jsonld",
   "@type": "Constraint",
   "uid": "http://example.com/p:88/C1",
   "leftOperand": "media",
   "operator": "eq",
   "rightOperand": "online"
}

```
By the IM definitions this Constraint instance is **invalid** as the 2.5.1 Constraint Class does NOT define a uid property. On the other hand a Logical Constraint operand needs identifiers to refer to Constraints.

**Conclusion**: currently Constraint and Logical Constraint instances can only have an auto-generated blank node id, it is not possible to set an identifier explicitly. 
**Suggestion**: the Constraint class and also the Logical Constraint Class must have a uid property.

**Comment by iherman** [comment]
Just noting... this does not seem to be an editorial change:-(

**Comment by nitmws** [comment]
I'm afraid this is the case. Then we need a quick action on that.

**Comment by iherman** [comment]
> 
> I'm afraid this is the case. Then we need a quick action on that.
> 

s/quick/very quick/

**Comment by simonstey** [comment]
uid's are a legacy concept of ODRL's XML serialization anyway (as discussed in #174) and "replaced" in our context file with `"uid":     "@id",`

**Comment by riannella** [comment]
It is an "editorial" oversight as **uid** appears in the Model for Constraint (see Figure 1) and all the examples. (we can easily add this)

Logical Constraint does not require a uid, as the operand has:  "its value is a list of the existing Constraint instances." 
(See Example 15 in the IM)

**Comment by nitmws** [comment]
Warning: if a Logical Constraint does not have a way of explicitly setting its identifier then it is impossible to explicitly reference a Logical Constraint from somewhere else. And: in fact each node must have an identifier, if no uid a Logical Constraint can only used as a nested JSON-LD node, then a software has to assign a blank node id.

**Comment by simonstey** [comment]
it has.. in jsonld you can use `@id`

**Comment by nitmws** [comment]
@simonstey you are right. But why does ODRL have a defined uid property at all which is a renamed @id as the @context defines?

**Comment by riannella** [comment]
Yes, we get some free stuff from JSON-LD (@id can be used), and RDF has the same rdf:ID etc.
In the XML, we use xml:id

**Comment by nitmws** [comment]
* It is an [explicit requirement of RDF](https://www.w3.org/TR/rdf11-concepts/#section-triples) that each triple MUST have a "_subject, which is an IRI or a blank node_".
* It was a decision of this WG to build POE ODRL on top of RDF.
* Therefore JSON-LD is an implicit option for ODRL syntax and [JSON-LD defines the keyword](https://www.w3.org/TR/json-ld/#syntax-tokens-and-keywords) @id "_used to uniquely identify things that are being described in the document with IRIs or blank node identifiers_"; can be used as identifier of the subject of a triple.
* For a better compatibility with earlier ODRL versions the ODRL-internal name uid was adopted for identifiers and the JSON-LD @context at http://www.w3.org/ns/odrl.jsonld defines already that uid is transformed/renamed to @id 

By that I conclude that it is primarily an editorial error that no uid is defined for Constraint and Logical Constraint as these classes MUST have an identifier for the subject (= an instance of the class) and re-using the definition of uid used for other classes does not change the IM in any way.
Therefore I suggest to add the uid property name to Constraint and Logical Constraint as correction of an editorial error as it is a goal of a Recommendation to express the same thing in a consistent way across a document. (Using uid for some classes and @id for Constraint & Logical Constraint generates the same result in terms of RDF triples but is not consistent for the ODRL user.)

**Comment by riannella** [comment]
I think we all agree, but the ODRL IM does not mention the need for a uid for the Logical Constraint class, as there is no need for it (from an IM perspective).

If you look at Example 15 (https://w3c.github.io/poe/model/#constraint-action)
how would that work with a uid for the xone logical constraint?

**Comment by nitmws** [comment]
@riannella this way:

```
{
...
        "action": [{
           "rdf:value": { "@id": "odrl:reproduce" },
           "refinement": { "uid": "http://example.com/locos/LC1" }
        }]
...
}

{
   "@context": "http://www.w3.org/ns/odrl.jsonld",
   "@type": "LogicalConstraint",
   "uid": "http://example.com/locos/LC1",
   "xone": [ { "@id": "http://example.com/p:88/C1" },
             { "@id": "http://example.com/p:88/C2" } ]
}

{
   "@context": "http://www.w3.org/ns/odrl.jsonld",
   "@type": "Constraint",
   "uid": "http://example.com/p:88/C1",
   "leftOperand": "media",
   "operator": "eq",
   "rightOperand": "online"
}
etc ...
```
What is shown above is in fact done by any JSON-LD library in the transformation from Compacted to Expanded JSON-LD and this is a prerequisite for transforming that into N-Quads - see the lower box at https://json-ld.org/playground/ : it splits up the nested syntax into standalone graphs.

As I said this is done by any Compacted to Expanded transformation, in this case the hand-made id `http://example.com/locos/LC1` is is set to a blank node id like `_:b99` by the internal processor of the transformator.

If the Logical Constraint would have a uid this would be possible:
* the same Logical Constraint is used by 6 Rules of a Policy
* the Logical Constraint graph is defined outside the Policy graph - but inside a "Policy and other graphs"-RDF Dataset.
* ... and all 6 Rules could (re-)use the Logical Constraint by a  `"constraint": { "uid": "http://example.com/constraints/C100" } `
* and to make this crystal clear: a `"constraint": { @id: "http://example.com/constraints/C100" }` is semantically exactly the same - only an @id has to be used instead of uid. 

Therefore is strongly suggest for the sake of a consistent ODRL syntax across all classes: let's define a uid property for Locial Constraint as it is defined for the other classes.

**Comment by simonstey** [comment]
> @simonstey you are right. But why does ODRL have a defined uid property at all which is a renamed @id as the @context defines?

#111 :(

**Comment by nitmws** [comment]
A reason was to use a property name which can also be used for the XML serialization, "@id" does not support that. This group should be aware of some existing ODRL 2.0/2.1 implementations using XML and we should invite them to switch to W3C ODRL without having to kill XML. (This is what I do currently inside IPTC.) 
We could have discussed earlier if a mapping from JSON-LD syntax to XML should be defined - a kind of XML context - but now we can't and we should support a consistent mapping of @id = uid = @id for all nodes in ODRL.

**Comment by riannella** [comment]
Updated IM with uid property for the Constraint classes and the domain in the vocab

**Comment by iherman** [comment]
Does this change affect test cases? Does this change affect any implementation out there that we may not even know about?

Bottom line: is this an editorial or a substantial change?

**Comment by riannella** [comment]
No change to test cases (= editorial)

**Comment by nitmws** [comment]
Footnote from digging into the JSON-LD @context details: the ODRL @context had in its CR version already a mapping `"uid" : "@id"` (with the known problem regarding syntax details). As such a mapping applies to the use of "uid" with any node even the @context does not have to be edited/changed to support uid for the Constraint classes.

**Comment by nitmws** [comment]
Re test cases: actually it is the other way round. Examples in the IM - used as test cases -  used uid already while it was not defined in the normative part of the IM.

**Comment by iherman** [comment]
@nitmws one could then argue that the test cases were wrong...
