### ISSUE TITLE
Update Example 14

### ISSUE THREAD

**Issue by riannella** [w3c/poe#281]
Example 14 does not clearly represent a refinement:
    http://w3c.github.io/poe/model/#constraint-action

Update example

**Comment by riannella** [comment]
What if we change the example to:

```
    "action": [{
          "rdf:value": { "@id": "odrl:print" },
          "refinement": [{
             "leftOperand": "resolution",
             "operator": "eq",
             "rightOperand": { "@value": "72", "@type": "xsd:integer" }
          }]
```

**Comment by simonstey** [comment]
> Example 14 does not clearly represent a refinement:

why?

**Comment by riannella** [comment]
Because it is not really "refining" the semantics of printing?
(percentage is  an Asset refinement)

**Comment by riannella** [comment]
Updated.
Also added a "unit"

**Comment by simonstey** [comment]
> Because it is not really "refining" the semantics of printing?
(percentage is an Asset refinement)

while `odrl:percentage` is indeed listed under [Asset Percentage](http://w3c.github.io/poe/vocab/#term-percentage) in the vocab, ODRL doesn't distinguish between different "types" of refinements (i.e. leftOperands). Or how does one know that [Asset Percentage](http://w3c.github.io/poe/vocab/#term-percentage) and [Rendition Resolution](http://w3c.github.io/poe/vocab/#term-resolution) can be used as **Asset** refinement and **Action** refinement respectively, only?

**Comment by riannella** [comment]
Since the introduction of refinements to the IM, there was no accompanying proposal to split the LeftOperands.

One assumes this is done by ensuring the semantics of the leftOperand refinement makes sense on the action (just like the constraint too).

**Comment by nitmws** [comment]
A comment with my IPTC hat: recently we had a long discussion about such refinements for sport competitions in our news classification taxonomy Media Topics. Our taxonomist pointed at a long-time approach to refining semantics called facet of a concept. And they claimed that we should not only define facets like "team size" but also set a relationship to all sport competitions to which this facet can be applied - e.g. to variants of soccer (outdoor, indoor) but not to alpine skiing slalom.
Conclusion: it would be of practical help for users if such a relationship could be set to leftOperands.

**Comment by riannella** [comment]
Taxonomists are great ;-)

A new issue should be raised for this change/
