### ISSUE TITLE
Review definitions of LeftOperands in the Common Vocab

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#284]
The IM claims in 2.5.1 “The leftOperand instances MUST clearly be defined to indicate the semantics of the Constraint, and MAY declare how the value for comparison has to be retrieved or generated.”

Some current definitions of [LeftOperands of Constraints in the Common Vocab](http://w3c.github.io/poe/vocab/#constraintLeftOperandCommon)  do not this requirement, e.g.
* Count: "Numeric count." -- count of what? 
* Datetime: "The date (and optional time and timezone) to be compared." -- this is the timestamp of what?

And a few are even wrong:
* Version: "The range of versions of the Asset."
Note: "Version 2.0 or higher" is <odrl:version> <odrl:gteq> "2.0" - but apparently the odrl:version stands for  a specific version and not a range of versions.

... etc.

As the Common Vocabulary cannot be changed after a Proposed Recommendation such wording issues should be solved by the first week of December, following the WG's current timeline.

**Comment by nitmws** [comment]
Ok, as Editor of the Vocab I guess I should suggest required changes.
(Typographical note: inserted/changed language in **bold**)

I went over [4.5 Constraint Left Operands](http://w3c.github.io/poe/vocab/#constraintLeftOperandCommon) of the Vocab Editor's draft of 18 November, the number below follows the Vocab document.

1. Absolute Asset Position: sounds ok, refers to the Asset
2. Absolute Spatial Asset Position: sounds ok, refers to the Asset
3. Absolute Temporal Asset Position: sounds ok, refers to the Asset
4. Absolute Asset Size: sounds ok, refers to the Asset
5. Count: refers to nothing; I suggest: "Numeric count **of executions of the action of the Rule**"
6. Datetime: refers to nothing, I suggest: "The date (and optional time and timezone) **of exercising the action of the Rule**. ..."
7. Delay period: refers to nothing, I suggest: "A time delay period **prior to exercising the action of the Rule**. The point in time triggering this period MAY be defined by another temporal Constraint **combined by a Logical** Constraint (utilising the odrl:andSequence **operand**). ..."
8. Delivery Channel: not completely clear, a refined definition is "The delivery channel used **for exercising the action of the Rule**."
9. Elapsed Time: refers to nothing, I suggest: "A continuous elapsed time period **which may be used for exercising of the action of the Rule**." (Hm, what exactly is the difference between Elapsed Time and Metered Time? I assume: Elapsed Time is a single continuous period opening a time slot which may be used for exercising the action while Metered Time may be a collection of many different measured periods used for exercising the action.)
10. Event: refers to nothing, I suggest "An identified event **setting a context for exercising the action of the Rule**."
11. File Format: refers only indirectly, I suggest "A transformed file format **of the Asset**."
12. Industry Context: refers to nothing, I suggest "A defined industry sector **setting a context for exercising the action of the Rule**." 
13. Natural Language: refers to nothing, I suggest: "A natural language **used by the Asset**."
14. Media Context: refers to nothing, I suggest: "Category of a media asset **setting** a context **for exercising the action of the Rule**." 
15. Metered Time: refers to nothing, I suggest "An accumulated amount of **one to many metered** time period**s which were used for exercising the action of the Rule**." (See my comment on Elapsed Time.)
16. Pay Amount: this is a constraint to be used for refinements, I hand this over to #282 
17. Asset Percentage: refers to Asset only by the label, I suggest "A percentage amount **of the Asset relevant for exercising the action of the Rule.**"
18. Product Context: refers to nothing, I suggest: "**Category of** product or service **setting a context for exercising the action of the Rule**.
19. Purpose: refers to nothing, I suggest "**The** purpose **for exercising the action of the Rule**."
20. Recipient: slight modification "The party receiving the result/outcome **of exercising the action of the Rule**."
21. Relative Asset Position: sounds ok, refers to the Asset
22. Relative Spatial Asset Position: sounds ok, refers to the Asset
23. Relative Temporal Asset Position: sounds ok, refers to the Asset
24. Relative Asset Size: sounds ok, refers to the Asset
25. Rendition Resolution: sounds ok, refers to the Asset
26. Geospatial Named Area: unclear what it refers to, I suggest: "A named and identified geospatial area with defined borders **which is used for exercising the action of the Rule**. ..."
27. Geospatial Coordinates: this is a narrower term of 26. , I suggest to align it: "A set of coordinates setting the borders of a geospatial area **which is used for exercising the action of the Rule**. ..."
28. System Device: refers to nothing, I suggest: "An identified computing system **which is used for exercising the action of the Rule**."
29. Recurring Time Interval: refers to nothing, I suggest. "A recurring period of time **before the next execution of the action of the Rule**. ..."
30. Unit Of Count: refers to nothing and is semantically linked to Count, I suggest: "The unit of measure used for counting **the executions of the action of the Rule**.
31. Version: the definition refers to the Asset, but in a way which cannot be used for a constraint. I suggest "**The version of the Asset**".
32. Virtual IT Communication Location: refers to nothing, I suggest: "An identified location of the IT communication space **which is relevant for exercising the action of the Rule**.

... and I continue with a review of 4.6 Constraint Right Operands
1. Policy Usage Time and definition: "Indicates the time when the policy rule is exercised."
Sorry, but that is a mix of many things, the key issue is: definition and note talks about exercising a Rule, the label and the identifier talks about the Policy - that does not fit! As a Policy cannot be exercised I suggest:
  Re-identify the RightOperand by http://www.w3.org/ns/odrl/2/ruleExercise
  Label: Rule Action Exercise Time
  Definition: "Indicates the (date and) time when the action of the Rule is exercised."
  Note: sorry I don't understand it. How can a Constraint require that the action of a Rule is exercised before the Rule is exercised?? What does it mean "a Rule is exercised"?
?? What is the POE use case requiring to add this RightOperand?

**Comment by riannella** [comment]
I agree with the editorial changes noted in 1 to 32 above (thanks!)

**Comment by riannella** [comment]
As for "Policy Usage Time"...

This is a rightOperand, so will be the **value** for a leftOperand Constraint - it is not a Constraint itself.

The use case was to support "paying $X before playing the video" when you don't know what the "before" datetime is and don't want to specify a specific datetime.

Suggest that the Label (only) be updated to "Policy Rule Usage" and the definition "Indicates the actual datetime the action of the Rule was exercised"

**Comment by nitmws** [comment]
@riannella I'm aware of the role of a rightOperand - but we should narrow down the definition to exercising the action. Your modified definition sounds ok.
A second thought: what if the action may be exercised multiple times? Should we say "Indicates the actual datetime the action of the Rule was exercised **last time.**" ?

**Comment by riannella** [comment]
The definition would be contextualised to the current action rule execution.

It would not be aware that the rule could be exercised multiple times.

**Comment by nitmws** [comment]
While editing the odrl22.ttl I noticed a detail of some LeftOperand definitions: the use the language "... of the Asset." An uppercase Asset stands for the Asset class which has no implicit relationship with a Rule and a Rule does not have an asset property, only the target property refers to an Asset. To make it unambiguous  what is meant by "Asset" I inserted target -->> "... of the **target** Asset."

**Comment by riannella** [comment]
I suppose more precisely it would be the "relation" Asset (of which _target_ is a sub-property of _relation_)

And since target would be used about 99% of the time, that makes sense.

**Comment by riannella** [comment]
Completed
