### ISSUE TITLE
Informative references to schema, vcard, & foaf

### ISSUE THREAD

**Issue by iherman** [w3c/poe#285]
A number of vocabulary items in section 3 of the vocab documents (eg, Party) declares itself to be a subclass of various foaf, schema, and vcard classes. Section 3 is normative, but these classes are referred to as informative. It is better to add, at the beginning of the section, a statement of the sort:

> Any reference to vocabulary items other than ODRL terms are considered to be informative.

I do not believe that has any effect on any implementations.

(This issue came up during the PR transition discussion with the Director.)

**Comment by riannella** [comment]
I have made this change and updated the Vocab snapshot

**Comment by riannella** [comment]
Completed
