### ISSUE TITLE
Typos in the PR document of ODRL Information Model 2.2

### ISSUE THREAD

**Issue by iherman** [w3c/poe#288]
(Recording the issue originally [submitted by email](https://lists.w3.org/Archives/Public/public-poe-comments/2018Jan/0000.html) but Shuji Kamitsuna)

Dear Sir and Madam

This is Shuji Kamitsuna@Japan.

I found some possible typos below in the PR document of ODRL Information Model 2.2. at
https://www.w3.org/TR/2018/PR-odrl-model-20180104/

* [x] Sec. 2.3.1: "the recipient the Rule" might be "the recipient of the Rule". 
* [x] Sec. 2.3.3, in the Example Use Case: "would the assignee" might be "would be the assignee". 
* [x] Sec. 2.6: "disjoint will all other..." might be "disjoint with all other...". 
* [x] Sec. 2.6.7, in the Example Use Case: "will be that the MUST" might be "will be that it MUST" or "will be that he/she MUST". 
* [x] Sec. 3.3: "a subclass the ODRL Policy class" might be "a subclass of the ODRL Policy class". 

Thank you for the great specification!

Cc: @riannella

**Comment by riannella** [comment]
Updated
