### ISSUE TITLE
Use HTTPS for examples?

### ISSUE THREAD

**Issue by edent** [w3c/poe#290]
I appreciate that this isn't the most pressing issue...

Is there a reason why the `@context` and other URls are all http? 

In https://w3c.github.io/poe/model/
> EXAMPLE 1

```
{
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Set",
    "uid": "http://example.com/policy:1010",
    "permission": [{
        "target": "http://example.com/asset:9898.movie",
        "action": "use"
    }]
}
````

I would have thought that the context should be http**s**.  I understand that it redirects to the secure version - so why not use that by default?

**Comment by rightschain** [comment]
Hi @edent - thanks for your feedback.

The WG discussed the issue you raised at today's teleconference and given that the JSON context URI is defined in the **normative** ODRL Vocab spec using "http" it would mean a substantive change to the document (and the CR/PR process repeated).

We also felt that the "example.com" http's are only indicative and changing them all to https would not change the intent of the (non-normative) examples.

Thanks - R

**Comment by rightschain** [comment]
(Whoops, the above was sent by @riannella who was logged into his other account !)

**Comment by edent** [comment]
:-) Like I said, it's not a high priority issue. It just feels a little weird seeing http everywhere.

Incidentally, https://example.com/ does support https!
