### ISSUE TITLE
About the ODRL ontology

### ISSUE THREAD

**Issue by vroddon** [w3c/poe#291]
**First comment**
Current text reads:
> The current (editors draft) ODRL Ontology and can be downloaded in:

I believe "(editors draft)" should be removed.

**Second comment**
In the document https://www.w3.org/TR/vocab-odrl/ there is no prominent link to the ODRL ontology. It only appears in Section 5.1, and the ontology's role is nowhere mentioned. I would be glad to see a sentence like 'The ODRL Vocabulary & Expression is formalized as a ODRL Ontology (LINK HERE)'.

**Comment by riannella** [comment]
Removed all the "editors drafts" 
Updated all links to final URLs

Added "..ODRL Ontology..." to Conformance section.
