### ISSUE TITLE
Question about using 'broader term' the vocabulary documentation

### ISSUE THREAD

**Issue by aisaac** [w3c/poe#297]
Many resources at https://www.w3.org/TR/odrl-vocab/ are defined as instance of skos:Concept and this is a good thing in my view. I am however wondering whether there was a strong rationale for representing the links to broader concepts as 'broader terms' not 'broader concepts'. The use of the word 'term' can be confusing in the SKOS context, where it can be also used to refer to the labels of the concepts, not the concepts themselves.
Anyway I am ready to accept that this is nitpicking, and will accept if you close this issue without changing the spec. I am just raising it in case it would be a sort of 'typo' that you could treat as such...

**Comment by riannella** [comment]
Yes, you are correct in that we define each Vocab thing as a skos:Concept (in the ttl) but then use "term" in the Vocab document. The only place that differs is for Rule - we call it a concept (because its an 'abstract class'). 

But we do use "term" through-out the Vocab document (we even define a "ConflictTerm").

Hence, why we then used "broader/narrower  term" in each of the definitions (where applicable).

**Comment by aisaac** [comment]
Ouch this 'ConflictTerm' hurts indeed. I was hoping you could replace term by concept at least in the 'broader terms' headings, but if you're using everywhere including in an individual name this is not going to be easy.

By the way is 'term' in 'ConflictTerm' really intended to mean 'concept' in the SKOS sense? Or does it mean something vaguer, like "a word that we use in conflict situation"? In fact the whole naming of the class sounds weird, as the URI ('ConflictTerm') has little to do with the label ('Conflict Strategy Preference')

**Comment by simonstey** [comment]
> By the way is 'term' in 'ConflictTerm' really intended to mean 'concept' in the SKOS sense? Or does it mean something vaguer, like "a word that we use in conflict situation"? In fact the whole naming of the class sounds weird, as the URI ('ConflictTerm') has little to do with the label ('Conflict Strategy Preference')

iirc, it was just meant to be the "name" of the class whose members define the specific conflict resolution strategy a policy has to be evaluated under.

from: https://www.w3.org/TR/odrl-model/#conflict

> **2.10 Policy Conflict Strategy**
> The conflict property is used to establish strategies to resolve conflicts that arise from the merging of Policies or conflicts between Permissions and Prohibitions in the same Policy. Conflicts may arise when merging Policies as a result of Policy Inheritance and the resultant Rules are inconsistent.
> 
> **The conflict property SHOULD take one of the following Conflict Strategy Preference values (instance of the ConflictTerm class**):
> - perm: the Permissions MUST override the Prohibitions
> - prohibit: the Prohibitions MUST override the Permissions
> - invalid: the entire Policy MUST be void if any conflict is detected
>
> If the conflict property is not explicitly set, the default of invalid will be used. 
> Additional conflict property values MAY be defined by ODRL Profiles.
> 
> The Conflict Strategy requirements include:
> 
> - If a Policy has the conflict property of perm then any conflicting Permission Rule MUST override the Prohibition Rule.
> - If a Policy has the conflict property of prohibit then any conflicting Prohibition Rule MUST override the Permission Rule.
> - If a Policy has the conflict property of invalid then any conflicting Rules MUST void the entire Policy.
> - If a Policy has multiple conflict property values (for example, after a Policy merge or inheritance) and there are conflicting Rules then the entire Policy MUST be void.

e.g.:

```jsonld

{
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Policy",
    "uid": "http://example.com/policy:0002",
    "profile": "http://example.com/odrl:profile:40",
    "conflict": "perm",
    "permission": [{
        "target": "http://example.com/asset:1212",
        "action": "display",
        "assigner": "http://example.com/owner:182"
    }],
    "prohibition": [{
        "target": "http://example.com/asset:1212",
        "action": "print"
    }]
}

```

with

```ttl

<http://www.w3.org/ns/odrl/2/#conflictConcepts>
    a skos:Collection ;
    skos:prefLabel "Policy Conflict Strategy"@en ;
    skos:scopeNote "ODRL Core Vocabulary Terms"@en ;
    skos:member :ConflictTerm ;
    skos:member :conflict ;
    skos:member :perm ;
    skos:member :prohibit ;
    skos:member :invalid .

:ConflictTerm
	a rdfs:Class, owl:Class, skos:Concept ;
	rdfs:isDefinedBy odrl: ;
        skos:definition "Used to establish strategies to resolve conflicts that arise from 
                                  the merging of Policies or conflicts between Permissions and Prohibitions in the same Policy."@en ;
        skos:note "Instances of ConflictTerm describe strategies for resolving conflicts."@en ;
	rdfs:label "Conflict Strategy Preference"@en .

:conflict
	a rdf:Property , owl:ObjectProperty, skos:Concept ;
	rdfs:isDefinedBy odrl: ;
	rdfs:label "Handle Policy Conflicts"@en ;
	skos:definition "The conflict-resolution strategy for a Policy."@en ;
	skos:note "If no strategy is specified, the default is invalid."@en ;
	rdfs:domain :Policy ;
	rdfs:range :ConflictTerm .

:perm
	a :ConflictTerm, owl:NamedIndividual, skos:Concept ;
	rdfs:isDefinedBy odrl: ;
	rdfs:label "Prefer Permissions"@en ;
        skos:definition "Permissions take preference over prohibitions."@en ;
        skos:note "Used to determine policy conflict outcomes."@en .
:prohibit
	a :ConflictTerm, owl:NamedIndividual, skos:Concept;
	rdfs:isDefinedBy odrl: ;
	rdfs:label "Prefer Prohibitions"@en ;
        skos:definition "Prohibitions take preference over permissions."@en ;
	skos:note "Used to determine policy conflict outcomes."@en .
:invalid
	a :ConflictTerm, owl:NamedIndividual, skos:Concept ;
	rdfs:isDefinedBy odrl: ;
	rdfs:label "Void Policy"@en ;
	skos:definition "The policy is void."@en ;
	skos:note "Used to indicate the policy is void for Conflict Strategy."@en ;
        skos:scopeNote "Non-Normative"@en .
```

**Comment by aisaac** [comment]
Thanks @simonstey it's really a pity that the word 'term' was used for this, as it's more than a term (it's a concept, really!)

**Comment by riannella** [comment]
Closing as no errata action needed
