### ISSUE TITLE
ODRL ontology: not a working draft anymore

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#302]
All the ontology documents (ODRL Vocabulary - https://www.w3.org/TR/odrl-vocab/#rdf) include this statement regarding the odrl Thing:

> This is the RDF ontology for ODRL Version 2.2 (working draft)

"(working draft)" can be removed now.

**Comment by iherman** [comment]
This is a change on the non TR documents, ie, can be done at any time. I have updated the repo accordingly (see https://github.com/w3c/poe/commit/f14648fb9b69483af1696a24c131eea31d0eafe9), and refreshed the ontology files on /TR.

Closing issue.
