### ISSUE TITLE
Typo in "cc:Commercialuse"

### ISSUE THREAD

**Issue by riannella** [w3c/poe#304]
"cc:CommericalUse" should be corrected with "cc:CommercialUse" in https://www.w3.org/ns/odrl/2/ODRL22.ttl

**Comment by vroddon** [comment]
I see the issue as closed but the file is still wrong (see https://www.w3.org/ns/odrl/2/ODRL22.ttl) 
I pushed the correction in the origin/gh-pages branch of https://github.com/w3c/poe with no results. 
What else has to be done to go public?

**Comment by riannella** [comment]
Thanks @vroddon 

I think we need the magic of @iherman now to copy the 3 files (.ttl, .rdf, .nt) to the right spot at https://www.w3.org/ns/odrl/2/

**Comment by iherman** [comment]
Magic or not, @iherman is getting old and his memory is failing... :-(

Can you give me the exact references of the files on github that must be copied to`/ns/odrl/2/` ? Are we talking about all the `ODRL22.*` files in `vocab/`?

**Comment by riannella** [comment]
These are the 3 files:
  https://raw.githubusercontent.com/w3c/poe/gh-pages/vocab/ODRL22.ttl
  https://raw.githubusercontent.com/w3c/poe/gh-pages/vocab/ODRL22.rdf
  https://raw.githubusercontent.com/w3c/poe/gh-pages/vocab/ODRL22.nt

Thanks @iherman

**Comment by iherman** [comment]
done.

**Comment by riannella** [comment]
Summary:

Incorrect spelling of "cc:CommericalUse" (in the ontology files) - should be "cc:CommercialUse"

**Comment by bact** [comment]
> "cc:CommericalUse" should be corrected with "cc:CommercialUse" in https://www.w3.org/ns/odrl/2/ODRL22.ttl

I downloaded the file from that URL and can confirmed that "cc:CommericalUse" is no longer be found in the file.

**Comment by iherman** [comment]
Thank you @bact. It is time to close this issue...

**Comment by bact** [comment]
Sorry @iherman it still remains in one of the three files:

- https://www.w3.org/ns/odrl/2/ODRL22.ttl - fixed

- https://www.w3.org/ns/odrl/2/ODRL22.nt - fixed

- <s>https://www.w3.org/ns/odrl/2/ODRL22.rdf - found at Line 22</s>

```
<Action rdf:about="http://creativecommons.org/ns#CommericalUse">
```

**Comment by iherman** [comment]
Oops. Done.

Thanks

**Comment by bact** [comment]
Confirmed the fix in RDF.
