### ISSUE TITLE
ODRL Profiles

### ISSUE THREAD

**Issue by riannella** [w3c/poe#49]
Move section to new Top-level Section (to show its importance).
Update the narrative

**Comment by riannella** [comment]
Narrative updated.
Requirements clearer
new Section
http://w3c.github.io/poe/model/#profile

**Comment by simonstey** [comment]
imo, Sections 4.1 & 4.3 should neither be part of the specification nor considered being normative

**Comment by riannella** [comment]
@simonstey I will make the entire section non-normative?

**Comment by simonstey** [comment]
which would (afaik) make ODRL profiles non-normative altogether.

**Comment by riannella** [comment]
Correct. ODRL Profiles are not mandatory to use ODRL.
