### ISSUE TITLE
rightOperand is a reference to a value

### ISSUE THREAD

**Issue by riannella** [w3c/poe#56]
Add support to indicate that the rightOperand is a reference (URI) to a value, not the value itself.

See: https://www.w3.org/2016/poe/wiki/Requirements#POE.R.E.01_Referring_to_external_resources_for_defining_payment_fees

**Comment by riannella** [comment]
One solution to this is to add a new (boolean) attribute to the Constraint class (in the UML model) as all we need to know is how to interpret the rightOperand. It will either be the value we are interested in comparing, or it will be a URI to some external service that will return the value of interest (dynamically).

Lets call this new optional attribute "dataReference"
If it is true, then the rightOperand must be a URI and must be dereferenced to get the value.
If it is false (the default) then the righOperand is as expected, the data value.

**Comment by riannella** [comment]
Another option is to have a new property called "rightOperandRef" that has the URI to de-reference (to get the value). And the rule is either rightOperand xor rightOperandRef must be present in the constraint.

**Comment by nitmws** [comment]
There are more details to consider: processing the right operand requires to include the rightOperand, the dataType and the unit properties. If we open up right operands to retrieving the value from a web resource I see these issues:
Issue 1: does it makes sense to include dataType and unit into the processing of a linked resource? 
Issue 2: what exactly will be delivered by the linked resource of the right operand? Overall format (JSON, XML, plain text), data type and unit?

One option to solve that is to define a mandatory format (... will not be liked by many) or to indicate "this has to be clarified with the organisation behind this link". 
This indicator could be simple:  dataType="http://www.w3.org/2001/XMLSchema:anyURI"
... and no special rightOperandRef is required.

**Comment by riannella** [comment]
Issue 1: perhaps it might....you could still express that what the "dynamic URL" will return is a decimal which is $USD.
Issue 2: we need to leave that to a Profile!

We could use the datatype to indicate the rightOperand is a "dynamic URL", but if we used xsd:anyURI that actually could be a real datatype someone might want to express (ie: the rightOperand is a URI value and this is literally what you are trying to match.

But we could define our own special value for odrl:datatype? 
(we've done that before: http://w3c.github.io/poe/vocab/#actionValues)
Such as odrl:derefURI

**Comment by nitmws** [comment]
Yes, having a special data type (ODRL) value for such a URL would help. I suggest odrl:resourceURL because one uses this URL to access the resouce identified by it.

**Comment by riannella** [comment]
In order to support API calls, we add a new property rightOperandReference, and a new class

**Comment by riannella** [comment]
Info Model updated (see Constraint section).
Need to add to the Vocab

**Comment by riannella** [comment]
Added rightOperandReference  to vocab
