### ISSUE TITLE
Add unit-of-count

### ISSUE THREAD

**Issue by riannella** [w3c/poe#58]
Add a unit-of-count to the Constraint

See: https://www.w3.org/2016/poe/wiki/Requirements#POE.R.V.03_Add_concept_of_.27unit-of-count.27_to_Duty_Constraint_Vocabulary

**Comment by riannella** [comment]
The solution to this has a dependency on https://github.com/w3c/poe/issues/62

**Comment by riannella** [comment]
Then we add "unitOfCount" as a new constraint to the Vocab

**Comment by nitmws** [comment]
Had a look into the Requirement and the related User Case: this sound more like a "pay-per-what" or more generic "what-triggers-a-payment" issue.

**Comment by riannella** [comment]
Apart from a payAmount Duty, what else would "unitOfCount" be used for?

**Comment by nitmws** [comment]
Pondering that use case I feel this unitOfCount is not a part of a constraint but a constraint itself. Why: in first examples this unitOfCount was part of the Payment Amount constraint defining an amount of money. But in fact unitOfCount relates to the Duty action "compensate": a compensation is triggered if a person or device or ... exercises the action of the Persmission. 
I think of creating a constraint with a left operand "dutyTrigger - Defines a context for the Action of a Permission. If this context applies the Action of the Duty has to be exercised." And the right operand has to be an entity like "Permission action exercised by a person" or "Permission action exercised by a device".

**Comment by riannella** [comment]
Add as new Constraint Name

**Comment by riannella** [comment]
Added to the vocab
