### ISSUE TITLE
Add Constraint to Party and Asset

### ISSUE THREAD

**Issue by riannella** [w3c/poe#59]
Add Constraint model to Party and Asset.

See: https://www.w3.org/2016/poe/wiki/Requirements#POE.R.DM.01_Define_how_constraints_on_a_party_can_be_expressed_.28Migrated.29

Also addresses:
https://www.w3.org/2016/poe/wiki/Requirements#POE.R.DM.07_Define_a_category_property_for_class_Party

https://www.w3.org/2016/poe/wiki/Requirements#POE.R.DM.08_Add_a_category_property_to_Asset

**Comment by nitmws** [comment]
Comment: these Requirements propose to add properties to the classes Party and Asset for filtering out potential parties and asset - but not (explicitly) to use the ODRL Constraint.

**Comment by riannella** [comment]
Yes, as requirements they state this - and as long as the solution supports this, then the requirement is met. Hence, in this case, the proposal is to "reuse" the Constraint model to meet this requirement.

**Comment by nitmws** [comment]
@riannella my view on your proposal is: that makes processing more complicated than a filtering category of a class.

1. Start processing a Party
2. Check all the constraints if one or more apply/ies to this party (this raises the issue we discussed already: how to link constraint and party, a link from the constraint to "assignee" is not sufficient as there could be multiple of them.)
3. A hand-written constraint processor is required to interpret the left operand correctly.
4. The results of all constraints have to be ANDed for making the final result.

With a property of a Party: the processor doesn't have to parse all constraints, the "filter" is attached to a specific instance of Party. The challenge of "how to get a result" is similar: how to check if this filtering item applies to the party - but the constraint-searching and -matching overhead does not exist.

**Comment by riannella** [comment]
Sure,  understand, but reusing the Constraint model means that implementors already have the code to do that?

**Comment by nitmws** [comment]
My conclusion from recent discussion about creating code for constraints is that this needs to be done differently (= individually) for each constraint name/left operand. Therefore an "already have the code" will not be a widespread case. Maybe only a programming model or design could be reused.

**Comment by riannella** [comment]
Use scope for Party and Asset

**Comment by riannella** [comment]
Info Model updated - see "scope" section in Party and Asset.
Need to update Vocab

**Comment by riannella** [comment]
We have a slight issue now...
Scope was modelled for Parties as explicit subclasses of Parties.
For example, "All2ndConnections" is a type of Party - (which I think is not correct ;-)
And, or course, this is not reusable for Asset.

Hence, I propose we add an class called Scope and relation (has scope) to the ontology.
These can then be used for Asset.

I propose we re-classify the Party-based Scopes to be all subclasses of Scope
(and Party then needs to use the "has scope" property)

From the implementors survey, it seems no-one has used these Scope classes, so there should be minimal impact.

It will mean that these examples will have to be updated:
  http://w3c.github.io/poe/vocab/#sc-example10

Thoughts????

**Comment by simonstey** [comment]
> From the implementors survey, it seems no-one has used these Scope classes, so there should be minimal impact.

Which (imo) is primarily due to ODRL's definition/interpretation of scopes rather than limited interest/missing use cases for them.

To start things of, I would begin with removing the collection aspect of "scopes". E.g., I think it would be way more useful to be able to write something like this:

```Turtle
<http://example.com/policy:5109>
  a odrl:Agreement ;
  odrl:permission [
    a odrl:Permission ;
    odrl:action odrl:display ;
    odrl:target <http://example.com/myPlace:billie:photos:football2010> ;
    odrl:assigner <http://example.com/myPlace:billie> ;
    odrl:assignee ex:football_network 
  ] .

ex:football_network 
   a odrl:Group ;
   odrl:member (ex:Alice ex:Bob) .

<http://example.com/myPlace:billie> a odrl:Individual.
ex:Alice a odrl:Individual.
ex:Bob a odrl:Individual.

```

**Comment by riannella** [comment]
I don't think ODRL should get into defining members of groups (of parties).
We *try* to stick to identifying the party - and thats it.
With scopes, we have to support a way to "scope" that entity with a URI.

**Comment by stuartmyles** [comment]
In my view, any kind of modifier to the identification of a party is a
mistake.

I'm against the "scoping" of parties as being either individuals or groups.
And, similarly, I think that the idea of identifying a party and then
filtering that party based on some kind of criteria (such as a constraint)
is very problematic. Specifically, I think it will be very difficult to
implement these kinds of filtering schemes in a way that will always
deliver the same results. In other words, I think you will wind up with
different results from different engines.

I realize, however, that this has been established as a requirement. But
can anyone explain what is the reason behind the requirement? Why isn't it
sufficient to just identify a party?

Regards,

Stuart

**Comment by riannella** [comment]
@stuartmyles The link to the requirement is in the first discussion item above.
As a WG member, you have the right to propose that this requirement not be supported (or to provide any other evidence for adoption). You can also propose that exisiting scopes be deprecated.

**Comment by simonstey** [comment]
@riannella 
> I don't think ODRL should get into defining members of groups (of parties).
We try to stick to identifying the party - and thats it.
With scopes, we have to support a way to "scope" that entity with a URI.

how's 
`odrl:assignee <http://example.com/employeeUnder18> ` 
different from
```
odrl:assignee <http://example.com/employee> 
odrl:scope <http://example.com/under18>
```

**Comment by riannella** [comment]
The first example shows a URI for the assignee.
The second example does the same, but then goes further and says, "that assignee is further scoped by this URI".
You can imagine in another Permission, there is the same employee URI but with a "over18" scope.

This is my interpretation of the original requirement.
I would support the removal of scopes.

**Comment by nitmws** [comment]
I recall from the discussion on 5 December that scopes like "policy applies only to the group as a whole" and "policy applies to each member of a group" should be kept as they are. For other "scopes" it was not clear how to proceed: adding more terms to scope or to define something different.

**Comment by riannella** [comment]
Scope for Parties already exists in the current model, and in fact, you can already add any scope (URI) you like to an ODRL policy for a Party. Some are defined in the vocab, but in theory, any URI can be used.

**Comment by riannella** [comment]
The vocab needs to be add support for the Asset scope and update the scope support for Party

**Comment by riannella** [comment]
Completed
