### ISSUE TITLE
Constraints on Constraints

### ISSUE THREAD

**Issue by riannella** [w3c/poe#62]
Define an updated constraints on constraints model

See: https://www.w3.org/2016/poe/wiki/Requirements#POE.R.DM.06_Support_relative_time_constraints

**Comment by nitmws** [comment]
What is a Constraing on a Constraint?
I think for a deeper discussion on 5 December  we need a description of what exactly that should be. 

The referenced Requirement DM.06 raises this need: "Extend the temporal constraints by setting a time reference, any period in the rightOperand refers to this point in time." The referred UCs for that requirement are UC16 (combining two constraints: c1 = monthly access, c2=over 7 years) and UC19 (exercising the action of a permission only after the end of an event)

For both UCs I see no urgent need for a Constraint on Constraints:

- UC 16 could be solved by applying two constraints to the permission (... is it really needed to combine both into a single one?) - see https://www.w3.org/2016/poe/wiki/Use_Cases#POE.UC.16_Accessing_Historical_Data
- UC 19 could be solved by a constraint covering that use case, e.g. eventEndPeriod in https://www.w3.org/2016/poe/wiki/Constraints

I'd like to remind of the general approach liked at the Constraints conference call on 15 November: it is better to express a complex scenario in a single, special constraint definition than expressing it by a rich set of constraint graphs which primarily add complexity and do not simplify the processing. (Simon raised concerns about endless loops of nested constraints.)

**Comment by iherman** [comment]
Discussed on virtual F2F, Dec-5-16:

"we work on improved Constraint Definitions and include non-simple values for some constraints where it makes sense"

See: http://www.w3.org/2016/12/05-poe-irc#T13-26-11-1

**Comment by riannella** [comment]
For Issue#60 we work on improved Constraint Definitions and include non-simple values for some constraints where it makes sense

**Comment by riannella** [comment]
This now actually becomes an ODRL Vocab milestone issue

**Comment by riannella** [comment]
@nitmws moved to Vocab milestone. Need to add the non-simple examples to the comments in the definitions??

**Comment by riannella** [comment]
WG agreed to proposal at: https://lists.w3.org/Archives/Public/public-poe-wg/2017Jan/0012.html
at 23JAN teleconf

**Comment by riannella** [comment]
Added "constraint on constraint" support to section "Constraint Relations" in the Information Model: http://w3c.github.io/poe/model/#constraint-relations

Also used "isNecessaryFor" instead of "dependsOn" operator
