### ISSUE TITLE
Names of constraints in Vocab Editor's Draft - 4 Nov 2016

### ISSUE THREAD

**Issue by iptc** [w3c/poe#66]
In the ODRL Vocabulary Editor's Draft document of 4 November - http://w3c.github.io/poe/vocab - the names of constraints (e.g. Absolute Position, Language or Spatial) have turned into Right Operands which i/ does not align with the ODRL 2.1 vocabulary and data model and ii/ also not with the data model in http://w3c.github.io/poe/model/ . Note: the page internal link to this section of the vocabulary is apparently #constraintActions which is also not the right term for the names of constraints.

**Comment by riannella** [comment]
Fixed in current Editors draft
