### ISSUE TITLE
Improve Constraint-related definitions in the Information Model

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#71]
There were complaints that in the ODRL Information Model, Editor's draft of 16 November (http://w3c.github.io/poe/model/),  the class Constraint and the use of this class by Permission, Prohibition and Duty are not well defined.

**Comment by nitmws** [comment]
See proposed changes in https://www.w3.org/2016/poe/wiki/Constraints_in_the_Information_Mode

**Comment by riannella** [comment]
This issue is already captured in this existing issue: https://github.com/w3c/poe/issues/68

**Comment by riannella** [comment]
@nitmws Closing this as it is the same as issue #68
