### ISSUE TITLE
Support Multiple Actions

### ISSUE THREAD

**Issue by riannella** [w3c/poe#73]
Should we relax the single Action per Perm/Prohib constraint?

Need to then be clear what a Constraint applies to (all the actions?, or one specific?)

What about Duties?

**Comment by simonstey** [comment]
what about inheritance? if a rule was defined for more than 1 action, how would a processor determine whether this rule should be overriden by child rules? 

besides that, I dont think we gain any additional expressivity from such a feature

**Comment by riannella** [comment]
Will leave as single Action per Rule (for now) until more info from the WG is received/discussed.

**Comment by riannella** [comment]
WG agreed to this change (9 JAN 2017).
Also look at multiple Assets

**Comment by riannella** [comment]
Added new section on 3.1.1 Policy Structures
