### ISSUE TITLE
revising vocabulary definitions 

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#74]
The majority of the definitions provided in the current ED of the vocabulary are either inconsistent, unclear or both.

For example: 

| Definition | Comment |
| ------------ | ------------- | 
| <blockquote> 4.1.1 Policy </br>Definition: An entity to capture the statements of the policy</blockquote>| statements == rules? | 
| <blockquote> 4.1.3 Profile</br> Definition: The identifier of an ODRL Profile that this Policy conforms to. </blockquote>|<ul><li>which policy?</li><li>why is Profile prepended with _ODRL_ but Policy isn't?</li><li>**p**olicy (4.1.1) vs. **P**olicy (4.1.3)</li></ul> |
| <blockquote> 4.4.1 Conflict Preference </br> Definition: Is used to resolve conflicts arising from the merging of policies, specifically when there are conflicting Actions in the Permissions and Prohibitions</blockquote>|<ul><li>who has a preference for conflicts at all?</li><li>it doesn't resolve any conflicts at all, but defines the conflict resolution strategy to be used</li><li>>1 conflicting actions in permissions?</li></ul> |
| <blockquote> Comment: Instances of ConflictTerm describe policies for resolving conflicts.</blockquote>| policies as in ODRL policies? -> semantics? | 
| <blockquote> Instances: invalid, perm, prohibit</blockquote>| prohibit is missing | 

etc.

**Comment by riannella** [comment]
Added prohibit (missing from skos collection)

**Comment by riannella** [comment]
Above changes made.

**Comment by simonstey** [comment]
> Above changes made.

I should have put more emphasis on the **etc.** part...

The current Vocab draft is in large parts still inconsistent and unclear (+ garnished with typos every now and then). It needs to be **thoroughly reviewed** (by at least >=2 members of the WG) and updated/fixed accordingly.

For example (**this is only a small subset**):

> **4.1.1 Policy**
Definition: 	A Rule expressing what Action is allowed and/or disallowed over an Asset.

- what are Rules then? (assuming "Rule" refers to [ODRL Rules](http://w3c.github.io/poe/model/#rule))
- how do we call policies with >1 rule? (this was also pointed out in #119)
- how can **one** Rule express that an Action is **both** allowed **and** disallowed over an Asset? 
- s/over an Asset/to be performed on an Asset/
-  (This also affects #119, sorry @riannella for not getting back to you on this.)
---------------------
> **4.1.1 Policy**
Definition: 	A Rule expressing what Action is allowed and/or disallowed over an Asset.

> **4.1.2 Rule**
Definition: 	A Permission, Prohibition or Duty that expresses an Action that may, must not, or must be performed (respectively).

> **4.9.1 Permission**
Definition: 	An Action that may be performed over an Asset.
> **4.10.1 Prohibition**
Definition: 	An Action that must not be performed over an Asset.
> **4.13.1 Duty**
Definition: 	An Action that has been agreed to be performed as a requirement for the applicable Permission to become valid.

So if: 
**Policy** = A **Rule** expressing what Action is allowed and/or disallowed over an Asset.
**Rule** = A **Permission, Prohibition or Duty** that expresses an Action that may, must not, or must be performed
**Permission, Prohibition or Duty** = An **Action** that may, must not, or has been agreed to be performed (over an Asset) as a requirement for the applicable Permission to become valid.
=>
**Policy** = An **Action** that may, must not, or has been agreed to be performed (over an Asset) as a requirement for the applicable Permission to become valid.

?

---------------------

> 4.16.1 Absolute Asset Position
Definition: 	A point in space or time defined with absolute coordinates the positioning of the Asset has to comply with for excersing the Action.

> 4.16.2 Absolute Spatial Asset Position
Definition: 	The absolute spatial positions of four corners of a rectangle on a 2D-canvas or the eight corners of a cubiod in a 3D-space the Asset has to fit in after the Action.

> 4.16.4 Absolute Asset Size
Definition: 	Measure(s) of one or two axes for 2D-objects or measure(s) of one to tree axes for 3D-objects of the Asset after the Action.

> and others ...

what? (also typos)

**Comment by vroddon** [comment]
Do you believe is it worth to have a specific call today or tomorrow to jointly propose better definitions?

**Comment by riannella** [comment]
@vroddon we have 14 hours to teleconf soon ;-)

@simonstey yes "etc" is too broad :-) ...please submit issues on all bits that need clarification. If its just a typo, then feel free to edit the files yourself.

@nitmws I think @simonstey is asking for clarification on the "Absolute..." terms

**Comment by riannella** [comment]
We need to ensure that all the changes to these core terms are reflected here:
  https://w3c.github.io/poe/model/#terminology
In the narrative of the IM spec and in the definitions in the Vocab spec.

So, lets see if we can agree on them here....once...then duplicate....

**Comment by riannella** [comment]
@simonstey what is your suggestion for defining these key terms:

https://w3c.github.io/poe/model/#terminology

**Comment by riannella** [comment]
What about:

Policy - One or more Rules that allow or disallow a Rule
Rule - Expresses an Action that can be related to an Asset, Party or Constraint.

**Comment by larsgsvensson** [comment]
> Policy - One or more Rules that allow or disallow a Rule

Shouldn't that be "Policy - One or more Rules that allow or disallow an Action"?
(One Rule to allow them all...)

**Comment by riannella** [comment]
Sure: 
"Policy - One or more Rules that permit or prohibit an Action"

**Comment by simonstey** [comment]
> "Policy - One or more Rules that permit or prohibit an Action"

**Proposed:** Policy - A non-empty set of Permissions and/or Prohibitions.

> Rule - Expresses an Action that can be related to an Asset, Party or Constraint.

that's not the essence of a rule.. It's more something along the lines of:

**Proposed:** Rule - An abstract concept that represents the common characteristics of Permissions, Prohibitions, and Duties. 

--------------

> Action - An operation that is applicable to a Rule

what? 
**Proposed:** Action - An operation on an Asset.

> Permission - An Action that may be performed over an Asset.

A permission is not an action.
**Proposed:** Permission - The right to perform an Action over an Asset. 

> Prohibition - An Action that must not be performed over an Asset.

A prohibition is not an action.
**Proposed:** Prohibition - The obligation to not perform an Action over an Asset. 

> Duty - An Action that has been agreed to be performed as a requirement for the applicable Permission to become valid.

A duty is not an action.
**Proposed:** Duty - The obligation to perform an Action.

> Asset - An identifiable resource that is the subject of a Rule

**Proposed:** Asset - A resource or a collection of resources that are the subject of a Rule.

> Party - An identifiable entity who may undertake a Role in a Policy

**Proposed:** Party - An agent or a collection of agents that undertake Roles in a Rule.

> Constraint - The context, such as limitations, restrictions, or interpretations, that must be applied to an Action, Party, or Asset

**Proposed:** Constraint - A Boolean expression that refines the applicability of a Rule.

> ODRL Processor - A system that provides services that creates, manipulates, and validates ODRL Policy expressions.

**Proposed:** ODRL Processor - A system that supports creating, manipulating, and validating ODRL Policies.
(missing the differentiation between ODRL Validator <-> ODRL Evaluator)

**Comment by riannella** [comment]
Since we use "set" as a Policy subclass, how about:
Policy - A non-empty group of Permissions and/or Prohibitions

We don't want to express "rights" per say, so how about:
Permission - The ability to perform an Action over an Asset

An Agent is someone/thing that performs on your behalf, so how about:
Party - An entity or a collection of entities that undertake Roles in a Rule

**Comment by vroddon** [comment]
Updated the changes in the definitions by commit b4fcf222447327cc5979adf8df72782999456e34

**Comment by riannella** [comment]
Updated the definitions across both documents now.

Just noticed we use "obligation" here:
 Prohibition - The obligation to not perform an Action over an Asset
Which could be confusing with Duties:
  Duty - The obligation to perform an Action

Proposed change to:
 Prohibition - The inability to perform an Action over an Asset
which mirrors:
 Permission - The ability to perform an Action over an Asset

Also, now that we have constraints in Party and Asset:
  Constraint - A Boolean expression that refines the applicability of a Rule, or the context of a Party or Asset collection.

commit:  0aa5563e0cd571dbebb6bc1ccf3c75278207568c

**Comment by simonstey** [comment]
there's still a lot to fix, cf. #184 

also:
> Permission - The ability to perform an Action over an Asset

just because I'm able to do something doesn't mean that I'm also entitled to do so (and vice versa)..
For example: 
- I'm (potentially) able to rob a bank, so according to that definition I also have the permission to do so.
- If I have the permission to download an asset but I'm currently not able to do so because my pc broke, I have suddenly both a permission+prohibition => conflict

**Comment by riannella** [comment]
I think the fact that your PC is broke has nothing to do with an ODRL Expression.

If there is a power failure, does ODRL have to deal with that ? ;-)

**Comment by simonstey** [comment]
> I think the fact that your PC is broke has nothing to do with an ODRL Expression.

and being **able** to do something has nothing to do with being **permitted** to do something

> We don't want to express "rights" per say, so how about:

btw. we define Duty as:
> A Duty is the **obligation** to perform an Action. 

where **obligation** according to http://www.dictionary.com/browse/obligation is defined as:
>  1. something by which a person is bound or obliged to do certain things, and which arises out of a sense of duty or results from custom, [law](url), etc.
> 2. something that is done or is to be done for such reasons:
to fulfill one's obligations.
>3. a binding promise, contract, sense of duty, etc.
>4. the act of binding or obliging oneself by a promise, contract, etc.
>5. **Law.
    an agreement enforceable by law, originally applied to promises under seal.
    a document containing such an agreement.
    a bond containing a penalty, with a condition annexed for payment of money, performance of covenants, etc.**
>6. any bond, note, bill, certificate, or the like, as of a government or a corporation, serving as evidence of indebtedness.

**Comment by riannella** [comment]
@simonstey What changes are you proposing?

(BTW, we don't focus on "rights"..so we can chose the 2nd dictionary definition ;-)
