### ISSUE TITLE
3.1.2 Undefined Policy

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#75]
> 3.1.2 Undefined Policy

- it's about undefined actions not policies right?

> The undefined attribute is used to indicate how to support Actions that are not part of any profile in the policy expression system. 

- what's a _policy expression system_ ?
- how do we know whether an action _is part of a profile_ ?
- is there a default profile to which all currently defined actions belong to?

> In the support case, even though the Action is unknown, the policy still is valid and the consuming parties or system of the policy MUST be made aware of the unknown Action.

- by whom? 
- do they also have to _support_ those actions? or do they only have to be made aware of them?

> This MAY be via a user interface that displays the unknown Action for human readability.

- what does that mean for systems automatically consuming/processing ODRL? 

> In the ignore case, even though the Action is unknown, the policy still is valid and the consuming parties or system of the policy MAY be made aware of the unknown Action.

- and it's up to them to decide whether they want to support or ignore those actions? 

> In the invalid case with the unknown Action, the policy is invalid and the consuming parties or system of the policy MUST be made aware of this.

- wording
- and it's up to them to decide whether they want to process that invalid policy anyway?

> and since the undefined attribute is invalid

- is it really invalid or is its value set to invalid

**Comment by riannella** [comment]
I have updated and *simplified* this section. In essence, we cant say how and ODLR system "supports" or "ignores" an action. So that is left up to the implementor.
