### ISSUE TITLE
3.1.1 Policy Conflict

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#76]
> The conflict attribute is used either to resolve conflicts arising from the merging of policies, 

- only from merging? what if a policy contains conflicting rules, but wasn't merged with any other policy?

> specifically when there are conflicting Actions in the Permissions and Prohibitions, 

- what constitutes a conflict? 
- how are _conflicting Actions_ identified? 
- is it possible that two permitted actions of the same policy are causing a conflict?

> or to set priorities over the Permissions/Prohibitions in the same policy.

- what?

> perm: the Permissions will always takes preference
prohibit: the Prohibitions will always takes preference

- what preference?

> invalid: the policy is invalid

- i.e., any policy using `invalid` as conflict resolution strategy is invalid per definition?

**Comment by riannella** [comment]
First question: if you keep reading the sentence...it then goes on to say "or to set priorities..."

I've updated the section.

Remember that to do conflict resolution properly, we look towards the Formal Semantics ;-)
All the ODRL expression can do it bluntly state the obvious.

**Comment by simonstey** [comment]
> First question: if you keep reading the sentence...it then goes on to say "or to set priorities..."

what does "setting priorities" mean? Current wording implies that it's possible to assign priority levels to individual rules of a policy, i.e. permission to use > prohibition to read > prohibition to print > permission to display

**Comment by riannella** [comment]
Is the word "preferences" better?

**Comment by simonstey** [comment]
> Is the word "preferences" better?

no.. the conflict attribute is neither _resolving conflicts_ nor does it _set priorities over the Permissions/Prohibitions in the same policy_. It is specifying a policy's conflict resolution strategy that must be adhered to when resolving conflicts of said policy.

In ODRL, there are currently only 3 strategies to choose from namely **invalid**,**perm**, and **prohibit**; and it happens that two of them define some sort of preference/priority hierarchy, but that's not the norm. There exist various other [different conf. res. strategies](https://kar.kent.ac.uk/43215/1/ResolvingPolicyConflictsFinalFormatted.pdf) that are as viable as the ones predefined by ODRL, but don't define any preferences or alike.

TL&DR: _The conflict attribute is used to specify a policy's conflict resolution strategy._

**Comment by riannella** [comment]
Ok, made some edits to the section to make it about "strategies" rather than actual conflict resolution.

if there are other strategies we can add to the model, please suggest.

**Comment by vroddon** [comment]
Merged
(Revision: 2ebab830920efae27881e66509538d82646ae7d2,  at 20/02/2017 12:25:51)

**Comment by simonstey** [comment]
The section about policy conflict strategies now includes following example:

> For example, one Policy stated that Assignee Fred had been granted an "exclusive" distribution Permission, and the other Policy said the same for Assignee Mary. In the same Policy, conflicts can also arise when the same Action is used in a Permission and a Prohibition. 

where _"Assignee Fred had been granted an "exclusive" distribution Permission, and the other Policy said the same for Assignee Mary."_ refers to a conflict arising between **two permissions** (due to their duty to [`odrl:ensureExclusivity`](https://w3c.github.io/poe/vocab/#term-ensureExclusivity)).

How would such a conflict be resolved for policies having `perm/prohibit` as conflict resolution strategies?

> - If a Policy has the conflict attribute of perm then any conflicting Permission Rule MUST overide the Prohibition Rule and continue with the Policy as valid.  
> - If a Policy has the conflict attribute of prohibit then any conflicting Prohibition Rule MUST overide the Permission Rule and continue with the Policy as valid.

(s/overide/override)

**Comment by riannella** [comment]
I think we remove this example (as it is  not relevant to this conflict detection strategy), and we have one later in that section that is.

**Comment by riannella** [comment]
Updated
