### ISSUE TITLE
Concept Table visual  look

### ISSUE THREAD

**Issue by riannella** [w3c/poe#8]
Need to decide on the visual look of the table describing each concept.
Two options are attached.
Feedback and other options welcome
<img width="835" alt="screen shot 2016-06-14 at 12 53 11" src="https://cloud.githubusercontent.com/assets/13191615/16142866/67f8816e-34ac-11e6-8b00-7a8dec0615ca.png">
<img width="833" alt="screen shot 2016-06-14 at 12 53 20" src="https://cloud.githubusercontent.com/assets/13191615/16142869/6a6ac5ec-34ac-11e6-8d8e-d270e12ed3e8.png">

**Comment by nitmws** [comment]
Hm, I assume 2.1.2 and 2.2.1 are the two different options - right?
- I see different sets of data, e.g. Parent Class and In Range of in Policy only. Should we show a consistent set with empty values if an assertion is not supported?
- SKOS is used like the owner of concepts, e.g. "Narrower SKOS Concepts". Should be "Narrower Concepts (by SKOS)" or "Narrower Concepts *)" and a footnote explains that *) = by SKOS.
- "SKOS Concept" must be "Concept Scheme"
- "SubClass: Action": shouldn't this be "Class: Action"?

**Comment by riannella** [comment]
The main difference is having one table with multiple rows, or have two tables and put the "vocab" stuff in the first table, and the more ontological stuff in the second table.
1 - I assumed we would only show what we know, otherwise we may have large tables with empty cells (and maybe non-relevant properties).
2 - We can work on what to actually call the SKOS concepts in the table.
3 - In this case, Use is a subclass of Action.
The main decision is do we want the single or double tables?

**Comment by iherman** [comment]
@riannella 

I think that separating the 'ontological' stuff, as you put it, into a separate table makes a lot of sense. In fact, we may want to have maybe a separate document to 'hide' the ontological part from those who do not even want to see that stuff (I remember we discussed this, I am not sure where we are with this). We have to accept the fact (whether we like it or not) that the precise ontology terminology would act as a push back for many out there.

**Comment by riannella** [comment]
I've made them slightly different colours as well. Perhaps in a future version we can add a hide/show script.

**Comment by riannella** [comment]
Completed
