### ISSUE TITLE
Improve Constraint related definitions in Information Model

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#81]
The definitions regarding constraints in the Information Model - http://w3c.github.io/poe/model/#infoModel - sections about Permission, Prohibition and Duty are currently not very clear and precise.
This should be improved, see proposals in https://www.w3.org/2016/poe/wiki/Constraints_in_the_Information_Model

**Comment by nitmws** [comment]
Note on removing "Needs WG Decision": I feel that the proposed definitions change the current (partially not existing) definitions. Does that kind of change need a WG Decision or is this just an editing action?

**Comment by riannella** [comment]
My impression from the 5 Dec meeting was that we are "clarifying" the definitions of the current constraint terms.

**Comment by nitmws** [comment]
Already at the special call on constraints on 15 November it was said that it may help to check if the definitions of the Constraints and its uses in other classes is clear and anambiguous. The goal was to define in the Information Model a blueprint for what the "Name of a Constraint", the left operand, should cover and what the impact of constraints on a class using it is.
This is reflected by that proposal Wiki page.
And the clarifications of the current constraint terms only makes sense if they follow such a blue-print.

**Comment by riannella** [comment]
Sorry, I was talking about the actual constraint definitions...
The changes in here: https://www.w3.org/2016/poe/wiki/Constraints_in_the_Information_Model
will be applied to the info model.
I don't think we can change the name of "name" without breaking backward compatibility.

**Comment by vroddon** [comment]
What is the status then of this issue? Does it need discussion in a call?

**Comment by riannella** [comment]
I think if there are no objections to the current proposal to change the rightOperand, then we are ok to go ahead.

**Comment by nitmws** [comment]
By my view and intention the proposals in https://www.w3.org/2016/poe/wiki/Constraints_in_the_Information_Model are clarifications and refinements of free-text definitions without a change of the information model. Using the term "name" for the left operand may be a surprise but I agree to @riannella that this is a backward compatibility issue. If it is ok to add these modified definitions to the Information Model without explicit approval by the WG then the only open issue is: who will do that - and where to apply the change exactly (the Current Editor's Draft?)

**Comment by riannella** [comment]
Yes, we (the InfoModel editors) can make this update.
But please see issue #84 on possibly updating "name" to "leftOperand"

**Comment by nitmws** [comment]
Having a look at http://w3c.github.io/poe/model/ I see that @riannella and @sereAbi are the two editors of the Information model - will you apply the proposals in https://www.w3.org/2016/poe/wiki/Constraints_in_the_Information_Model ?

**Comment by riannella** [comment]
Yes

**Comment by riannella** [comment]
Completed
