### ISSUE TITLE
Allow Asset/Party at the Policy level

### ISSUE THREAD

**Issue by riannella** [w3c/poe#82]
In many cases, the Asset (target) and Parties (assigner, assignee) are the same for multiple Permissions and Prohibitions in an ODRL Policy.

It maybe a useful change to support the Asset/Party at the Policy level, which means that these values all apply to the enclosed Perms/Prohibs (and conversely means that the Perms/Prohibs do not define these values).

**Comment by riannella** [comment]
From @victor:

I fully support this.

This creates, again, alternative manners to express the same thing.
But again, I believe that if necessary, a simple script can transform these expressions into a "canonical form".

I guess that we can define a "canonical" representation of one policy.
And then, different syntaxes that can be algorithmically mapped to the canonical representation.
By having a canonical representation we can grant that (to some extent) policies with the same meaning can be compared and matched. This would be work, though, for the formalization task force, I guess.

**Comment by nitmws** [comment]
My 5 cents on that: asset and party properties should be added to the Policy and not deprecated for Permission/Prohibition/Duty. The processing rule should be: the related assets and parties of a P/P/D are the assets and parties of this P/P/D instance or if not existing of the parenting policy instance. This way a processor would have to search "bottom up" but only for properties of the same name and structure.

But: that triggers more thoughts: what about constraints and duties shared across multiple P/P/Ds? I have to say frankly the @id and @idref design of the XML syntax  was never my good friend - and also not used in any of the XML examples. Was something like that ever defined for JSON? 
And this reference-by-structure design could be a consistent approach across different syntaxes.

**Comment by simonstey** [comment]
> My 5 cents on that: asset and party properties should be added to the Policy and not deprecated for Permission/Prohibition/Duty. 

then there's no need to make such a change in the first place

**Comment by riannella** [comment]
The proposal was *not* to deprecate the Asset/Party for Perms/Prohibs.
But to allow them to be specified at the Policy level - that then says all the Perms/Prohibs in the Policy use these entities. You could then has a target and assigner at the Policy level, then have 10 permissions in the policy, each with a different assignee.

XML ids are a necessary evil ;-)

**Comment by simonstey** [comment]
> You could then has a target and assigner at the Policy level, then have 10 permissions in the policy, each with a different assignee.

what happens if both policy + nested rules define e.g. targets/parties?

**Comment by riannella** [comment]
We would have a normative rule that if asset/party appears at Policy level, then it cannot appear at the Rule level. 
This does allow, say an assigner at the Policy level, and assignee's at the Rule level.

**Comment by simonstey** [comment]
what about inheritance?

**Comment by riannella** [comment]
If there are Asset/Parties at the Policy level in the Parent, they get inherited to the Child, along with any Rules.
Then in the newly inherited Policy (child+parent) the same rule applies.
If it already has Asset/Parties at the (child) policy level, then the outcome is an invalid policy.

**Comment by nitmws** [comment]
A note on inheritance inside a policy: the most flexible solution would be to permit having party/asset at the policy level and in addition at the P/P/D level too. The inheritance rule should be: the party/asset applying to a rule is the union of party/asset at the policy and at the rule level. 
(Practical view: as the data structure has party/asset at both levels I'm afraid sooner or later they will be used at both levels in a policy - ignoring the free-text specs ...)

**Comment by riannella** [comment]
Look at implications of inheritance model

**Comment by riannella** [comment]
WG agreed to the examples send to the list: 
https://lists.w3.org/Archives/Public/public-poe-wg/2017Jan/0004.html
https://lists.w3.org/Archives/Public/public-poe-wg/2017Jan/0005.html

**Comment by riannella** [comment]
Added new section on 3.1.1 Policy Structures
