### ISSUE TITLE
ODRL Processor & Test Suite

### ISSUE THREAD

**Issue by philarcher** [w3c/poe#86]
There are several sections of the ODRL model that talk about how ODRL should be processed. My strong recommendation is that these are collected into a specific section of the document that sets out methodically what a processor should do. An example would be https://www.w3.org/TR/powder-dr/#powderprocessor. This is backed up by a test suite, which is a feature of many standards. That is, you provide a set of sample ODRL policies and define what the output of the processor should be.

**Comment by riannella** [comment]
Process of validation is seperate from evaluation

ODRL Validator = check for conformance of the policy that is meets the ODRL IM (spec) requirements

ODRL Evaluator = determines whether the permissions and prohibitions of a policy are in effect
(based on the ODRL Validator conformance)

(add to the terminology)

Update IM to make clear where Validation and Evaluation occurs.
The latter when some external "black box" is referred to to resolve a constraint/duty

"black box" - checking that a constraint has been satisfied.
- external constraint checking system 

1. An ODRL Validator that checks that the ODRL is correct.
2. An ODRL Evaluator that determines whether or not a particular permission/obligation is in effect.
3. A Constraint Checker. This is any system that is able to return a satisfied/not satisfied response to the ODRL Evaluator

**Comment by philarcher** [comment]
OK, I've had a go at this as promised, and there's a pull request to match https://github.com/w3c/poe/pull/207. My approach was to work through the examples in the IM and note where the actions of an evaluator were either implied or expressed, and then tried to codify what it should do. It is not complete, but does, I hope show a possible way forward of the WG agrees with the general approach. IMO, we need to have such a prescriptive set of behaviours that an evaluator must follow as part of the normative spec.

**Comment by riannella** [comment]
(aside: respec renumbers all the examples automatically, so we can't refer to "Example 13" ;-(

**Comment by riannella** [comment]
Closing this, as the WG needs to create the Test Cases (so, no longer an issue)
