### ISSUE TITLE
Move Scenario Examples to Best Practices NOTE

### ISSUE THREAD

**Issue by riannella** [w3c/poe#88]
I propose to remove the Scenario Examples from the ODRL Vocab spec and move them to the ODRL Best Practices NOTE.
(They have already been removed from the ODRL Info Model)

**Comment by vroddon** [comment]
Agreed. Already started discussions with Ben.

**Comment by vroddon** [comment]
Now we have a large collection of RDF examples and JSON examples from the spec. 
Which shall be the notation for the best practices? Any help in making both of them possible?

**Comment by riannella** [comment]
Both is good.
Can you use: http://www.easyrdf.org/converter
