### ISSUE TITLE
normative vs non-normative vocabulary terms strategy?

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#93]
At POE calls it was said that a distinction of "normative" and "non-normative" could be applied to terms in the POE vocabulary - http://w3c.github.io/poe/vocab
All terms could have one of these two stati, having a look at them I can't see a strategy in some cases:

- Actions for Permissions and Prohibitions:
This is a hierarchical vocabulary with "use" (= making use of an asset) and "transfer" (= transferring ownership) as the only two top level terms. **Why is use normative and transfer non-normative?** (It can understand that all narrower and more granular terms are non-normative ...)
- Constraint Left Operands:
Out of the 31 Left Operand instances Absolute Asset Position, Count, Action Datetime or Period, Delivery Channel, Event Action, Industry Context, Language, Payment Amount, Purpose and  Recipient = **only 10 terms are normative - why these ones?**
- Constraint Operators, Party Functions:
Some are non-normative, the other terms are neither nor.

**In general it would be good to have written down rule for the normative/non-normative strategy.**

**Comment by riannella** [comment]
@nitmws The strategy was based on implementations. We took the ODRL Implementation survey as the first cut. See Issue #64 for snapshot of the implementation survey.
We will get updates from implementors over the next 6 months to update the term status.

The idea for this was that if there is only 1 implementor of a term/concept, then it would not be acceptable to W3C to standardise.

**Comment by nitmws** [comment]
Thanks @riannella for this clarification. Then we should wait with final non-/normative decisions until we have more feedback - would a good reason to ask IPTC members for one.
