### ISSUE TITLE
3.1 Policy

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#96]
> The Policy entity contains the following attributes:

-> A Policy has following attributes: 

> uid: the unique identification of the Policy entity (REQUIRED)

s/uid/id to align it with [json-ld's node identifier](http://json-ld.org/spec/latest/json-ld/#node-identifiers)?  `the unique id ..` e.g., OWL does not adhere to the [UNA ](https://en.wikipedia.org/wiki/Unique_name_assumption) -> s/the unique identification of/an identifier of ? 

> type: **indicates the semantics** of the Policy entity (REQUIRED). 

which trivially applies to all attributes of any of the concepts.. s/semantics/specific type 

> These are further described in the ODRL vocabulary [vocab-odrl] and ODRL Profiles.

I would also include that description, i.e., explanation of the diff. between different policy types, in the info model. remove `and ODRL Profiles`

> The uid attribute MUST be a unique identifier.

see above comment.. btw. why mentioning this here explicitely, but not in any of the other sections?

> This value MAY also impose further constraints on the Information Model.

on what? this document? what's the IM of a specific policy? constraints as in ODRL constraints?

> It is important that the type attribute be clearly understood in policy expressions as the semantics MAY impose restrictions on the expression language constructs such as cardinalities between entities.

clearly understood by whom? only the type attribute itself or its values? how does one verify *clear understanding*? It's already mentioned that different types may impose additional constraints, so why reiterate it here again?  

> For example, the ODRL Agreement Policy Type stipluates that it must contain two Parties (an Assigner and Assignee).

what's `it`? the policy type itself? a policy of type agreement? exactly 2? >= 2? what does `contain two Parties` mean? if a policy refers to 1000 different rules and only 1 refers to an assigner and only 1 other rule to an assignee, does this satisfy the agreement requirement? if not, why? 

> A Policy of type Set states that the Asset http//example.com/asset:9898 is the target of ..

any policy of type set? or only the one in example 1?

> the Permission read and the Prohibition reproduce. 

is the permission called read? -> the permission to perform action read on asset ...

> Two Parties are involved, namely the Assigner of the Permissions and the Party to be attributed.

s/Permissions/Permission

``` 
"@context": {
    "odrl": "http://www.w3.org/ns/odrl/2/"
    }
    "type":
``` 

all examples are missing a colon after `}` ->

``` 
"@context": {
    "odrl": "http://www.w3.org/ns/odrl/2/"
    }, 
    "type":
```

**Comment by riannella** [comment]
"uid" should be mapped to @id in json-ld section.

other changes made.

**Comment by simonstey** [comment]
[3.1 Policy](http://w3c.github.io/poe/model/#policy) states: 

> For example, the "Agreement" Policy type stipulates minimal cardinalities for some for the Information Model entities, which are different than the "Offer" Policy type. In addition, and more importantly, the **"Agreement" Policy type expresses that the Permissions/Prohibitions have been granted**, but the "Offer" Policy type does not. 

That's wrong, e.g. [3.4 Permission](http://w3c.github.io/poe/model/#permission) states: 

> The Permission entity MAY refer to one or more duty/ies. **The Duty expresses an obligation that MUST be fulfilled before the Permission being granted.**

or [following example in section 3.7](http://w3c.github.io/poe/model/#action):

> Example Use Case: The Party needs to define **an Offer policy granting a Permission** for the target Asset http://example.com/music:1012, namely the permission to play the Asset.

Also, can you **grant** someone a Prohibition? ;)

**Comment by riannella** [comment]
Updated to:

The Permission entity MAY refer to one or more <code>duty</code>/ies. The Duty expresses an obligation that MUST be fulfilled in order for the Permission to be valid.

and:

Example Use Case: The Party expresses an Offer policy for the target Asset http://example.com/music:1012, namely the Permission to play the Asset.

**Comment by riannella** [comment]
Grant can also mean "to be willing to concede" ;-)

https://www.merriam-webster.com/dictionary/grant
