### ISSUE TITLE
On prohibitions living alone

### ISSUE THREAD

**Issue by vroddon** [w3c/poe#97]
I understand a prohibition living alone may bring no new information whatsoever. But I would argue the following:

- **How to mark "All rights reserved" in a digital catalog?** (let's say of e-books). You can imagine a catalog, many of whose entries are waiving some rights with ODRL expressions. Great.
What shall we do with those entries (e-books) which have waived no right at all? Well, no permission at all. But it is a bit weird and makes more difficult the processing.
Facing a similar problem with language resources, we had to define a new license for that. Look at this:

`http://purl.oclc.org/NET/rdflicense/allrightsreserved
`
(If you click, by default you will get a redirect to Wikipedia's page. But it has content negotiation, if you demand RDF you will get the following odrl policy):

```
:allrightsreserved  a     odrl:Policy ;
        rdfs:comment      "This license does not disclose any of the IPR and database rights.."@en ;
        rdfs:label        "All rights reserved"@en ;
        cc:legalcode      <http://en.wikipedia.org/wiki/All_rights_reserved> ;
        dct:publisher     "None" ;
        odrl:prohibition  [ odrl:action  ldr:IPRRight , ldr:DatabaseRight ] .
```

- It is still useful as a reminder, even if redundant. In the first page of books I usually read "All rights reserved. You cannot fotocopy this book". Well, of course not. Still, it is nice to see it again.

**Comment by riannella** [comment]
@vroddon the good news is that the ODRL Info Model does support a policy with just a Prohibition.
The PolicyTypes makes that clear: https://w3c.github.io/poe/vocab/#policyTypes

A question about your example. You are prohibiting "odrl:action" ?

**Comment by vroddon** [comment]
@riannella 
1) ok! from yesterday's conversation I understood you were questioning this type of policy.
2) In the given example odrl:action is the property and we are just forbidding "IPR rights" and "Database rights". 
The only change I see is replacing "odrl:Policy" by the "odrl:Prohibition"
